// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mediaservice/media/v1/media.proto

package mediav1

import (
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaLifecycle int32

const (
	MediaLifecycle_MEDIA_LIFECYCLE_UNSPECIFIED MediaLifecycle = 0
	MediaLifecycle_MEDIA_LIFECYCLE_PENDING     MediaLifecycle = 1
	MediaLifecycle_MEDIA_LIFECYCLE_RUNNING     MediaLifecycle = 2
	MediaLifecycle_MEDIA_LIFECYCLE_COMPLETE    MediaLifecycle = 3
	MediaLifecycle_MEDIA_LIFECYCLE_FAILED      MediaLifecycle = 4
	MediaLifecycle_MEDIA_LIFECYCLE_DELETED     MediaLifecycle = 5
)

// Enum value maps for MediaLifecycle.
var (
	MediaLifecycle_name = map[int32]string{
		0: "MEDIA_LIFECYCLE_UNSPECIFIED",
		1: "MEDIA_LIFECYCLE_PENDING",
		2: "MEDIA_LIFECYCLE_RUNNING",
		3: "MEDIA_LIFECYCLE_COMPLETE",
		4: "MEDIA_LIFECYCLE_FAILED",
		5: "MEDIA_LIFECYCLE_DELETED",
	}
	MediaLifecycle_value = map[string]int32{
		"MEDIA_LIFECYCLE_UNSPECIFIED": 0,
		"MEDIA_LIFECYCLE_PENDING":     1,
		"MEDIA_LIFECYCLE_RUNNING":     2,
		"MEDIA_LIFECYCLE_COMPLETE":    3,
		"MEDIA_LIFECYCLE_FAILED":      4,
		"MEDIA_LIFECYCLE_DELETED":     5,
	}
)

func (x MediaLifecycle) Enum() *MediaLifecycle {
	p := new(MediaLifecycle)
	*p = x
	return p
}

func (x MediaLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_mediaservice_media_v1_media_proto_enumTypes[0].Descriptor()
}

func (MediaLifecycle) Type() protoreflect.EnumType {
	return &file_mediaservice_media_v1_media_proto_enumTypes[0]
}

func (x MediaLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaLifecycle.Descriptor instead.
func (MediaLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{0}
}

type AssetKind int32

const (
	AssetKind_ASSET_KIND_UNSPECIFIED AssetKind = 0
	AssetKind_ASSET_KIND_ORIGINAL    AssetKind = 1
	AssetKind_ASSET_KIND_DERIVED     AssetKind = 2
	AssetKind_ASSET_KIND_GENERATED   AssetKind = 3
)

// Enum value maps for AssetKind.
var (
	AssetKind_name = map[int32]string{
		0: "ASSET_KIND_UNSPECIFIED",
		1: "ASSET_KIND_ORIGINAL",
		2: "ASSET_KIND_DERIVED",
		3: "ASSET_KIND_GENERATED",
	}
	AssetKind_value = map[string]int32{
		"ASSET_KIND_UNSPECIFIED": 0,
		"ASSET_KIND_ORIGINAL":    1,
		"ASSET_KIND_DERIVED":     2,
		"ASSET_KIND_GENERATED":   3,
	}
)

func (x AssetKind) Enum() *AssetKind {
	p := new(AssetKind)
	*p = x
	return p
}

func (x AssetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_mediaservice_media_v1_media_proto_enumTypes[1].Descriptor()
}

func (AssetKind) Type() protoreflect.EnumType {
	return &file_mediaservice_media_v1_media_proto_enumTypes[1]
}

func (x AssetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetKind.Descriptor instead.
func (AssetKind) EnumDescriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{1}
}

type AssetRole int32

const (
	AssetRole_ASSET_ROLE_UNSPECIFIED AssetRole = 0
	AssetRole_ASSET_ROLE_ORIGINAL    AssetRole = 1
	AssetRole_ASSET_ROLE_THUMBNAIL   AssetRole = 2
	AssetRole_ASSET_ROLE_PREVIEW     AssetRole = 3
	AssetRole_ASSET_ROLE_DOWNLOAD    AssetRole = 4
	AssetRole_ASSET_ROLE_FINAL       AssetRole = 5
)

// Enum value maps for AssetRole.
var (
	AssetRole_name = map[int32]string{
		0: "ASSET_ROLE_UNSPECIFIED",
		1: "ASSET_ROLE_ORIGINAL",
		2: "ASSET_ROLE_THUMBNAIL",
		3: "ASSET_ROLE_PREVIEW",
		4: "ASSET_ROLE_DOWNLOAD",
		5: "ASSET_ROLE_FINAL",
	}
	AssetRole_value = map[string]int32{
		"ASSET_ROLE_UNSPECIFIED": 0,
		"ASSET_ROLE_ORIGINAL":    1,
		"ASSET_ROLE_THUMBNAIL":   2,
		"ASSET_ROLE_PREVIEW":     3,
		"ASSET_ROLE_DOWNLOAD":    4,
		"ASSET_ROLE_FINAL":       5,
	}
)

func (x AssetRole) Enum() *AssetRole {
	p := new(AssetRole)
	*p = x
	return p
}

func (x AssetRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetRole) Descriptor() protoreflect.EnumDescriptor {
	return file_mediaservice_media_v1_media_proto_enumTypes[2].Descriptor()
}

func (AssetRole) Type() protoreflect.EnumType {
	return &file_mediaservice_media_v1_media_proto_enumTypes[2]
}

func (x AssetRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetRole.Descriptor instead.
func (AssetRole) EnumDescriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{2}
}

type AssetOperation int32

const (
	AssetOperation_ASSET_OPERATION_UNSPECIFIED      AssetOperation = 0
	AssetOperation_ASSET_OPERATION_IMAGE_RESIZE     AssetOperation = 1
	AssetOperation_ASSET_OPERATION_IMAGE_THUMBNAIL  AssetOperation = 2
	AssetOperation_ASSET_OPERATION_GENERATION_FINAL AssetOperation = 3
)

// Enum value maps for AssetOperation.
var (
	AssetOperation_name = map[int32]string{
		0: "ASSET_OPERATION_UNSPECIFIED",
		1: "ASSET_OPERATION_IMAGE_RESIZE",
		2: "ASSET_OPERATION_IMAGE_THUMBNAIL",
		3: "ASSET_OPERATION_GENERATION_FINAL",
	}
	AssetOperation_value = map[string]int32{
		"ASSET_OPERATION_UNSPECIFIED":      0,
		"ASSET_OPERATION_IMAGE_RESIZE":     1,
		"ASSET_OPERATION_IMAGE_THUMBNAIL":  2,
		"ASSET_OPERATION_GENERATION_FINAL": 3,
	}
)

func (x AssetOperation) Enum() *AssetOperation {
	p := new(AssetOperation)
	*p = x
	return p
}

func (x AssetOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_mediaservice_media_v1_media_proto_enumTypes[3].Descriptor()
}

func (AssetOperation) Type() protoreflect.EnumType {
	return &file_mediaservice_media_v1_media_proto_enumTypes[3]
}

func (x AssetOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetOperation.Descriptor instead.
func (AssetOperation) EnumDescriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{3}
}

type AssetLifecycle int32

const (
	AssetLifecycle_ASSET_LIFECYCLE_UNSPECIFIED    AssetLifecycle = 0
	AssetLifecycle_ASSET_LIFECYCLE_PENDING_UPLOAD AssetLifecycle = 1
	AssetLifecycle_ASSET_LIFECYCLE_PENDING        AssetLifecycle = 2
	AssetLifecycle_ASSET_LIFECYCLE_PROCESSING     AssetLifecycle = 3
	AssetLifecycle_ASSET_LIFECYCLE_COMPLETE       AssetLifecycle = 4
	AssetLifecycle_ASSET_LIFECYCLE_FAILED         AssetLifecycle = 5
	AssetLifecycle_ASSET_LIFECYCLE_DELETED        AssetLifecycle = 6
)

// Enum value maps for AssetLifecycle.
var (
	AssetLifecycle_name = map[int32]string{
		0: "ASSET_LIFECYCLE_UNSPECIFIED",
		1: "ASSET_LIFECYCLE_PENDING_UPLOAD",
		2: "ASSET_LIFECYCLE_PENDING",
		3: "ASSET_LIFECYCLE_PROCESSING",
		4: "ASSET_LIFECYCLE_COMPLETE",
		5: "ASSET_LIFECYCLE_FAILED",
		6: "ASSET_LIFECYCLE_DELETED",
	}
	AssetLifecycle_value = map[string]int32{
		"ASSET_LIFECYCLE_UNSPECIFIED":    0,
		"ASSET_LIFECYCLE_PENDING_UPLOAD": 1,
		"ASSET_LIFECYCLE_PENDING":        2,
		"ASSET_LIFECYCLE_PROCESSING":     3,
		"ASSET_LIFECYCLE_COMPLETE":       4,
		"ASSET_LIFECYCLE_FAILED":         5,
		"ASSET_LIFECYCLE_DELETED":        6,
	}
)

func (x AssetLifecycle) Enum() *AssetLifecycle {
	p := new(AssetLifecycle)
	*p = x
	return p
}

func (x AssetLifecycle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetLifecycle) Descriptor() protoreflect.EnumDescriptor {
	return file_mediaservice_media_v1_media_proto_enumTypes[4].Descriptor()
}

func (AssetLifecycle) Type() protoreflect.EnumType {
	return &file_mediaservice_media_v1_media_proto_enumTypes[4]
}

func (x AssetLifecycle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetLifecycle.Descriptor instead.
func (AssetLifecycle) EnumDescriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{4}
}

type Visibility int32

const (
	Visibility_VISIBILITY_UNSPECIFIED   Visibility = 0
	Visibility_VISIBILITY_OWNER_PRIVATE Visibility = 1
	Visibility_VISIBILITY_TENANT_SHARED Visibility = 2
)

// Enum value maps for Visibility.
var (
	Visibility_name = map[int32]string{
		0: "VISIBILITY_UNSPECIFIED",
		1: "VISIBILITY_OWNER_PRIVATE",
		2: "VISIBILITY_TENANT_SHARED",
	}
	Visibility_value = map[string]int32{
		"VISIBILITY_UNSPECIFIED":   0,
		"VISIBILITY_OWNER_PRIVATE": 1,
		"VISIBILITY_TENANT_SHARED": 2,
	}
)

func (x Visibility) Enum() *Visibility {
	p := new(Visibility)
	*p = x
	return p
}

func (x Visibility) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Visibility) Descriptor() protoreflect.EnumDescriptor {
	return file_mediaservice_media_v1_media_proto_enumTypes[5].Descriptor()
}

func (Visibility) Type() protoreflect.EnumType {
	return &file_mediaservice_media_v1_media_proto_enumTypes[5]
}

func (x Visibility) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Visibility.Descriptor instead.
func (Visibility) EnumDescriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{5}
}

type Provenance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	AiGenerated   bool                   `protobuf:"varint,3,opt,name=ai_generated,json=aiGenerated,proto3" json:"ai_generated,omitempty"`
	Disclosure    string                 `protobuf:"bytes,4,opt,name=disclosure,proto3" json:"disclosure,omitempty"`
	Watermark     string                 `protobuf:"bytes,5,opt,name=watermark,proto3" json:"watermark,omitempty"`
	Safety        string                 `protobuf:"bytes,6,opt,name=safety,proto3" json:"safety,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *Provenance) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Provenance) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Provenance) GetAiGenerated() bool {
	if x != nil {
		return x.AiGenerated
	}
	return false
}

func (x *Provenance) GetDisclosure() string {
	if x != nil {
		return x.Disclosure
	}
	return ""
}

func (x *Provenance) GetWatermark() string {
	if x != nil {
		return x.Watermark
	}
	return ""
}

func (x *Provenance) GetSafety() string {
	if x != nil {
		return x.Safety
	}
	return ""
}

type DesiredSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputFormat  string                 `protobuf:"bytes,1,opt,name=output_format,json=outputFormat,proto3" json:"output_format,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredSpec) Reset() {
	*x = DesiredSpec{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredSpec) ProtoMessage() {}

func (x *DesiredSpec) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredSpec.ProtoReflect.Descriptor instead.
func (*DesiredSpec) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *DesiredSpec) GetOutputFormat() string {
	if x != nil {
		return x.OutputFormat
	}
	return ""
}

func (x *DesiredSpec) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *DesiredSpec) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *DesiredSpec) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Media struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaId         string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OwnerUserId     string                 `protobuf:"bytes,3,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Origin          v1.Origin              `protobuf:"varint,4,opt,name=origin,proto3,enum=mediaservice.common.v1.Origin" json:"origin,omitempty"`
	MediaType       v1.MediaType           `protobuf:"varint,5,opt,name=media_type,json=mediaType,proto3,enum=mediaservice.common.v1.MediaType" json:"media_type,omitempty"`
	Lifecycle       MediaLifecycle         `protobuf:"varint,6,opt,name=lifecycle,proto3,enum=mediaservice.media.v1.MediaLifecycle" json:"lifecycle,omitempty"`
	OriginalAssetId string                 `protobuf:"bytes,7,opt,name=original_asset_id,json=originalAssetId,proto3" json:"original_asset_id,omitempty"`
	WebhookUrl      string                 `protobuf:"bytes,8,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Visibility      Visibility             `protobuf:"varint,13,opt,name=visibility,proto3,enum=mediaservice.media.v1.Visibility" json:"visibility,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *Media) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Media) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Media) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Media) GetOrigin() v1.Origin {
	if x != nil {
		return x.Origin
	}
	return v1.Origin(0)
}

func (x *Media) GetMediaType() v1.MediaType {
	if x != nil {
		return x.MediaType
	}
	return v1.MediaType(0)
}

func (x *Media) GetLifecycle() MediaLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return MediaLifecycle_MEDIA_LIFECYCLE_UNSPECIFIED
}

func (x *Media) GetOriginalAssetId() string {
	if x != nil {
		return x.OriginalAssetId
	}
	return ""
}

func (x *Media) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Media) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Media) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Media) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Media) GetVisibility() Visibility {
	if x != nil {
		return x.Visibility
	}
	return Visibility_VISIBILITY_UNSPECIFIED
}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	MediaId       string                 `protobuf:"bytes,2,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Kind          AssetKind              `protobuf:"varint,4,opt,name=kind,proto3,enum=mediaservice.media.v1.AssetKind" json:"kind,omitempty"`
	Role          AssetRole              `protobuf:"varint,5,opt,name=role,proto3,enum=mediaservice.media.v1.AssetRole" json:"role,omitempty"`
	Operation     AssetOperation         `protobuf:"varint,6,opt,name=operation,proto3,enum=mediaservice.media.v1.AssetOperation" json:"operation,omitempty"`
	Lifecycle     AssetLifecycle         `protobuf:"varint,7,opt,name=lifecycle,proto3,enum=mediaservice.media.v1.AssetLifecycle" json:"lifecycle,omitempty"`
	SourceAssetId string                 `protobuf:"bytes,8,opt,name=source_asset_id,json=sourceAssetId,proto3" json:"source_asset_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,9,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	ContentType   string                 `protobuf:"bytes,10,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Extension     string                 `protobuf:"bytes,11,opt,name=extension,proto3" json:"extension,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,12,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        string                 `protobuf:"bytes,13,opt,name=sha256,proto3" json:"sha256,omitempty"`
	DesiredSpec   *DesiredSpec           `protobuf:"bytes,14,opt,name=desired_spec,json=desiredSpec,proto3" json:"desired_spec,omitempty"`
	Provenance    *Provenance            `protobuf:"bytes,15,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Attempts      uint32                 `protobuf:"varint,16,opt,name=attempts,proto3" json:"attempts,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,17,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,18,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *Asset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *Asset) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *Asset) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Asset) GetKind() AssetKind {
	if x != nil {
		return x.Kind
	}
	return AssetKind_ASSET_KIND_UNSPECIFIED
}

func (x *Asset) GetRole() AssetRole {
	if x != nil {
		return x.Role
	}
	return AssetRole_ASSET_ROLE_UNSPECIFIED
}

func (x *Asset) GetOperation() AssetOperation {
	if x != nil {
		return x.Operation
	}
	return AssetOperation_ASSET_OPERATION_UNSPECIFIED
}

func (x *Asset) GetLifecycle() AssetLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return AssetLifecycle_ASSET_LIFECYCLE_UNSPECIFIED
}

func (x *Asset) GetSourceAssetId() string {
	if x != nil {
		return x.SourceAssetId
	}
	return ""
}

func (x *Asset) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *Asset) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Asset) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *Asset) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Asset) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Asset) GetDesiredSpec() *DesiredSpec {
	if x != nil {
		return x.DesiredSpec
	}
	return nil
}

func (x *Asset) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *Asset) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Asset) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Asset) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListMediaRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Cursor         string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit          uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	MediaType      v1.MediaType           `protobuf:"varint,3,opt,name=media_type,json=mediaType,proto3,enum=mediaservice.common.v1.MediaType" json:"media_type,omitempty"`
	Origin         v1.Origin              `protobuf:"varint,4,opt,name=origin,proto3,enum=mediaservice.common.v1.Origin" json:"origin,omitempty"`
	IncludeDeleted bool                   `protobuf:"varint,5,opt,name=include_deleted,json=includeDeleted,proto3" json:"include_deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMediaRequest) Reset() {
	*x = ListMediaRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaRequest) ProtoMessage() {}

func (x *ListMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaRequest.ProtoReflect.Descriptor instead.
func (*ListMediaRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *ListMediaRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMediaRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMediaRequest) GetMediaType() v1.MediaType {
	if x != nil {
		return x.MediaType
	}
	return v1.MediaType(0)
}

func (x *ListMediaRequest) GetOrigin() v1.Origin {
	if x != nil {
		return x.Origin
	}
	return v1.Origin(0)
}

func (x *ListMediaRequest) GetIncludeDeleted() bool {
	if x != nil {
		return x.IncludeDeleted
	}
	return false
}

type ListMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Media               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMediaResponse) Reset() {
	*x = ListMediaResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMediaResponse) ProtoMessage() {}

func (x *ListMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMediaResponse.ProtoReflect.Descriptor instead.
func (*ListMediaResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *ListMediaResponse) GetItems() []*Media {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMediaResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListMediaResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaResponse) Reset() {
	*x = GetMediaResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaResponse) ProtoMessage() {}

func (x *GetMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaResponse.ProtoReflect.Descriptor instead.
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetMediaResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type DeleteMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaRequest) Reset() {
	*x = DeleteMediaRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaRequest) ProtoMessage() {}

func (x *DeleteMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMediaRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type DeleteMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaResponse) Reset() {
	*x = DeleteMediaResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaResponse) ProtoMessage() {}

func (x *DeleteMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{9}
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *ListAssetsRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type ListAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{12}
}

func (x *GetAssetRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type GetAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetResponse) Reset() {
	*x = GetAssetResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetResponse) ProtoMessage() {}

func (x *GetAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetResponse.ProtoReflect.Descriptor instead.
func (*GetAssetResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{13}
}

func (x *GetAssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type CreateAssetsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MediaId        string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Operations     []AssetOperation       `protobuf:"varint,3,rep,packed,name=operations,proto3,enum=mediaservice.media.v1.AssetOperation" json:"operations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAssetsRequest) Reset() {
	*x = CreateAssetsRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetsRequest) ProtoMessage() {}

func (x *CreateAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetsRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetsRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{14}
}

func (x *CreateAssetsRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateAssetsRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateAssetsRequest) GetOperations() []AssetOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type AssetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     AssetOperation         `protobuf:"varint,1,opt,name=operation,proto3,enum=mediaservice.media.v1.AssetOperation" json:"operation,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Lifecycle     AssetLifecycle         `protobuf:"varint,3,opt,name=lifecycle,proto3,enum=mediaservice.media.v1.AssetLifecycle" json:"lifecycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetRef) Reset() {
	*x = AssetRef{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetRef) ProtoMessage() {}

func (x *AssetRef) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetRef.ProtoReflect.Descriptor instead.
func (*AssetRef) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{15}
}

func (x *AssetRef) GetOperation() AssetOperation {
	if x != nil {
		return x.Operation
	}
	return AssetOperation_ASSET_OPERATION_UNSPECIFIED
}

func (x *AssetRef) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetRef) GetLifecycle() AssetLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return AssetLifecycle_ASSET_LIFECYCLE_UNSPECIFIED
}

type CreateAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Assets        []*AssetRef            `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets,omitempty"`
	Replay        bool                   `protobuf:"varint,3,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetsResponse) Reset() {
	*x = CreateAssetsResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetsResponse) ProtoMessage() {}

func (x *CreateAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetsResponse.ProtoReflect.Descriptor instead.
func (*CreateAssetsResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAssetsResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateAssetsResponse) GetAssets() []*AssetRef {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *CreateAssetsResponse) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

type RetryAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryAssetRequest) Reset() {
	*x = RetryAssetRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryAssetRequest) ProtoMessage() {}

func (x *RetryAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryAssetRequest.ProtoReflect.Descriptor instead.
func (*RetryAssetRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{17}
}

func (x *RetryAssetRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *RetryAssetRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

type RetryAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryAssetResponse) Reset() {
	*x = RetryAssetResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryAssetResponse) ProtoMessage() {}

func (x *RetryAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryAssetResponse.ProtoReflect.Descriptor instead.
func (*RetryAssetResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{18}
}

func (x *RetryAssetResponse) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

type InitPresignedUploadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	WebhookUrl     string                 `protobuf:"bytes,5,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	OwnerUserId    string                 `protobuf:"bytes,6,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitPresignedUploadRequest) Reset() {
	*x = InitPresignedUploadRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPresignedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPresignedUploadRequest) ProtoMessage() {}

func (x *InitPresignedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPresignedUploadRequest.ProtoReflect.Descriptor instead.
func (*InitPresignedUploadRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{19}
}

func (x *InitPresignedUploadRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *InitPresignedUploadRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *InitPresignedUploadRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitPresignedUploadRequest) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *InitPresignedUploadRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *InitPresignedUploadRequest) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

type InitPresignedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,4,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresIn     uint32                 `protobuf:"varint,7,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitPresignedUploadResponse) Reset() {
	*x = InitPresignedUploadResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPresignedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPresignedUploadResponse) ProtoMessage() {}

func (x *InitPresignedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPresignedUploadResponse.ProtoReflect.Descriptor instead.
func (*InitPresignedUploadResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{20}
}

func (x *InitPresignedUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *InitPresignedUploadResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *InitPresignedUploadResponse) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *InitPresignedUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *InitPresignedUploadResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *InitPresignedUploadResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *InitPresignedUploadResponse) GetExpiresIn() uint32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *InitPresignedUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RefreshPresignedUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPresignedUploadRequest) Reset() {
	*x = RefreshPresignedUploadRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPresignedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPresignedUploadRequest) ProtoMessage() {}

func (x *RefreshPresignedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPresignedUploadRequest.ProtoReflect.Descriptor instead.
func (*RefreshPresignedUploadRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{21}
}

func (x *RefreshPresignedUploadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type RefreshPresignedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StorageKey    string                 `protobuf:"bytes,3,opt,name=storage_key,json=storageKey,proto3" json:"storage_key,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,4,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	Method        string                 `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiresIn     uint32                 `protobuf:"varint,7,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPresignedUploadResponse) Reset() {
	*x = RefreshPresignedUploadResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPresignedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPresignedUploadResponse) ProtoMessage() {}

func (x *RefreshPresignedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPresignedUploadResponse.ProtoReflect.Descriptor instead.
func (*RefreshPresignedUploadResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{22}
}

func (x *RefreshPresignedUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *RefreshPresignedUploadResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *RefreshPresignedUploadResponse) GetStorageKey() string {
	if x != nil {
		return x.StorageKey
	}
	return ""
}

func (x *RefreshPresignedUploadResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *RefreshPresignedUploadResponse) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RefreshPresignedUploadResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RefreshPresignedUploadResponse) GetExpiresIn() uint32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *RefreshPresignedUploadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CompletePresignedUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletePresignedUploadRequest) Reset() {
	*x = CompletePresignedUploadRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletePresignedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePresignedUploadRequest) ProtoMessage() {}

func (x *CompletePresignedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePresignedUploadRequest.ProtoReflect.Descriptor instead.
func (*CompletePresignedUploadRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{23}
}

func (x *CompletePresignedUploadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type CompletePresignedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Lifecycle     AssetLifecycle         `protobuf:"varint,3,opt,name=lifecycle,proto3,enum=mediaservice.media.v1.AssetLifecycle" json:"lifecycle,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Etag          string                 `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletePresignedUploadResponse) Reset() {
	*x = CompletePresignedUploadResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletePresignedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletePresignedUploadResponse) ProtoMessage() {}

func (x *CompletePresignedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletePresignedUploadResponse.ProtoReflect.Descriptor instead.
func (*CompletePresignedUploadResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{24}
}

func (x *CompletePresignedUploadResponse) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CompletePresignedUploadResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CompletePresignedUploadResponse) GetLifecycle() AssetLifecycle {
	if x != nil {
		return x.Lifecycle
	}
	return AssetLifecycle_ASSET_LIFECYCLE_UNSPECIFIED
}

func (x *CompletePresignedUploadResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CompletePresignedUploadResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CompletePresignedUploadResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type PresignAssetDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignAssetDownloadRequest) Reset() {
	*x = PresignAssetDownloadRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignAssetDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignAssetDownloadRequest) ProtoMessage() {}

func (x *PresignAssetDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignAssetDownloadRequest.ProtoReflect.Descriptor instead.
func (*PresignAssetDownloadRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{25}
}

func (x *PresignAssetDownloadRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *PresignAssetDownloadRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PresignAssetDownloadRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type PresignAssetDownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresIn     uint32                 `protobuf:"varint,2,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresignAssetDownloadResponse) Reset() {
	*x = PresignAssetDownloadResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresignAssetDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresignAssetDownloadResponse) ProtoMessage() {}

func (x *PresignAssetDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresignAssetDownloadResponse.ProtoReflect.Descriptor instead.
func (*PresignAssetDownloadResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{26}
}

func (x *PresignAssetDownloadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PresignAssetDownloadResponse) GetExpiresIn() uint32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *PresignAssetDownloadResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// GetMediaRoleURLRequest resolves a role selector to the matching COMPLETE asset under a media id and returns a presigned GET URL.
type GetMediaRoleURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Role          AssetRole              `protobuf:"varint,2,opt,name=role,proto3,enum=mediaservice.media.v1.AssetRole" json:"role,omitempty"`
	TtlSeconds    uint32                 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRoleURLRequest) Reset() {
	*x = GetMediaRoleURLRequest{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRoleURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRoleURLRequest) ProtoMessage() {}

func (x *GetMediaRoleURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRoleURLRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRoleURLRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{27}
}

func (x *GetMediaRoleURLRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *GetMediaRoleURLRequest) GetRole() AssetRole {
	if x != nil {
		return x.Role
	}
	return AssetRole_ASSET_ROLE_UNSPECIFIED
}

func (x *GetMediaRoleURLRequest) GetTtlSeconds() uint32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type GetMediaRoleURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       string                 `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRoleURLResponse) Reset() {
	*x = GetMediaRoleURLResponse{}
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRoleURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRoleURLResponse) ProtoMessage() {}

func (x *GetMediaRoleURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_media_v1_media_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRoleURLResponse.ProtoReflect.Descriptor instead.
func (*GetMediaRoleURLResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_media_v1_media_proto_rawDescGZIP(), []int{28}
}

func (x *GetMediaRoleURLResponse) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *GetMediaRoleURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetMediaRoleURLResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *GetMediaRoleURLResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GetMediaRoleURLResponse) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

var File_mediaservice_media_v1_media_proto protoreflect.FileDescriptor

const file_mediaservice_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"!mediaservice/media/v1/media.proto\x12\x15mediaservice.media.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a#mediaservice/common/v1/common.proto\"\xb7\x01\n" +
	"\n" +
	"Provenance\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12!\n" +
	"\fai_generated\x18\x03 \x01(\bR\vaiGenerated\x12\x1e\n" +
	"\n" +
	"disclosure\x18\x04 \x01(\tR\n" +
	"disclosure\x12\x1c\n" +
	"\twatermark\x18\x05 \x01(\tR\twatermark\x12\x16\n" +
	"\x06safety\x18\x06 \x01(\tR\x06safety\"t\n" +
	"\vDesiredSpec\x12#\n" +
	"\routput_format\x18\x01 \x01(\tR\foutputFormat\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\x9e\x05\n" +
	"\x05Media\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\"\n" +
	"\rowner_user_id\x18\x03 \x01(\tR\vownerUserId\x126\n" +
	"\x06origin\x18\x04 \x01(\x0e2\x1e.mediaservice.common.v1.OriginR\x06origin\x12@\n" +
	"\n" +
	"media_type\x18\x05 \x01(\x0e2!.mediaservice.common.v1.MediaTypeR\tmediaType\x12C\n" +
	"\tlifecycle\x18\x06 \x01(\x0e2%.mediaservice.media.v1.MediaLifecycleR\tlifecycle\x12*\n" +
	"\x11original_asset_id\x18\a \x01(\tR\x0foriginalAssetId\x12\x1f\n" +
	"\vwebhook_url\x18\b \x01(\tR\n" +
	"webhookUrl\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x129\n" +
	"\n" +
	"expires_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12A\n" +
	"\n" +
	"visibility\x18\r \x01(\x0e2!.mediaservice.media.v1.VisibilityR\n" +
	"visibility\"\xf1\x06\n" +
	"\x05Asset\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x19\n" +
	"\bmedia_id\x18\x02 \x01(\tR\amediaId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x124\n" +
	"\x04kind\x18\x04 \x01(\x0e2 .mediaservice.media.v1.AssetKindR\x04kind\x124\n" +
	"\x04role\x18\x05 \x01(\x0e2 .mediaservice.media.v1.AssetRoleR\x04role\x12C\n" +
	"\toperation\x18\x06 \x01(\x0e2%.mediaservice.media.v1.AssetOperationR\toperation\x12C\n" +
	"\tlifecycle\x18\a \x01(\x0e2%.mediaservice.media.v1.AssetLifecycleR\tlifecycle\x12&\n" +
	"\x0fsource_asset_id\x18\b \x01(\tR\rsourceAssetId\x12\x1f\n" +
	"\vstorage_key\x18\t \x01(\tR\n" +
	"storageKey\x12!\n" +
	"\fcontent_type\x18\n" +
	" \x01(\tR\vcontentType\x12\x1c\n" +
	"\textension\x18\v \x01(\tR\textension\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\f \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\r \x01(\tR\x06sha256\x12E\n" +
	"\fdesired_spec\x18\x0e \x01(\v2\".mediaservice.media.v1.DesiredSpecR\vdesiredSpec\x12A\n" +
	"\n" +
	"provenance\x18\x0f \x01(\v2!.mediaservice.media.v1.ProvenanceR\n" +
	"provenance\x12\x1a\n" +
	"\battempts\x18\x10 \x01(\rR\battempts\x12\x1d\n" +
	"\n" +
	"error_code\x18\x11 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x12 \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe3\x01\n" +
	"\x10ListMediaRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12@\n" +
	"\n" +
	"media_type\x18\x03 \x01(\x0e2!.mediaservice.common.v1.MediaTypeR\tmediaType\x126\n" +
	"\x06origin\x18\x04 \x01(\x0e2\x1e.mediaservice.common.v1.OriginR\x06origin\x12'\n" +
	"\x0finclude_deleted\x18\x05 \x01(\bR\x0eincludeDeleted\"\x83\x01\n" +
	"\x11ListMediaResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.mediaservice.media.v1.MediaR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\",\n" +
	"\x0fGetMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"F\n" +
	"\x10GetMediaResponse\x122\n" +
	"\x05media\x18\x01 \x01(\v2\x1c.mediaservice.media.v1.MediaR\x05media\"/\n" +
	"\x12DeleteMediaRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\x15\n" +
	"\x13DeleteMediaResponse\".\n" +
	"\x11ListAssetsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"J\n" +
	"\x12ListAssetsResponse\x124\n" +
	"\x06assets\x18\x01 \x03(\v2\x1c.mediaservice.media.v1.AssetR\x06assets\"G\n" +
	"\x0fGetAssetRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"F\n" +
	"\x10GetAssetResponse\x122\n" +
	"\x05asset\x18\x01 \x01(\v2\x1c.mediaservice.media.v1.AssetR\x05asset\"\xa0\x01\n" +
	"\x13CreateAssetsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12E\n" +
	"\n" +
	"operations\x18\x03 \x03(\x0e2%.mediaservice.media.v1.AssetOperationR\n" +
	"operations\"\xaf\x01\n" +
	"\bAssetRef\x12C\n" +
	"\toperation\x18\x01 \x01(\x0e2%.mediaservice.media.v1.AssetOperationR\toperation\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12C\n" +
	"\tlifecycle\x18\x03 \x01(\x0e2%.mediaservice.media.v1.AssetLifecycleR\tlifecycle\"\x82\x01\n" +
	"\x14CreateAssetsResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x127\n" +
	"\x06assets\x18\x02 \x03(\v2\x1f.mediaservice.media.v1.AssetRefR\x06assets\x12\x16\n" +
	"\x06replay\x18\x03 \x01(\bR\x06replay\"I\n" +
	"\x11RetryAssetRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\"H\n" +
	"\x12RetryAssetResponse\x122\n" +
	"\x05asset\x18\x01 \x01(\v2\x1c.mediaservice.media.v1.AssetR\x05asset\"\xe8\x01\n" +
	"\x1aInitPresignedUploadRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1f\n" +
	"\vwebhook_url\x18\x05 \x01(\tR\n" +
	"webhookUrl\x12\"\n" +
	"\rowner_user_id\x18\x06 \x01(\tR\vownerUserId\"\x9c\x03\n" +
	"\x1bInitPresignedUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x04 \x01(\tR\tuploadUrl\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12Y\n" +
	"\aheaders\x18\x06 \x03(\v2?.mediaservice.media.v1.InitPresignedUploadResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_in\x18\a \x01(\rR\texpiresIn\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x1dRefreshPresignedUploadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\xa2\x03\n" +
	"\x1eRefreshPresignedUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1f\n" +
	"\vstorage_key\x18\x03 \x01(\tR\n" +
	"storageKey\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x04 \x01(\tR\tuploadUrl\x12\x16\n" +
	"\x06method\x18\x05 \x01(\tR\x06method\x12\\\n" +
	"\aheaders\x18\x06 \x03(\v2B.mediaservice.media.v1.RefreshPresignedUploadResponse.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"expires_in\x18\a \x01(\rR\texpiresIn\x129\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\";\n" +
	"\x1eCompletePresignedUploadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"\xf2\x01\n" +
	"\x1fCompletePresignedUploadResponse\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12C\n" +
	"\tlifecycle\x18\x03 \x01(\x0e2%.mediaservice.media.v1.AssetLifecycleR\tlifecycle\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\tR\x04etag\"t\n" +
	"\x1bPresignAssetDownloadRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\"\x8a\x01\n" +
	"\x1cPresignAssetDownloadResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x02 \x01(\rR\texpiresIn\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x8a\x01\n" +
	"\x16GetMediaRoleURLRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x124\n" +
	"\x04role\x18\x02 \x01(\x0e2 .mediaservice.media.v1.AssetRoleR\x04role\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\rR\n" +
	"ttlSeconds\"\xc3\x01\n" +
	"\x17GetMediaRoleURLResponse\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\tR\aassetId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x04R\tsizeBytes*\xc2\x01\n" +
	"\x0eMediaLifecycle\x12\x1f\n" +
	"\x1bMEDIA_LIFECYCLE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17MEDIA_LIFECYCLE_PENDING\x10\x01\x12\x1b\n" +
	"\x17MEDIA_LIFECYCLE_RUNNING\x10\x02\x12\x1c\n" +
	"\x18MEDIA_LIFECYCLE_COMPLETE\x10\x03\x12\x1a\n" +
	"\x16MEDIA_LIFECYCLE_FAILED\x10\x04\x12\x1b\n" +
	"\x17MEDIA_LIFECYCLE_DELETED\x10\x05*r\n" +
	"\tAssetKind\x12\x1a\n" +
	"\x16ASSET_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ASSET_KIND_ORIGINAL\x10\x01\x12\x16\n" +
	"\x12ASSET_KIND_DERIVED\x10\x02\x12\x18\n" +
	"\x14ASSET_KIND_GENERATED\x10\x03*\xa1\x01\n" +
	"\tAssetRole\x12\x1a\n" +
	"\x16ASSET_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ASSET_ROLE_ORIGINAL\x10\x01\x12\x18\n" +
	"\x14ASSET_ROLE_THUMBNAIL\x10\x02\x12\x16\n" +
	"\x12ASSET_ROLE_PREVIEW\x10\x03\x12\x17\n" +
	"\x13ASSET_ROLE_DOWNLOAD\x10\x04\x12\x14\n" +
	"\x10ASSET_ROLE_FINAL\x10\x05*\x9e\x01\n" +
	"\x0eAssetOperation\x12\x1f\n" +
	"\x1bASSET_OPERATION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cASSET_OPERATION_IMAGE_RESIZE\x10\x01\x12#\n" +
	"\x1fASSET_OPERATION_IMAGE_THUMBNAIL\x10\x02\x12$\n" +
	" ASSET_OPERATION_GENERATION_FINAL\x10\x03*\xe9\x01\n" +
	"\x0eAssetLifecycle\x12\x1f\n" +
	"\x1bASSET_LIFECYCLE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eASSET_LIFECYCLE_PENDING_UPLOAD\x10\x01\x12\x1b\n" +
	"\x17ASSET_LIFECYCLE_PENDING\x10\x02\x12\x1e\n" +
	"\x1aASSET_LIFECYCLE_PROCESSING\x10\x03\x12\x1c\n" +
	"\x18ASSET_LIFECYCLE_COMPLETE\x10\x04\x12\x1a\n" +
	"\x16ASSET_LIFECYCLE_FAILED\x10\x05\x12\x1b\n" +
	"\x17ASSET_LIFECYCLE_DELETED\x10\x06*d\n" +
	"\n" +
	"Visibility\x12\x1a\n" +
	"\x16VISIBILITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18VISIBILITY_OWNER_PRIVATE\x10\x01\x12\x1c\n" +
	"\x18VISIBILITY_TENANT_SHARED\x10\x022\xc1\n" +
	"\n" +
	"\fMediaService\x12^\n" +
	"\tListMedia\x12'.mediaservice.media.v1.ListMediaRequest\x1a(.mediaservice.media.v1.ListMediaResponse\x12[\n" +
	"\bGetMedia\x12&.mediaservice.media.v1.GetMediaRequest\x1a'.mediaservice.media.v1.GetMediaResponse\x12d\n" +
	"\vDeleteMedia\x12).mediaservice.media.v1.DeleteMediaRequest\x1a*.mediaservice.media.v1.DeleteMediaResponse\x12a\n" +
	"\n" +
	"ListAssets\x12(.mediaservice.media.v1.ListAssetsRequest\x1a).mediaservice.media.v1.ListAssetsResponse\x12[\n" +
	"\bGetAsset\x12&.mediaservice.media.v1.GetAssetRequest\x1a'.mediaservice.media.v1.GetAssetResponse\x12g\n" +
	"\fCreateAssets\x12*.mediaservice.media.v1.CreateAssetsRequest\x1a+.mediaservice.media.v1.CreateAssetsResponse\x12a\n" +
	"\n" +
	"RetryAsset\x12(.mediaservice.media.v1.RetryAssetRequest\x1a).mediaservice.media.v1.RetryAssetResponse\x12|\n" +
	"\x13InitPresignedUpload\x121.mediaservice.media.v1.InitPresignedUploadRequest\x1a2.mediaservice.media.v1.InitPresignedUploadResponse\x12\x85\x01\n" +
	"\x16RefreshPresignedUpload\x124.mediaservice.media.v1.RefreshPresignedUploadRequest\x1a5.mediaservice.media.v1.RefreshPresignedUploadResponse\x12\x88\x01\n" +
	"\x17CompletePresignedUpload\x125.mediaservice.media.v1.CompletePresignedUploadRequest\x1a6.mediaservice.media.v1.CompletePresignedUploadResponse\x12\x7f\n" +
	"\x14PresignAssetDownload\x122.mediaservice.media.v1.PresignAssetDownloadRequest\x1a3.mediaservice.media.v1.PresignAssetDownloadResponse\x12p\n" +
	"\x0fGetMediaRoleURL\x12-.mediaservice.media.v1.GetMediaRoleURLRequest\x1a..mediaservice.media.v1.GetMediaRoleURLResponseB\xfe\x01\n" +
	"\x19com.mediaservice.media.v1B\n" +
	"MediaProtoP\x01Z_github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/media/v1;mediav1\xa2\x02\x03MMX\xaa\x02\x15Mediaservice.Media.V1\xca\x02\x15Mediaservice\\Media\\V1\xe2\x02!Mediaservice\\Media\\V1\\GPBMetadata\xea\x02\x17Mediaservice::Media::V1b\x06proto3"

var (
	file_mediaservice_media_v1_media_proto_rawDescOnce sync.Once
	file_mediaservice_media_v1_media_proto_rawDescData []byte
)

func file_mediaservice_media_v1_media_proto_rawDescGZIP() []byte {
	file_mediaservice_media_v1_media_proto_rawDescOnce.Do(func() {
		file_mediaservice_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mediaservice_media_v1_media_proto_rawDesc), len(file_mediaservice_media_v1_media_proto_rawDesc)))
	})
	return file_mediaservice_media_v1_media_proto_rawDescData
}

var file_mediaservice_media_v1_media_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_mediaservice_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_mediaservice_media_v1_media_proto_goTypes = []any{
	(MediaLifecycle)(0),                     // 0: mediaservice.media.v1.MediaLifecycle
	(AssetKind)(0),                          // 1: mediaservice.media.v1.AssetKind
	(AssetRole)(0),                          // 2: mediaservice.media.v1.AssetRole
	(AssetOperation)(0),                     // 3: mediaservice.media.v1.AssetOperation
	(AssetLifecycle)(0),                     // 4: mediaservice.media.v1.AssetLifecycle
	(Visibility)(0),                         // 5: mediaservice.media.v1.Visibility
	(*Provenance)(nil),                      // 6: mediaservice.media.v1.Provenance
	(*DesiredSpec)(nil),                     // 7: mediaservice.media.v1.DesiredSpec
	(*Media)(nil),                           // 8: mediaservice.media.v1.Media
	(*Asset)(nil),                           // 9: mediaservice.media.v1.Asset
	(*ListMediaRequest)(nil),                // 10: mediaservice.media.v1.ListMediaRequest
	(*ListMediaResponse)(nil),               // 11: mediaservice.media.v1.ListMediaResponse
	(*GetMediaRequest)(nil),                 // 12: mediaservice.media.v1.GetMediaRequest
	(*GetMediaResponse)(nil),                // 13: mediaservice.media.v1.GetMediaResponse
	(*DeleteMediaRequest)(nil),              // 14: mediaservice.media.v1.DeleteMediaRequest
	(*DeleteMediaResponse)(nil),             // 15: mediaservice.media.v1.DeleteMediaResponse
	(*ListAssetsRequest)(nil),               // 16: mediaservice.media.v1.ListAssetsRequest
	(*ListAssetsResponse)(nil),              // 17: mediaservice.media.v1.ListAssetsResponse
	(*GetAssetRequest)(nil),                 // 18: mediaservice.media.v1.GetAssetRequest
	(*GetAssetResponse)(nil),                // 19: mediaservice.media.v1.GetAssetResponse
	(*CreateAssetsRequest)(nil),             // 20: mediaservice.media.v1.CreateAssetsRequest
	(*AssetRef)(nil),                        // 21: mediaservice.media.v1.AssetRef
	(*CreateAssetsResponse)(nil),            // 22: mediaservice.media.v1.CreateAssetsResponse
	(*RetryAssetRequest)(nil),               // 23: mediaservice.media.v1.RetryAssetRequest
	(*RetryAssetResponse)(nil),              // 24: mediaservice.media.v1.RetryAssetResponse
	(*InitPresignedUploadRequest)(nil),      // 25: mediaservice.media.v1.InitPresignedUploadRequest
	(*InitPresignedUploadResponse)(nil),     // 26: mediaservice.media.v1.InitPresignedUploadResponse
	(*RefreshPresignedUploadRequest)(nil),   // 27: mediaservice.media.v1.RefreshPresignedUploadRequest
	(*RefreshPresignedUploadResponse)(nil),  // 28: mediaservice.media.v1.RefreshPresignedUploadResponse
	(*CompletePresignedUploadRequest)(nil),  // 29: mediaservice.media.v1.CompletePresignedUploadRequest
	(*CompletePresignedUploadResponse)(nil), // 30: mediaservice.media.v1.CompletePresignedUploadResponse
	(*PresignAssetDownloadRequest)(nil),     // 31: mediaservice.media.v1.PresignAssetDownloadRequest
	(*PresignAssetDownloadResponse)(nil),    // 32: mediaservice.media.v1.PresignAssetDownloadResponse
	(*GetMediaRoleURLRequest)(nil),          // 33: mediaservice.media.v1.GetMediaRoleURLRequest
	(*GetMediaRoleURLResponse)(nil),         // 34: mediaservice.media.v1.GetMediaRoleURLResponse
	nil,                                     // 35: mediaservice.media.v1.InitPresignedUploadResponse.HeadersEntry
	nil,                                     // 36: mediaservice.media.v1.RefreshPresignedUploadResponse.HeadersEntry
	(v1.Origin)(0),                          // 37: mediaservice.common.v1.Origin
	(v1.MediaType)(0),                       // 38: mediaservice.common.v1.MediaType
	(*timestamppb.Timestamp)(nil),           // 39: google.protobuf.Timestamp
}
var file_mediaservice_media_v1_media_proto_depIdxs = []int32{
	37, // 0: mediaservice.media.v1.Media.origin:type_name -> mediaservice.common.v1.Origin
	38, // 1: mediaservice.media.v1.Media.media_type:type_name -> mediaservice.common.v1.MediaType
	0,  // 2: mediaservice.media.v1.Media.lifecycle:type_name -> mediaservice.media.v1.MediaLifecycle
	39, // 3: mediaservice.media.v1.Media.created_at:type_name -> google.protobuf.Timestamp
	39, // 4: mediaservice.media.v1.Media.updated_at:type_name -> google.protobuf.Timestamp
	39, // 5: mediaservice.media.v1.Media.deleted_at:type_name -> google.protobuf.Timestamp
	39, // 6: mediaservice.media.v1.Media.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 7: mediaservice.media.v1.Media.visibility:type_name -> mediaservice.media.v1.Visibility
	1,  // 8: mediaservice.media.v1.Asset.kind:type_name -> mediaservice.media.v1.AssetKind
	2,  // 9: mediaservice.media.v1.Asset.role:type_name -> mediaservice.media.v1.AssetRole
	3,  // 10: mediaservice.media.v1.Asset.operation:type_name -> mediaservice.media.v1.AssetOperation
	4,  // 11: mediaservice.media.v1.Asset.lifecycle:type_name -> mediaservice.media.v1.AssetLifecycle
	7,  // 12: mediaservice.media.v1.Asset.desired_spec:type_name -> mediaservice.media.v1.DesiredSpec
	6,  // 13: mediaservice.media.v1.Asset.provenance:type_name -> mediaservice.media.v1.Provenance
	39, // 14: mediaservice.media.v1.Asset.created_at:type_name -> google.protobuf.Timestamp
	39, // 15: mediaservice.media.v1.Asset.updated_at:type_name -> google.protobuf.Timestamp
	38, // 16: mediaservice.media.v1.ListMediaRequest.media_type:type_name -> mediaservice.common.v1.MediaType
	37, // 17: mediaservice.media.v1.ListMediaRequest.origin:type_name -> mediaservice.common.v1.Origin
	8,  // 18: mediaservice.media.v1.ListMediaResponse.items:type_name -> mediaservice.media.v1.Media
	8,  // 19: mediaservice.media.v1.GetMediaResponse.media:type_name -> mediaservice.media.v1.Media
	9,  // 20: mediaservice.media.v1.ListAssetsResponse.assets:type_name -> mediaservice.media.v1.Asset
	9,  // 21: mediaservice.media.v1.GetAssetResponse.asset:type_name -> mediaservice.media.v1.Asset
	3,  // 22: mediaservice.media.v1.CreateAssetsRequest.operations:type_name -> mediaservice.media.v1.AssetOperation
	3,  // 23: mediaservice.media.v1.AssetRef.operation:type_name -> mediaservice.media.v1.AssetOperation
	4,  // 24: mediaservice.media.v1.AssetRef.lifecycle:type_name -> mediaservice.media.v1.AssetLifecycle
	21, // 25: mediaservice.media.v1.CreateAssetsResponse.assets:type_name -> mediaservice.media.v1.AssetRef
	9,  // 26: mediaservice.media.v1.RetryAssetResponse.asset:type_name -> mediaservice.media.v1.Asset
	35, // 27: mediaservice.media.v1.InitPresignedUploadResponse.headers:type_name -> mediaservice.media.v1.InitPresignedUploadResponse.HeadersEntry
	39, // 28: mediaservice.media.v1.InitPresignedUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	36, // 29: mediaservice.media.v1.RefreshPresignedUploadResponse.headers:type_name -> mediaservice.media.v1.RefreshPresignedUploadResponse.HeadersEntry
	39, // 30: mediaservice.media.v1.RefreshPresignedUploadResponse.expires_at:type_name -> google.protobuf.Timestamp
	4,  // 31: mediaservice.media.v1.CompletePresignedUploadResponse.lifecycle:type_name -> mediaservice.media.v1.AssetLifecycle
	39, // 32: mediaservice.media.v1.PresignAssetDownloadResponse.expires_at:type_name -> google.protobuf.Timestamp
	2,  // 33: mediaservice.media.v1.GetMediaRoleURLRequest.role:type_name -> mediaservice.media.v1.AssetRole
	39, // 34: mediaservice.media.v1.GetMediaRoleURLResponse.expires_at:type_name -> google.protobuf.Timestamp
	10, // 35: mediaservice.media.v1.MediaService.ListMedia:input_type -> mediaservice.media.v1.ListMediaRequest
	12, // 36: mediaservice.media.v1.MediaService.GetMedia:input_type -> mediaservice.media.v1.GetMediaRequest
	14, // 37: mediaservice.media.v1.MediaService.DeleteMedia:input_type -> mediaservice.media.v1.DeleteMediaRequest
	16, // 38: mediaservice.media.v1.MediaService.ListAssets:input_type -> mediaservice.media.v1.ListAssetsRequest
	18, // 39: mediaservice.media.v1.MediaService.GetAsset:input_type -> mediaservice.media.v1.GetAssetRequest
	20, // 40: mediaservice.media.v1.MediaService.CreateAssets:input_type -> mediaservice.media.v1.CreateAssetsRequest
	23, // 41: mediaservice.media.v1.MediaService.RetryAsset:input_type -> mediaservice.media.v1.RetryAssetRequest
	25, // 42: mediaservice.media.v1.MediaService.InitPresignedUpload:input_type -> mediaservice.media.v1.InitPresignedUploadRequest
	27, // 43: mediaservice.media.v1.MediaService.RefreshPresignedUpload:input_type -> mediaservice.media.v1.RefreshPresignedUploadRequest
	29, // 44: mediaservice.media.v1.MediaService.CompletePresignedUpload:input_type -> mediaservice.media.v1.CompletePresignedUploadRequest
	31, // 45: mediaservice.media.v1.MediaService.PresignAssetDownload:input_type -> mediaservice.media.v1.PresignAssetDownloadRequest
	33, // 46: mediaservice.media.v1.MediaService.GetMediaRoleURL:input_type -> mediaservice.media.v1.GetMediaRoleURLRequest
	11, // 47: mediaservice.media.v1.MediaService.ListMedia:output_type -> mediaservice.media.v1.ListMediaResponse
	13, // 48: mediaservice.media.v1.MediaService.GetMedia:output_type -> mediaservice.media.v1.GetMediaResponse
	15, // 49: mediaservice.media.v1.MediaService.DeleteMedia:output_type -> mediaservice.media.v1.DeleteMediaResponse
	17, // 50: mediaservice.media.v1.MediaService.ListAssets:output_type -> mediaservice.media.v1.ListAssetsResponse
	19, // 51: mediaservice.media.v1.MediaService.GetAsset:output_type -> mediaservice.media.v1.GetAssetResponse
	22, // 52: mediaservice.media.v1.MediaService.CreateAssets:output_type -> mediaservice.media.v1.CreateAssetsResponse
	24, // 53: mediaservice.media.v1.MediaService.RetryAsset:output_type -> mediaservice.media.v1.RetryAssetResponse
	26, // 54: mediaservice.media.v1.MediaService.InitPresignedUpload:output_type -> mediaservice.media.v1.InitPresignedUploadResponse
	28, // 55: mediaservice.media.v1.MediaService.RefreshPresignedUpload:output_type -> mediaservice.media.v1.RefreshPresignedUploadResponse
	30, // 56: mediaservice.media.v1.MediaService.CompletePresignedUpload:output_type -> mediaservice.media.v1.CompletePresignedUploadResponse
	32, // 57: mediaservice.media.v1.MediaService.PresignAssetDownload:output_type -> mediaservice.media.v1.PresignAssetDownloadResponse
	34, // 58: mediaservice.media.v1.MediaService.GetMediaRoleURL:output_type -> mediaservice.media.v1.GetMediaRoleURLResponse
	47, // [47:59] is the sub-list for method output_type
	35, // [35:47] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_mediaservice_media_v1_media_proto_init() }
func file_mediaservice_media_v1_media_proto_init() {
	if File_mediaservice_media_v1_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mediaservice_media_v1_media_proto_rawDesc), len(file_mediaservice_media_v1_media_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaservice_media_v1_media_proto_goTypes,
		DependencyIndexes: file_mediaservice_media_v1_media_proto_depIdxs,
		EnumInfos:         file_mediaservice_media_v1_media_proto_enumTypes,
		MessageInfos:      file_mediaservice_media_v1_media_proto_msgTypes,
	}.Build()
	File_mediaservice_media_v1_media_proto = out.File
	file_mediaservice_media_v1_media_proto_goTypes = nil
	file_mediaservice_media_v1_media_proto_depIdxs = nil
}
