// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mediaservice/generation/v1/generation.proto

package generationv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/generation/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GenerationServiceName is the fully-qualified name of the GenerationService service.
	GenerationServiceName = "mediaservice.generation.v1.GenerationService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GenerationServiceCreateGenerationProcedure is the fully-qualified name of the GenerationService's
	// CreateGeneration RPC.
	GenerationServiceCreateGenerationProcedure = "/mediaservice.generation.v1.GenerationService/CreateGeneration"
	// GenerationServiceCreateAudioOverviewProcedure is the fully-qualified name of the
	// GenerationService's CreateAudioOverview RPC.
	GenerationServiceCreateAudioOverviewProcedure = "/mediaservice.generation.v1.GenerationService/CreateAudioOverview"
	// GenerationServiceGetGenerationProcedure is the fully-qualified name of the GenerationService's
	// GetGeneration RPC.
	GenerationServiceGetGenerationProcedure = "/mediaservice.generation.v1.GenerationService/GetGeneration"
	// GenerationServiceGetGenerationResultProcedure is the fully-qualified name of the
	// GenerationService's GetGenerationResult RPC.
	GenerationServiceGetGenerationResultProcedure = "/mediaservice.generation.v1.GenerationService/GetGenerationResult"
)

// GenerationServiceClient is a client for the mediaservice.generation.v1.GenerationService service.
type GenerationServiceClient interface {
	CreateGeneration(context.Context, *connect.Request[v1.CreateGenerationRequest]) (*connect.Response[v1.CreateGenerationResponse], error)
	CreateAudioOverview(context.Context, *connect.Request[v1.CreateAudioOverviewRequest]) (*connect.Response[v1.CreateAudioOverviewResponse], error)
	GetGeneration(context.Context, *connect.Request[v1.GetGenerationRequest]) (*connect.Response[v1.GetGenerationResponse], error)
	GetGenerationResult(context.Context, *connect.Request[v1.GetGenerationResultRequest]) (*connect.Response[v1.GetGenerationResultResponse], error)
}

// NewGenerationServiceClient constructs a client for the
// mediaservice.generation.v1.GenerationService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGenerationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GenerationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	generationServiceMethods := v1.File_mediaservice_generation_v1_generation_proto.Services().ByName("GenerationService").Methods()
	return &generationServiceClient{
		createGeneration: connect.NewClient[v1.CreateGenerationRequest, v1.CreateGenerationResponse](
			httpClient,
			baseURL+GenerationServiceCreateGenerationProcedure,
			connect.WithSchema(generationServiceMethods.ByName("CreateGeneration")),
			connect.WithClientOptions(opts...),
		),
		createAudioOverview: connect.NewClient[v1.CreateAudioOverviewRequest, v1.CreateAudioOverviewResponse](
			httpClient,
			baseURL+GenerationServiceCreateAudioOverviewProcedure,
			connect.WithSchema(generationServiceMethods.ByName("CreateAudioOverview")),
			connect.WithClientOptions(opts...),
		),
		getGeneration: connect.NewClient[v1.GetGenerationRequest, v1.GetGenerationResponse](
			httpClient,
			baseURL+GenerationServiceGetGenerationProcedure,
			connect.WithSchema(generationServiceMethods.ByName("GetGeneration")),
			connect.WithClientOptions(opts...),
		),
		getGenerationResult: connect.NewClient[v1.GetGenerationResultRequest, v1.GetGenerationResultResponse](
			httpClient,
			baseURL+GenerationServiceGetGenerationResultProcedure,
			connect.WithSchema(generationServiceMethods.ByName("GetGenerationResult")),
			connect.WithClientOptions(opts...),
		),
	}
}

// generationServiceClient implements GenerationServiceClient.
type generationServiceClient struct {
	createGeneration    *connect.Client[v1.CreateGenerationRequest, v1.CreateGenerationResponse]
	createAudioOverview *connect.Client[v1.CreateAudioOverviewRequest, v1.CreateAudioOverviewResponse]
	getGeneration       *connect.Client[v1.GetGenerationRequest, v1.GetGenerationResponse]
	getGenerationResult *connect.Client[v1.GetGenerationResultRequest, v1.GetGenerationResultResponse]
}

// CreateGeneration calls mediaservice.generation.v1.GenerationService.CreateGeneration.
func (c *generationServiceClient) CreateGeneration(ctx context.Context, req *connect.Request[v1.CreateGenerationRequest]) (*connect.Response[v1.CreateGenerationResponse], error) {
	return c.createGeneration.CallUnary(ctx, req)
}

// CreateAudioOverview calls mediaservice.generation.v1.GenerationService.CreateAudioOverview.
func (c *generationServiceClient) CreateAudioOverview(ctx context.Context, req *connect.Request[v1.CreateAudioOverviewRequest]) (*connect.Response[v1.CreateAudioOverviewResponse], error) {
	return c.createAudioOverview.CallUnary(ctx, req)
}

// GetGeneration calls mediaservice.generation.v1.GenerationService.GetGeneration.
func (c *generationServiceClient) GetGeneration(ctx context.Context, req *connect.Request[v1.GetGenerationRequest]) (*connect.Response[v1.GetGenerationResponse], error) {
	return c.getGeneration.CallUnary(ctx, req)
}

// GetGenerationResult calls mediaservice.generation.v1.GenerationService.GetGenerationResult.
func (c *generationServiceClient) GetGenerationResult(ctx context.Context, req *connect.Request[v1.GetGenerationResultRequest]) (*connect.Response[v1.GetGenerationResultResponse], error) {
	return c.getGenerationResult.CallUnary(ctx, req)
}

// GenerationServiceHandler is an implementation of the mediaservice.generation.v1.GenerationService
// service.
type GenerationServiceHandler interface {
	CreateGeneration(context.Context, *connect.Request[v1.CreateGenerationRequest]) (*connect.Response[v1.CreateGenerationResponse], error)
	CreateAudioOverview(context.Context, *connect.Request[v1.CreateAudioOverviewRequest]) (*connect.Response[v1.CreateAudioOverviewResponse], error)
	GetGeneration(context.Context, *connect.Request[v1.GetGenerationRequest]) (*connect.Response[v1.GetGenerationResponse], error)
	GetGenerationResult(context.Context, *connect.Request[v1.GetGenerationResultRequest]) (*connect.Response[v1.GetGenerationResultResponse], error)
}

// NewGenerationServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGenerationServiceHandler(svc GenerationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	generationServiceMethods := v1.File_mediaservice_generation_v1_generation_proto.Services().ByName("GenerationService").Methods()
	generationServiceCreateGenerationHandler := connect.NewUnaryHandler(
		GenerationServiceCreateGenerationProcedure,
		svc.CreateGeneration,
		connect.WithSchema(generationServiceMethods.ByName("CreateGeneration")),
		connect.WithHandlerOptions(opts...),
	)
	generationServiceCreateAudioOverviewHandler := connect.NewUnaryHandler(
		GenerationServiceCreateAudioOverviewProcedure,
		svc.CreateAudioOverview,
		connect.WithSchema(generationServiceMethods.ByName("CreateAudioOverview")),
		connect.WithHandlerOptions(opts...),
	)
	generationServiceGetGenerationHandler := connect.NewUnaryHandler(
		GenerationServiceGetGenerationProcedure,
		svc.GetGeneration,
		connect.WithSchema(generationServiceMethods.ByName("GetGeneration")),
		connect.WithHandlerOptions(opts...),
	)
	generationServiceGetGenerationResultHandler := connect.NewUnaryHandler(
		GenerationServiceGetGenerationResultProcedure,
		svc.GetGenerationResult,
		connect.WithSchema(generationServiceMethods.ByName("GetGenerationResult")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mediaservice.generation.v1.GenerationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GenerationServiceCreateGenerationProcedure:
			generationServiceCreateGenerationHandler.ServeHTTP(w, r)
		case GenerationServiceCreateAudioOverviewProcedure:
			generationServiceCreateAudioOverviewHandler.ServeHTTP(w, r)
		case GenerationServiceGetGenerationProcedure:
			generationServiceGetGenerationHandler.ServeHTTP(w, r)
		case GenerationServiceGetGenerationResultProcedure:
			generationServiceGetGenerationResultHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGenerationServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGenerationServiceHandler struct{}

func (UnimplementedGenerationServiceHandler) CreateGeneration(context.Context, *connect.Request[v1.CreateGenerationRequest]) (*connect.Response[v1.CreateGenerationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.generation.v1.GenerationService.CreateGeneration is not implemented"))
}

func (UnimplementedGenerationServiceHandler) CreateAudioOverview(context.Context, *connect.Request[v1.CreateAudioOverviewRequest]) (*connect.Response[v1.CreateAudioOverviewResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.generation.v1.GenerationService.CreateAudioOverview is not implemented"))
}

func (UnimplementedGenerationServiceHandler) GetGeneration(context.Context, *connect.Request[v1.GetGenerationRequest]) (*connect.Response[v1.GetGenerationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.generation.v1.GenerationService.GetGeneration is not implemented"))
}

func (UnimplementedGenerationServiceHandler) GetGenerationResult(context.Context, *connect.Request[v1.GetGenerationResultRequest]) (*connect.Response[v1.GetGenerationResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.generation.v1.GenerationService.GetGenerationResult is not implemented"))
}
