// Package bootstrap wires AWS clients, drivers, and app-layer repos. It is
// the single assembly root: every cmd binary calls Wire and consumes the
// assembled fields rather than constructing repos itself.
//
// Wire self-provisions local resources when no Terraform-managed topology is
// present. When Terraform injects resource ARNs/URLs through environment
// variables, those values are treated as authoritative and no resources are
// re-ensured.
package bootstrap

import (
	"cmp"
	"context"
	"fmt"
	"os"
	"time"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	"github.com/aws/aws-sdk-go-v2/service/kms"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sns"
	"github.com/aws/aws-sdk-go-v2/service/sqs"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"

	adminapp "github.com/dtszwai/media-processing-service/backend/internal/app/admin"
	analyticsapp "github.com/dtszwai/media-processing-service/backend/internal/app/analytics"
	auditapp "github.com/dtszwai/media-processing-service/backend/internal/app/audit"
	authapp "github.com/dtszwai/media-processing-service/backend/internal/app/auth"
	genapp "github.com/dtszwai/media-processing-service/backend/internal/app/generation"
	gendb "github.com/dtszwai/media-processing-service/backend/internal/app/generation/ddb"
	mediaapp "github.com/dtszwai/media-processing-service/backend/internal/app/media"
	quotaapp "github.com/dtszwai/media-processing-service/backend/internal/app/quota"
	safetyapp "github.com/dtszwai/media-processing-service/backend/internal/app/safety"
	shorturlapp "github.com/dtszwai/media-processing-service/backend/internal/app/shorturl"
	webhookapp "github.com/dtszwai/media-processing-service/backend/internal/app/webhook"
	"github.com/dtszwai/media-processing-service/backend/internal/conf/app"
	awscfg "github.com/dtszwai/media-processing-service/backend/internal/conf/aws"
	"github.com/dtszwai/media-processing-service/backend/internal/domain/quota"
	"github.com/dtszwai/media-processing-service/backend/internal/infra/eventbus"
	snsdrv "github.com/dtszwai/media-processing-service/backend/internal/infra/eventbus/sns"
	sqsdrv "github.com/dtszwai/media-processing-service/backend/internal/infra/eventbus/sqs"
	"github.com/dtszwai/media-processing-service/backend/internal/infra/kv"
	kvddb "github.com/dtszwai/media-processing-service/backend/internal/infra/kv/dynamodb"
	"github.com/dtszwai/media-processing-service/backend/internal/infra/obs"
	"github.com/dtszwai/media-processing-service/backend/internal/infra/postprocess"
	"github.com/dtszwai/media-processing-service/backend/internal/infra/sealer"
	kmsdrv "github.com/dtszwai/media-processing-service/backend/internal/infra/sealer/kms"
	"github.com/dtszwai/media-processing-service/backend/internal/infra/storage"
	s3drv "github.com/dtszwai/media-processing-service/backend/internal/infra/storage/s3"
)

// envTopology captures the values bootstrap reads from environment variables
// directly: Terraform-generated ARNs, the KMS prompt key id, and signing
// secrets. They stay out of app.Config because they are either generated by
// infra or sensitive — keeping them out of any checked-in YAML avoids the
// trap of secrets leaking into committed config.
type envTopology struct {
	mediaTopicARN           string
	mediaCleanupTopicARN    string
	generationTopicARN      string
	analyticsTopicARN       string
	mediaQueueURL           string
	mediaCleanupQueueURL    string
	mediaUploadEventsURL    string
	webhookQueueURL         string
	analyticsQueueURL       string
	generationQueueURLsJSON string
	webhookSecret           string
	dlqReplaySecret         string
	kmsPromptKeyID          string
}

// envBinding maps one environment variable to the envTopology field that holds
// its value. Required=true means the field is part of the managed-topology
// invariant: either all of them are set (Terraform-driven bring-up) or none of
// them are (self-provisioned bring-up). Partial managed topology is a hard
// error, not a "fix it with CreateTopic" situation.
type envBinding struct {
	Name     string
	Field    *string
	Required bool
}

func (e *envTopology) bindings() []envBinding {
	return []envBinding{
		{"SNS_MEDIA_TOPIC_ARN", &e.mediaTopicARN, true},
		{"SNS_MEDIA_CLEANUP_TOPIC_ARN", &e.mediaCleanupTopicARN, true},
		{"SNS_GENERATION_TOPIC_ARN", &e.generationTopicARN, true},
		{"SNS_ANALYTICS_TOPIC_ARN", &e.analyticsTopicARN, true},
		{"SQS_MEDIA_QUEUE_URL", &e.mediaQueueURL, true},
		{"SQS_MEDIA_CLEANUP_QUEUE_URL", &e.mediaCleanupQueueURL, true},
		{"SQS_MEDIA_UPLOAD_EVENTS_QUEUE_URL", &e.mediaUploadEventsURL, true},
		{"SQS_WEBHOOK_QUEUE_URL", &e.webhookQueueURL, true},
		{"SQS_ANALYTICS_QUEUE_URL", &e.analyticsQueueURL, true},
		{"SQS_GENERATION_QUEUE_URLS", &e.generationQueueURLsJSON, true},
		{"WEBHOOK_SECRET", &e.webhookSecret, false},
		{"DLQ_REPLAY_SECRET", &e.dlqReplaySecret, false},
		{"KMS_PROMPT_KEY_ID", &e.kmsPromptKeyID, false},
	}
}

func readEnvTopology() envTopology {
	var env envTopology
	for _, b := range env.bindings() {
		*b.Field = os.Getenv(b.Name)
	}
	env.webhookSecret = cmp.Or(env.webhookSecret, "local-dev-secret-change-me")
	env.dlqReplaySecret = cmp.Or(env.dlqReplaySecret, "local-dlq-secret-change-me")
	return env
}

// DLQInfo carries the URLs needed by admin/dlq operations.
type DLQInfo struct {
	Name      string
	URL       string
	SourceURL string
}

// AWS is the assembly output. Cmd code consumes ports + assembled repos;
// the raw SQS client is exposed only for queue polling in workers.
type AWS struct {
	SQS            *sqs.Client
	KMSPromptKeyID string
	Table          string
	Bucket         string

	// WebhookSecret is the HMAC signing key for outbound webhook deliveries.
	// Lives on the bootstrap output so cmd binaries don't replicate the env
	// read + default that Wire already performed.
	WebhookSecret []byte

	// Ports — app code consumes these.
	KV     kv.KV
	Blob   storage.Storage
	Sealer sealer.Sealer

	// Topic ARNs / queue URLs.
	MediaTopicARN             string
	MediaQueueURL             string
	MediaCleanupTopicARN      string
	MediaCleanupQueueURL      string
	MediaUploadEventsQueueURL string
	WebhookQueueURL           string
	GenerationTopicARN        string
	AnalyticsTopicARN         string
	AnalyticsQueueURL         string
	GenerationQueues          map[string]string
	DLQs                      map[string]DLQInfo

	// Pre-bound publishers (one per topic).
	MediaPub        eventbus.Publisher
	MediaCleanupPub eventbus.Publisher
	GenerationPub   eventbus.Publisher
	AnalyticsPub    eventbus.Publisher

	// App-layer repos.
	MediaRepo       *mediaapp.DDBRepo
	JobRepo         *gendb.JobRepo
	Idempotency     *gendb.Idempotency
	ArtifactSink    *gendb.ArtifactSink
	StagedArtifact  *gendb.Staging
	ImageStamper    *postprocess.Stamper
	ResourceLessor  *gendb.ResourceLessor
	LeaseRunner     *genapp.LeaseScopedRunner
	AuditRecorder   auditapp.Recorder
	AnalyticsReader *analyticsapp.DDBReader
	AnalyticsSink   *analyticsapp.Sink
	// AnalyticsTracker is the producer-side port injected into transport
	// handlers. Falls back to NoopTracker when no analytics topic is wired
	// (minimal local bring-up); production replaces it with the SNS-backed
	// implementation. Handlers must treat Track failures as non-fatal — see
	// the wrapping pattern at the handler call sites.
	AnalyticsTracker analyticsapp.Tracker
	Users            *authapp.DDBUsers
	APIKeys          *authapp.DDBAPIKeys
	ShortURL         *shorturlapp.Service
	DLQ              *adminapp.DLQAdmin
	OutboxDLQ        *adminapp.OutboxDLQAdmin
	IdempotencyAdmin *adminapp.IdempotencyAdmin
	QuotaAdmin       *adminapp.QuotaAdmin
	TenantAdmin      *adminapp.TenantAdmin
	WorkflowAdmin    *adminapp.WorkflowAdmin
	WebhookAdmin     *adminapp.WebhookAdmin
	WebhookSecrets   *webhookapp.SecretStore

	// QuotaAdapter satisfies both QuotaReserver and QuotaLedger and is
	// keyed today on (TENANT, COST_MICRO_USD, yyyyMMdd). The same Reservoir
	// primitive backs API-key cost, vendor cost, and request-count
	// reservoirs once their call sites land.
	QuotaAdapter *quotaapp.WorkflowAdapter
	QuotaMeter   *quotaapp.Meter

	// Moderator is the safety-port the INPUT_MODERATION and
	// OUTPUT_MODERATION stages call. Wired to a local SimulatedModerator
	// for now; replacing with a real provider impl only requires assigning
	// a different safetyapp.Moderator to this field.
	Moderator safetyapp.Moderator

	// Instruments is the process-wide OTEL counter / histogram / observable
	// gauge bundle the workflow, provider adapters, outbox relay, and
	// safety stages emit to. Constructed once at bootstrap so every
	// emitter shares the same Meter binding.
	Instruments *obs.Instruments
}

// Wire builds drivers and either self-provisions local infrastructure or binds
// to Terraform-injected infrastructure, depending on the environment.
func Wire(ctx context.Context, cfg app.Config) (*AWS, error) {
	env := readEnvTopology()

	awsCfg, err := awscfg.Load(ctx, awscfg.Options{
		Region:       cfg.AWS.Region,
		EndpointURL:  cfg.AWS.EndpointURL,
		AccessKey:    os.Getenv("AWS_ACCESS_KEY_ID"),
		SecretKey:    os.Getenv("AWS_SECRET_ACCESS_KEY"),
		SessionToken: os.Getenv("AWS_SESSION_TOKEN"),
	})
	if err != nil {
		return nil, fmt.Errorf("bootstrap: load aws config: %w", err)
	}

	ddbClient := dynamodb.NewFromConfig(awsCfg)
	s3Client := s3.NewFromConfig(awsCfg, func(o *s3.Options) { o.UsePathStyle = cfg.AWS.EndpointURL != "" })
	snsClient := sns.NewFromConfig(awsCfg)
	sqsClient := sqs.NewFromConfig(awsCfg)
	kmsClient := kms.NewFromConfig(awsCfg)

	kvDriver := kvddb.New(ddbClient, cfg.AWS.DDBTable)
	blob, err := s3drv.New(s3Client, cfg.AWS.S3Bucket, cfg.AWS.PublicEndpointURL)
	if err != nil {
		return nil, err
	}

	out := &AWS{
		SQS:                  sqsClient,
		KMSPromptKeyID:       env.kmsPromptKeyID,
		Table:                cfg.AWS.DDBTable,
		Bucket:               cfg.AWS.S3Bucket,
		WebhookSecret:        []byte(env.webhookSecret),
		KV:                   kvDriver,
		Blob:                 blob,
		MediaTopicARN:        env.mediaTopicARN,
		MediaCleanupTopicARN: env.mediaCleanupTopicARN,
		GenerationTopicARN:   env.generationTopicARN,
		AnalyticsTopicARN:    env.analyticsTopicARN,
		GenerationQueues:     map[string]string{},
		DLQs:                 map[string]DLQInfo{},
	}

	managedTopology, err := out.applyManagedTopology(env)
	if err != nil {
		return nil, err
	}
	if managedTopology {
		if out.KMSPromptKeyID == "" {
			return nil, fmt.Errorf("bootstrap: managed topology requires KMS_PROMPT_KEY_ID")
		}
	} else {
		if err := kvddb.EnsureMediaTable(ctx, ddbClient, cfg.AWS.DDBTable); err != nil {
			return nil, fmt.Errorf("bootstrap: ensure table: %w", err)
		}
		if err := blob.EnsureBucket(ctx); err != nil {
			return nil, fmt.Errorf("bootstrap: ensure bucket: %w", err)
		}
		if out.KMSPromptKeyID == "" {
			keyID, kerr := ensureLocalPromptKey(ctx, kmsClient)
			if kerr != nil {
				return nil, fmt.Errorf("bootstrap: ensure prompt kms key: %w", kerr)
			}
			out.KMSPromptKeyID = keyID
		}
		if err := out.ensureTopology(ctx, cfg.AWS, snsClient, sqsClient); err != nil {
			return nil, err
		}
	}

	out.Sealer = kmsdrv.New(kmsClient, out.KMSPromptKeyID)
	if out.MediaTopicARN != "" {
		out.MediaPub = snsdrv.New(snsClient, out.MediaTopicARN)
	}
	if out.MediaCleanupTopicARN != "" {
		out.MediaCleanupPub = snsdrv.New(snsClient, out.MediaCleanupTopicARN)
	}
	if out.GenerationTopicARN != "" {
		out.GenerationPub = snsdrv.New(snsClient, out.GenerationTopicARN)
	}
	if out.AnalyticsTopicARN != "" {
		out.AnalyticsPub = snsdrv.New(snsClient, out.AnalyticsTopicARN)
	}

	out.MediaRepo = mediaapp.NewDDBRepo(kvDriver)
	out.Idempotency = gendb.NewIdempotency(kvDriver)
	// AuditRecorder is the standalone audit subsystem. Constructed before
	// any consumer so per-feature writers (DLQAdmin, auth
	// Service) can fan their decisions through it on top of their own
	// per-job/per-message rows.
	out.AuditRecorder = auditapp.NewDDB(kvDriver)
	out.ArtifactSink = gendb.NewArtifactSink(kvDriver, blob)
	out.StagedArtifact = gendb.NewStaging(kvDriver, blob)
	// Visible watermark stamper for image artifacts. The label is
	// deliberately static — auditability of AI-disclosure relies on every
	// stamped image carrying the same readable text.
	stamper, serr := postprocess.NewStamper("AI Generated")
	if serr != nil {
		return nil, fmt.Errorf("bootstrap: image stamper: %w", serr)
	}
	out.ImageStamper = stamper
	// DDB-backed resource lessor for per-(provider × resource-class)
	// concurrency. The lease-reaper Lambda runs SweepExpired periodically
	// so a crashed worker's row gets reclaimed without operator action.
	out.ResourceLessor = gendb.NewResourceLessor(kvDriver)
	out.LeaseRunner = genapp.NewLeaseScopedRunner(out.ResourceLessor)
	out.JobRepo = gendb.NewJobRepo(kvDriver, out.Sealer)
	out.AnalyticsReader = analyticsapp.NewDDBReader(kvDriver)
	out.AnalyticsSink = analyticsapp.NewSink(kvDriver)
	// Producer-side tracker. Without an analytics topic the noop tracker is
	// the safe default — handlers continue to call Track and the call
	// returns nil instead of forcing every handler to nil-check.
	if pub := analyticsapp.NewBusPublisher(out.AnalyticsPub); pub != nil {
		out.AnalyticsTracker = analyticsapp.NewTracker(pub)
	} else {
		out.AnalyticsTracker = analyticsapp.NoopTracker{}
	}
	out.Users = authapp.NewDDBUsers(kvDriver)
	out.APIKeys = authapp.NewDDBAPIKeys(kvDriver)
	out.ShortURL = shorturlapp.NewService(kvDriver)
	out.WebhookSecrets = webhookapp.NewSecretStore(kvDriver, out.Sealer)

	// Outbox relays intentionally live in the standalone outbox-relay binary
	// (backend/cmd/workers/outbox-relay). Keeping them out of the API +
	// per-worker process means a single API outage can't stall MEDIA,
	// MEDIA_CLEANUP, or GEN stream draining.

	quotaRepo := quotaapp.NewRepo(kvDriver)
	out.QuotaAdapter = quotaapp.NewWorkflowAdapter(quotaRepo, cfg.Quota.TenantCostCapMicroUSD)
	out.QuotaMeter = quotaapp.NewMeter(quotaRepo)
	out.JobRepo.QuotaLedger = out.QuotaAdapter
	// SimulatedModerator is the default in-process classifier — see the
	// app/safety package doc. Production replaces it with a remote
	// moderation provider; the wiring point is identical.
	out.Moderator = safetyapp.NewSimulatedModerator()

	// One Meter / one Instruments per process. The Meter is sourced from
	// the global MeterProvider that telemetry.Init wired, so when no OTLP
	// endpoint is configured this still resolves to the SDK's no-op meter.
	instruments, err := obs.NewInstruments(otel.GetMeterProvider().Meter(obs.MeterName))
	if err != nil {
		return nil, fmt.Errorf("bootstrap: instruments: %w", err)
	}
	out.Instruments = instruments
	// Service-global cost reservoir gauge. quota.used_pct dashboards expect
	// (cap - available) / cap × 100; the callback reads the row at scrape
	// time so the value reflects whatever the latest reserve / commit /
	// release wrote rather than a cached per-process snapshot.
	if err := registerQuotaUsedGauge(instruments, out.QuotaAdapter); err != nil {
		return nil, fmt.Errorf("bootstrap: register quota gauge: %w", err)
	}

	dlqTransport := sqsdrv.New(sqsClient, "")
	out.DLQ = adminapp.NewDLQAdmin(dlqTransport, out.Idempotency, out.AuditRecorder)
	out.OutboxDLQ = adminapp.NewOutboxDLQAdmin(kvDriver, out.AuditRecorder)
	out.IdempotencyAdmin = adminapp.NewIdempotencyAdmin(kvDriver, out.AuditRecorder)
	out.QuotaAdmin = adminapp.NewQuotaAdmin(quotaRepo, out.AuditRecorder)
	out.TenantAdmin = adminapp.NewTenantAdmin(kvDriver, out.AuditRecorder)
	out.WorkflowAdmin = adminapp.NewWorkflowAdmin(out.JobRepo, out.AuditRecorder)
	out.WebhookAdmin = adminapp.NewWebhookAdmin(out.WebhookSecrets, out.AuditRecorder)
	dlqTopology := map[string]adminapp.DLQInfo{}
	for name, info := range out.DLQs {
		dlqTopology[name] = adminapp.DLQInfo{Name: info.Name, URL: info.URL, SourceURL: info.SourceURL}
	}
	out.DLQ.SetTopology([]byte(env.dlqReplaySecret), dlqTopology)

	return out, nil
}

// registerQuotaUsedGauge wires a callback for quota.used_pct against the
// service-global cost reservoir. Per-tenant fan-out would require scanning all
// tenant reservoirs every scrape, so this reports only the service.global
// aggregate and leaves per-tenant gauges to a scheduled materialization job.
func registerQuotaUsedGauge(inst *obs.Instruments, adapter *quotaapp.WorkflowAdapter) error {
	if inst == nil || adapter == nil {
		return nil
	}
	repo := adapter.Repo()
	if repo == nil {
		return nil
	}
	meter := otel.GetMeterProvider().Meter(obs.MeterName)
	const scopeID = "service.global"
	_, err := meter.RegisterCallback(func(cbCtx context.Context, observer metric.Observer) error {
		// Absence of an Ensured row is silent (no observation) so an empty
		// installation doesn't emit a misleading 0% — the dashboard then
		// renders "no data" rather than a flat green line.
		period := quota.PeriodDaily(time.Now().UTC())
		r, getErr := repo.Get(cbCtx, quota.ScopeService, scopeID, quota.CostMicroUSD, period)
		if getErr != nil || r == nil || r.Cap <= 0 {
			return nil
		}
		usedPct := float64(r.Cap-r.Available) / float64(r.Cap) * 100.0
		observer.ObserveFloat64(inst.QuotaUsedPct, usedPct,
			metric.WithAttributes(
				attribute.String("metric", string(quota.CostMicroUSD)),
				attribute.String("scope_type", string(quota.ScopeService)),
				attribute.String("scope_hash", scopeID),
			),
		)
		return nil
	}, inst.QuotaUsedPct)
	return err
}
