// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mediaservice/ops/v1/ops.proto

// Package ops is the operator console's read + mutate surface. It is gated by
// LOCAL_ONLY=true on the API process; production deploys MUST NOT mount the
// OpsService handler. The surface is intentionally separate from the public
// API (auth/media/generation/admin) so the product surface is not polluted
// with infra-shaped types.
package opsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/ops/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OpsServiceName is the fully-qualified name of the OpsService service.
	OpsServiceName = "mediaservice.ops.v1.OpsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OpsServiceListJobsProcedure is the fully-qualified name of the OpsService's ListJobs RPC.
	OpsServiceListJobsProcedure = "/mediaservice.ops.v1.OpsService/ListJobs"
	// OpsServiceGetJobProcedure is the fully-qualified name of the OpsService's GetJob RPC.
	OpsServiceGetJobProcedure = "/mediaservice.ops.v1.OpsService/GetJob"
	// OpsServiceListMediaProcedure is the fully-qualified name of the OpsService's ListMedia RPC.
	OpsServiceListMediaProcedure = "/mediaservice.ops.v1.OpsService/ListMedia"
	// OpsServiceGetMediaProcedure is the fully-qualified name of the OpsService's GetMedia RPC.
	OpsServiceGetMediaProcedure = "/mediaservice.ops.v1.OpsService/GetMedia"
	// OpsServiceScanDdbProcedure is the fully-qualified name of the OpsService's ScanDdb RPC.
	OpsServiceScanDdbProcedure = "/mediaservice.ops.v1.OpsService/ScanDdb"
	// OpsServiceGetDdbRowProcedure is the fully-qualified name of the OpsService's GetDdbRow RPC.
	OpsServiceGetDdbRowProcedure = "/mediaservice.ops.v1.OpsService/GetDdbRow"
	// OpsServiceQueueDepthsProcedure is the fully-qualified name of the OpsService's QueueDepths RPC.
	OpsServiceQueueDepthsProcedure = "/mediaservice.ops.v1.OpsService/QueueDepths"
	// OpsServiceGetTenantUsageProcedure is the fully-qualified name of the OpsService's GetTenantUsage
	// RPC.
	OpsServiceGetTenantUsageProcedure = "/mediaservice.ops.v1.OpsService/GetTenantUsage"
	// OpsServiceListS3Procedure is the fully-qualified name of the OpsService's ListS3 RPC.
	OpsServiceListS3Procedure = "/mediaservice.ops.v1.OpsService/ListS3"
	// OpsServicePresignDownloadProcedure is the fully-qualified name of the OpsService's
	// PresignDownload RPC.
	OpsServicePresignDownloadProcedure = "/mediaservice.ops.v1.OpsService/PresignDownload"
	// OpsServiceStreamLogsProcedure is the fully-qualified name of the OpsService's StreamLogs RPC.
	OpsServiceStreamLogsProcedure = "/mediaservice.ops.v1.OpsService/StreamLogs"
	// OpsServiceCancelJobProcedure is the fully-qualified name of the OpsService's CancelJob RPC.
	OpsServiceCancelJobProcedure = "/mediaservice.ops.v1.OpsService/CancelJob"
	// OpsServiceRetryJobProcedure is the fully-qualified name of the OpsService's RetryJob RPC.
	OpsServiceRetryJobProcedure = "/mediaservice.ops.v1.OpsService/RetryJob"
	// OpsServiceForceFailJobProcedure is the fully-qualified name of the OpsService's ForceFailJob RPC.
	OpsServiceForceFailJobProcedure = "/mediaservice.ops.v1.OpsService/ForceFailJob"
	// OpsServiceReplayOutboxProcedure is the fully-qualified name of the OpsService's ReplayOutbox RPC.
	OpsServiceReplayOutboxProcedure = "/mediaservice.ops.v1.OpsService/ReplayOutbox"
	// OpsServicePurgeQueueProcedure is the fully-qualified name of the OpsService's PurgeQueue RPC.
	OpsServicePurgeQueueProcedure = "/mediaservice.ops.v1.OpsService/PurgeQueue"
	// OpsServiceRedriveDlqProcedure is the fully-qualified name of the OpsService's RedriveDlq RPC.
	OpsServiceRedriveDlqProcedure = "/mediaservice.ops.v1.OpsService/RedriveDlq"
	// OpsServicePutDdbAttrProcedure is the fully-qualified name of the OpsService's PutDdbAttr RPC.
	OpsServicePutDdbAttrProcedure = "/mediaservice.ops.v1.OpsService/PutDdbAttr"
	// OpsServiceDeleteDdbRowProcedure is the fully-qualified name of the OpsService's DeleteDdbRow RPC.
	OpsServiceDeleteDdbRowProcedure = "/mediaservice.ops.v1.OpsService/DeleteDdbRow"
	// OpsServiceDeleteS3ObjectProcedure is the fully-qualified name of the OpsService's DeleteS3Object
	// RPC.
	OpsServiceDeleteS3ObjectProcedure = "/mediaservice.ops.v1.OpsService/DeleteS3Object"
	// OpsServiceListGenerationModelsProcedure is the fully-qualified name of the OpsService's
	// ListGenerationModels RPC.
	OpsServiceListGenerationModelsProcedure = "/mediaservice.ops.v1.OpsService/ListGenerationModels"
	// OpsServiceGetLocalIdentityProcedure is the fully-qualified name of the OpsService's
	// GetLocalIdentity RPC.
	OpsServiceGetLocalIdentityProcedure = "/mediaservice.ops.v1.OpsService/GetLocalIdentity"
)

// OpsServiceClient is a client for the mediaservice.ops.v1.OpsService service.
type OpsServiceClient interface {
	// Reads — phase 1 & 2.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	GetJob(context.Context, *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.GetJobResponse], error)
	ListMedia(context.Context, *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error)
	GetMedia(context.Context, *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error)
	ScanDdb(context.Context, *connect.Request[v1.ScanDdbRequest]) (*connect.Response[v1.ScanDdbResponse], error)
	GetDdbRow(context.Context, *connect.Request[v1.GetDdbRowRequest]) (*connect.Response[v1.GetDdbRowResponse], error)
	QueueDepths(context.Context, *connect.Request[v1.QueueDepthsRequest]) (*connect.Response[v1.QueueDepthsResponse], error)
	GetTenantUsage(context.Context, *connect.Request[v1.GetTenantUsageRequest]) (*connect.Response[v1.GetTenantUsageResponse], error)
	ListS3(context.Context, *connect.Request[v1.ListS3Request]) (*connect.Response[v1.ListS3Response], error)
	PresignDownload(context.Context, *connect.Request[v1.PresignDownloadRequest]) (*connect.Response[v1.PresignDownloadResponse], error)
	StreamLogs(context.Context, *connect.Request[v1.StreamLogsRequest]) (*connect.ServerStreamForClient[v1.StreamLogsResponse], error)
	// Mutations — phase 3. Every successful mutation writes an AUDIT#OPS#...
	// row alongside the state change.
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
	RetryJob(context.Context, *connect.Request[v1.RetryJobRequest]) (*connect.Response[v1.RetryJobResponse], error)
	ForceFailJob(context.Context, *connect.Request[v1.ForceFailJobRequest]) (*connect.Response[v1.ForceFailJobResponse], error)
	ReplayOutbox(context.Context, *connect.Request[v1.ReplayOutboxRequest]) (*connect.Response[v1.ReplayOutboxResponse], error)
	PurgeQueue(context.Context, *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error)
	RedriveDlq(context.Context, *connect.Request[v1.RedriveDlqRequest]) (*connect.Response[v1.RedriveDlqResponse], error)
	PutDdbAttr(context.Context, *connect.Request[v1.PutDdbAttrRequest]) (*connect.Response[v1.PutDdbAttrResponse], error)
	DeleteDdbRow(context.Context, *connect.Request[v1.DeleteDdbRowRequest]) (*connect.Response[v1.DeleteDdbRowResponse], error)
	DeleteS3Object(context.Context, *connect.Request[v1.DeleteS3ObjectRequest]) (*connect.Response[v1.DeleteS3ObjectResponse], error)
	// Submit form metadata.
	ListGenerationModels(context.Context, *connect.Request[v1.ListGenerationModelsRequest]) (*connect.Response[v1.ListGenerationModelsResponse], error)
	// Local console identity (LOCAL_TENANT_ID / LOCAL_USER_ID).
	GetLocalIdentity(context.Context, *connect.Request[v1.GetLocalIdentityRequest]) (*connect.Response[v1.GetLocalIdentityResponse], error)
}

// NewOpsServiceClient constructs a client for the mediaservice.ops.v1.OpsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOpsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OpsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	opsServiceMethods := v1.File_mediaservice_ops_v1_ops_proto.Services().ByName("OpsService").Methods()
	return &opsServiceClient{
		listJobs: connect.NewClient[v1.ListJobsRequest, v1.ListJobsResponse](
			httpClient,
			baseURL+OpsServiceListJobsProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListJobs")),
			connect.WithClientOptions(opts...),
		),
		getJob: connect.NewClient[v1.GetJobRequest, v1.GetJobResponse](
			httpClient,
			baseURL+OpsServiceGetJobProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetJob")),
			connect.WithClientOptions(opts...),
		),
		listMedia: connect.NewClient[v1.ListMediaRequest, v1.ListMediaResponse](
			httpClient,
			baseURL+OpsServiceListMediaProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListMedia")),
			connect.WithClientOptions(opts...),
		),
		getMedia: connect.NewClient[v1.GetMediaRequest, v1.GetMediaResponse](
			httpClient,
			baseURL+OpsServiceGetMediaProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetMedia")),
			connect.WithClientOptions(opts...),
		),
		scanDdb: connect.NewClient[v1.ScanDdbRequest, v1.ScanDdbResponse](
			httpClient,
			baseURL+OpsServiceScanDdbProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ScanDdb")),
			connect.WithClientOptions(opts...),
		),
		getDdbRow: connect.NewClient[v1.GetDdbRowRequest, v1.GetDdbRowResponse](
			httpClient,
			baseURL+OpsServiceGetDdbRowProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetDdbRow")),
			connect.WithClientOptions(opts...),
		),
		queueDepths: connect.NewClient[v1.QueueDepthsRequest, v1.QueueDepthsResponse](
			httpClient,
			baseURL+OpsServiceQueueDepthsProcedure,
			connect.WithSchema(opsServiceMethods.ByName("QueueDepths")),
			connect.WithClientOptions(opts...),
		),
		getTenantUsage: connect.NewClient[v1.GetTenantUsageRequest, v1.GetTenantUsageResponse](
			httpClient,
			baseURL+OpsServiceGetTenantUsageProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetTenantUsage")),
			connect.WithClientOptions(opts...),
		),
		listS3: connect.NewClient[v1.ListS3Request, v1.ListS3Response](
			httpClient,
			baseURL+OpsServiceListS3Procedure,
			connect.WithSchema(opsServiceMethods.ByName("ListS3")),
			connect.WithClientOptions(opts...),
		),
		presignDownload: connect.NewClient[v1.PresignDownloadRequest, v1.PresignDownloadResponse](
			httpClient,
			baseURL+OpsServicePresignDownloadProcedure,
			connect.WithSchema(opsServiceMethods.ByName("PresignDownload")),
			connect.WithClientOptions(opts...),
		),
		streamLogs: connect.NewClient[v1.StreamLogsRequest, v1.StreamLogsResponse](
			httpClient,
			baseURL+OpsServiceStreamLogsProcedure,
			connect.WithSchema(opsServiceMethods.ByName("StreamLogs")),
			connect.WithClientOptions(opts...),
		),
		cancelJob: connect.NewClient[v1.CancelJobRequest, v1.CancelJobResponse](
			httpClient,
			baseURL+OpsServiceCancelJobProcedure,
			connect.WithSchema(opsServiceMethods.ByName("CancelJob")),
			connect.WithClientOptions(opts...),
		),
		retryJob: connect.NewClient[v1.RetryJobRequest, v1.RetryJobResponse](
			httpClient,
			baseURL+OpsServiceRetryJobProcedure,
			connect.WithSchema(opsServiceMethods.ByName("RetryJob")),
			connect.WithClientOptions(opts...),
		),
		forceFailJob: connect.NewClient[v1.ForceFailJobRequest, v1.ForceFailJobResponse](
			httpClient,
			baseURL+OpsServiceForceFailJobProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ForceFailJob")),
			connect.WithClientOptions(opts...),
		),
		replayOutbox: connect.NewClient[v1.ReplayOutboxRequest, v1.ReplayOutboxResponse](
			httpClient,
			baseURL+OpsServiceReplayOutboxProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ReplayOutbox")),
			connect.WithClientOptions(opts...),
		),
		purgeQueue: connect.NewClient[v1.PurgeQueueRequest, v1.PurgeQueueResponse](
			httpClient,
			baseURL+OpsServicePurgeQueueProcedure,
			connect.WithSchema(opsServiceMethods.ByName("PurgeQueue")),
			connect.WithClientOptions(opts...),
		),
		redriveDlq: connect.NewClient[v1.RedriveDlqRequest, v1.RedriveDlqResponse](
			httpClient,
			baseURL+OpsServiceRedriveDlqProcedure,
			connect.WithSchema(opsServiceMethods.ByName("RedriveDlq")),
			connect.WithClientOptions(opts...),
		),
		putDdbAttr: connect.NewClient[v1.PutDdbAttrRequest, v1.PutDdbAttrResponse](
			httpClient,
			baseURL+OpsServicePutDdbAttrProcedure,
			connect.WithSchema(opsServiceMethods.ByName("PutDdbAttr")),
			connect.WithClientOptions(opts...),
		),
		deleteDdbRow: connect.NewClient[v1.DeleteDdbRowRequest, v1.DeleteDdbRowResponse](
			httpClient,
			baseURL+OpsServiceDeleteDdbRowProcedure,
			connect.WithSchema(opsServiceMethods.ByName("DeleteDdbRow")),
			connect.WithClientOptions(opts...),
		),
		deleteS3Object: connect.NewClient[v1.DeleteS3ObjectRequest, v1.DeleteS3ObjectResponse](
			httpClient,
			baseURL+OpsServiceDeleteS3ObjectProcedure,
			connect.WithSchema(opsServiceMethods.ByName("DeleteS3Object")),
			connect.WithClientOptions(opts...),
		),
		listGenerationModels: connect.NewClient[v1.ListGenerationModelsRequest, v1.ListGenerationModelsResponse](
			httpClient,
			baseURL+OpsServiceListGenerationModelsProcedure,
			connect.WithSchema(opsServiceMethods.ByName("ListGenerationModels")),
			connect.WithClientOptions(opts...),
		),
		getLocalIdentity: connect.NewClient[v1.GetLocalIdentityRequest, v1.GetLocalIdentityResponse](
			httpClient,
			baseURL+OpsServiceGetLocalIdentityProcedure,
			connect.WithSchema(opsServiceMethods.ByName("GetLocalIdentity")),
			connect.WithClientOptions(opts...),
		),
	}
}

// opsServiceClient implements OpsServiceClient.
type opsServiceClient struct {
	listJobs             *connect.Client[v1.ListJobsRequest, v1.ListJobsResponse]
	getJob               *connect.Client[v1.GetJobRequest, v1.GetJobResponse]
	listMedia            *connect.Client[v1.ListMediaRequest, v1.ListMediaResponse]
	getMedia             *connect.Client[v1.GetMediaRequest, v1.GetMediaResponse]
	scanDdb              *connect.Client[v1.ScanDdbRequest, v1.ScanDdbResponse]
	getDdbRow            *connect.Client[v1.GetDdbRowRequest, v1.GetDdbRowResponse]
	queueDepths          *connect.Client[v1.QueueDepthsRequest, v1.QueueDepthsResponse]
	getTenantUsage       *connect.Client[v1.GetTenantUsageRequest, v1.GetTenantUsageResponse]
	listS3               *connect.Client[v1.ListS3Request, v1.ListS3Response]
	presignDownload      *connect.Client[v1.PresignDownloadRequest, v1.PresignDownloadResponse]
	streamLogs           *connect.Client[v1.StreamLogsRequest, v1.StreamLogsResponse]
	cancelJob            *connect.Client[v1.CancelJobRequest, v1.CancelJobResponse]
	retryJob             *connect.Client[v1.RetryJobRequest, v1.RetryJobResponse]
	forceFailJob         *connect.Client[v1.ForceFailJobRequest, v1.ForceFailJobResponse]
	replayOutbox         *connect.Client[v1.ReplayOutboxRequest, v1.ReplayOutboxResponse]
	purgeQueue           *connect.Client[v1.PurgeQueueRequest, v1.PurgeQueueResponse]
	redriveDlq           *connect.Client[v1.RedriveDlqRequest, v1.RedriveDlqResponse]
	putDdbAttr           *connect.Client[v1.PutDdbAttrRequest, v1.PutDdbAttrResponse]
	deleteDdbRow         *connect.Client[v1.DeleteDdbRowRequest, v1.DeleteDdbRowResponse]
	deleteS3Object       *connect.Client[v1.DeleteS3ObjectRequest, v1.DeleteS3ObjectResponse]
	listGenerationModels *connect.Client[v1.ListGenerationModelsRequest, v1.ListGenerationModelsResponse]
	getLocalIdentity     *connect.Client[v1.GetLocalIdentityRequest, v1.GetLocalIdentityResponse]
}

// ListJobs calls mediaservice.ops.v1.OpsService.ListJobs.
func (c *opsServiceClient) ListJobs(ctx context.Context, req *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return c.listJobs.CallUnary(ctx, req)
}

// GetJob calls mediaservice.ops.v1.OpsService.GetJob.
func (c *opsServiceClient) GetJob(ctx context.Context, req *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.GetJobResponse], error) {
	return c.getJob.CallUnary(ctx, req)
}

// ListMedia calls mediaservice.ops.v1.OpsService.ListMedia.
func (c *opsServiceClient) ListMedia(ctx context.Context, req *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error) {
	return c.listMedia.CallUnary(ctx, req)
}

// GetMedia calls mediaservice.ops.v1.OpsService.GetMedia.
func (c *opsServiceClient) GetMedia(ctx context.Context, req *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error) {
	return c.getMedia.CallUnary(ctx, req)
}

// ScanDdb calls mediaservice.ops.v1.OpsService.ScanDdb.
func (c *opsServiceClient) ScanDdb(ctx context.Context, req *connect.Request[v1.ScanDdbRequest]) (*connect.Response[v1.ScanDdbResponse], error) {
	return c.scanDdb.CallUnary(ctx, req)
}

// GetDdbRow calls mediaservice.ops.v1.OpsService.GetDdbRow.
func (c *opsServiceClient) GetDdbRow(ctx context.Context, req *connect.Request[v1.GetDdbRowRequest]) (*connect.Response[v1.GetDdbRowResponse], error) {
	return c.getDdbRow.CallUnary(ctx, req)
}

// QueueDepths calls mediaservice.ops.v1.OpsService.QueueDepths.
func (c *opsServiceClient) QueueDepths(ctx context.Context, req *connect.Request[v1.QueueDepthsRequest]) (*connect.Response[v1.QueueDepthsResponse], error) {
	return c.queueDepths.CallUnary(ctx, req)
}

// GetTenantUsage calls mediaservice.ops.v1.OpsService.GetTenantUsage.
func (c *opsServiceClient) GetTenantUsage(ctx context.Context, req *connect.Request[v1.GetTenantUsageRequest]) (*connect.Response[v1.GetTenantUsageResponse], error) {
	return c.getTenantUsage.CallUnary(ctx, req)
}

// ListS3 calls mediaservice.ops.v1.OpsService.ListS3.
func (c *opsServiceClient) ListS3(ctx context.Context, req *connect.Request[v1.ListS3Request]) (*connect.Response[v1.ListS3Response], error) {
	return c.listS3.CallUnary(ctx, req)
}

// PresignDownload calls mediaservice.ops.v1.OpsService.PresignDownload.
func (c *opsServiceClient) PresignDownload(ctx context.Context, req *connect.Request[v1.PresignDownloadRequest]) (*connect.Response[v1.PresignDownloadResponse], error) {
	return c.presignDownload.CallUnary(ctx, req)
}

// StreamLogs calls mediaservice.ops.v1.OpsService.StreamLogs.
func (c *opsServiceClient) StreamLogs(ctx context.Context, req *connect.Request[v1.StreamLogsRequest]) (*connect.ServerStreamForClient[v1.StreamLogsResponse], error) {
	return c.streamLogs.CallServerStream(ctx, req)
}

// CancelJob calls mediaservice.ops.v1.OpsService.CancelJob.
func (c *opsServiceClient) CancelJob(ctx context.Context, req *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return c.cancelJob.CallUnary(ctx, req)
}

// RetryJob calls mediaservice.ops.v1.OpsService.RetryJob.
func (c *opsServiceClient) RetryJob(ctx context.Context, req *connect.Request[v1.RetryJobRequest]) (*connect.Response[v1.RetryJobResponse], error) {
	return c.retryJob.CallUnary(ctx, req)
}

// ForceFailJob calls mediaservice.ops.v1.OpsService.ForceFailJob.
func (c *opsServiceClient) ForceFailJob(ctx context.Context, req *connect.Request[v1.ForceFailJobRequest]) (*connect.Response[v1.ForceFailJobResponse], error) {
	return c.forceFailJob.CallUnary(ctx, req)
}

// ReplayOutbox calls mediaservice.ops.v1.OpsService.ReplayOutbox.
func (c *opsServiceClient) ReplayOutbox(ctx context.Context, req *connect.Request[v1.ReplayOutboxRequest]) (*connect.Response[v1.ReplayOutboxResponse], error) {
	return c.replayOutbox.CallUnary(ctx, req)
}

// PurgeQueue calls mediaservice.ops.v1.OpsService.PurgeQueue.
func (c *opsServiceClient) PurgeQueue(ctx context.Context, req *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error) {
	return c.purgeQueue.CallUnary(ctx, req)
}

// RedriveDlq calls mediaservice.ops.v1.OpsService.RedriveDlq.
func (c *opsServiceClient) RedriveDlq(ctx context.Context, req *connect.Request[v1.RedriveDlqRequest]) (*connect.Response[v1.RedriveDlqResponse], error) {
	return c.redriveDlq.CallUnary(ctx, req)
}

// PutDdbAttr calls mediaservice.ops.v1.OpsService.PutDdbAttr.
func (c *opsServiceClient) PutDdbAttr(ctx context.Context, req *connect.Request[v1.PutDdbAttrRequest]) (*connect.Response[v1.PutDdbAttrResponse], error) {
	return c.putDdbAttr.CallUnary(ctx, req)
}

// DeleteDdbRow calls mediaservice.ops.v1.OpsService.DeleteDdbRow.
func (c *opsServiceClient) DeleteDdbRow(ctx context.Context, req *connect.Request[v1.DeleteDdbRowRequest]) (*connect.Response[v1.DeleteDdbRowResponse], error) {
	return c.deleteDdbRow.CallUnary(ctx, req)
}

// DeleteS3Object calls mediaservice.ops.v1.OpsService.DeleteS3Object.
func (c *opsServiceClient) DeleteS3Object(ctx context.Context, req *connect.Request[v1.DeleteS3ObjectRequest]) (*connect.Response[v1.DeleteS3ObjectResponse], error) {
	return c.deleteS3Object.CallUnary(ctx, req)
}

// ListGenerationModels calls mediaservice.ops.v1.OpsService.ListGenerationModels.
func (c *opsServiceClient) ListGenerationModels(ctx context.Context, req *connect.Request[v1.ListGenerationModelsRequest]) (*connect.Response[v1.ListGenerationModelsResponse], error) {
	return c.listGenerationModels.CallUnary(ctx, req)
}

// GetLocalIdentity calls mediaservice.ops.v1.OpsService.GetLocalIdentity.
func (c *opsServiceClient) GetLocalIdentity(ctx context.Context, req *connect.Request[v1.GetLocalIdentityRequest]) (*connect.Response[v1.GetLocalIdentityResponse], error) {
	return c.getLocalIdentity.CallUnary(ctx, req)
}

// OpsServiceHandler is an implementation of the mediaservice.ops.v1.OpsService service.
type OpsServiceHandler interface {
	// Reads — phase 1 & 2.
	ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error)
	GetJob(context.Context, *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.GetJobResponse], error)
	ListMedia(context.Context, *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error)
	GetMedia(context.Context, *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error)
	ScanDdb(context.Context, *connect.Request[v1.ScanDdbRequest]) (*connect.Response[v1.ScanDdbResponse], error)
	GetDdbRow(context.Context, *connect.Request[v1.GetDdbRowRequest]) (*connect.Response[v1.GetDdbRowResponse], error)
	QueueDepths(context.Context, *connect.Request[v1.QueueDepthsRequest]) (*connect.Response[v1.QueueDepthsResponse], error)
	GetTenantUsage(context.Context, *connect.Request[v1.GetTenantUsageRequest]) (*connect.Response[v1.GetTenantUsageResponse], error)
	ListS3(context.Context, *connect.Request[v1.ListS3Request]) (*connect.Response[v1.ListS3Response], error)
	PresignDownload(context.Context, *connect.Request[v1.PresignDownloadRequest]) (*connect.Response[v1.PresignDownloadResponse], error)
	StreamLogs(context.Context, *connect.Request[v1.StreamLogsRequest], *connect.ServerStream[v1.StreamLogsResponse]) error
	// Mutations — phase 3. Every successful mutation writes an AUDIT#OPS#...
	// row alongside the state change.
	CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error)
	RetryJob(context.Context, *connect.Request[v1.RetryJobRequest]) (*connect.Response[v1.RetryJobResponse], error)
	ForceFailJob(context.Context, *connect.Request[v1.ForceFailJobRequest]) (*connect.Response[v1.ForceFailJobResponse], error)
	ReplayOutbox(context.Context, *connect.Request[v1.ReplayOutboxRequest]) (*connect.Response[v1.ReplayOutboxResponse], error)
	PurgeQueue(context.Context, *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error)
	RedriveDlq(context.Context, *connect.Request[v1.RedriveDlqRequest]) (*connect.Response[v1.RedriveDlqResponse], error)
	PutDdbAttr(context.Context, *connect.Request[v1.PutDdbAttrRequest]) (*connect.Response[v1.PutDdbAttrResponse], error)
	DeleteDdbRow(context.Context, *connect.Request[v1.DeleteDdbRowRequest]) (*connect.Response[v1.DeleteDdbRowResponse], error)
	DeleteS3Object(context.Context, *connect.Request[v1.DeleteS3ObjectRequest]) (*connect.Response[v1.DeleteS3ObjectResponse], error)
	// Submit form metadata.
	ListGenerationModels(context.Context, *connect.Request[v1.ListGenerationModelsRequest]) (*connect.Response[v1.ListGenerationModelsResponse], error)
	// Local console identity (LOCAL_TENANT_ID / LOCAL_USER_ID).
	GetLocalIdentity(context.Context, *connect.Request[v1.GetLocalIdentityRequest]) (*connect.Response[v1.GetLocalIdentityResponse], error)
}

// NewOpsServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOpsServiceHandler(svc OpsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	opsServiceMethods := v1.File_mediaservice_ops_v1_ops_proto.Services().ByName("OpsService").Methods()
	opsServiceListJobsHandler := connect.NewUnaryHandler(
		OpsServiceListJobsProcedure,
		svc.ListJobs,
		connect.WithSchema(opsServiceMethods.ByName("ListJobs")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetJobHandler := connect.NewUnaryHandler(
		OpsServiceGetJobProcedure,
		svc.GetJob,
		connect.WithSchema(opsServiceMethods.ByName("GetJob")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListMediaHandler := connect.NewUnaryHandler(
		OpsServiceListMediaProcedure,
		svc.ListMedia,
		connect.WithSchema(opsServiceMethods.ByName("ListMedia")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetMediaHandler := connect.NewUnaryHandler(
		OpsServiceGetMediaProcedure,
		svc.GetMedia,
		connect.WithSchema(opsServiceMethods.ByName("GetMedia")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceScanDdbHandler := connect.NewUnaryHandler(
		OpsServiceScanDdbProcedure,
		svc.ScanDdb,
		connect.WithSchema(opsServiceMethods.ByName("ScanDdb")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetDdbRowHandler := connect.NewUnaryHandler(
		OpsServiceGetDdbRowProcedure,
		svc.GetDdbRow,
		connect.WithSchema(opsServiceMethods.ByName("GetDdbRow")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceQueueDepthsHandler := connect.NewUnaryHandler(
		OpsServiceQueueDepthsProcedure,
		svc.QueueDepths,
		connect.WithSchema(opsServiceMethods.ByName("QueueDepths")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetTenantUsageHandler := connect.NewUnaryHandler(
		OpsServiceGetTenantUsageProcedure,
		svc.GetTenantUsage,
		connect.WithSchema(opsServiceMethods.ByName("GetTenantUsage")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListS3Handler := connect.NewUnaryHandler(
		OpsServiceListS3Procedure,
		svc.ListS3,
		connect.WithSchema(opsServiceMethods.ByName("ListS3")),
		connect.WithHandlerOptions(opts...),
	)
	opsServicePresignDownloadHandler := connect.NewUnaryHandler(
		OpsServicePresignDownloadProcedure,
		svc.PresignDownload,
		connect.WithSchema(opsServiceMethods.ByName("PresignDownload")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceStreamLogsHandler := connect.NewServerStreamHandler(
		OpsServiceStreamLogsProcedure,
		svc.StreamLogs,
		connect.WithSchema(opsServiceMethods.ByName("StreamLogs")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceCancelJobHandler := connect.NewUnaryHandler(
		OpsServiceCancelJobProcedure,
		svc.CancelJob,
		connect.WithSchema(opsServiceMethods.ByName("CancelJob")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceRetryJobHandler := connect.NewUnaryHandler(
		OpsServiceRetryJobProcedure,
		svc.RetryJob,
		connect.WithSchema(opsServiceMethods.ByName("RetryJob")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceForceFailJobHandler := connect.NewUnaryHandler(
		OpsServiceForceFailJobProcedure,
		svc.ForceFailJob,
		connect.WithSchema(opsServiceMethods.ByName("ForceFailJob")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceReplayOutboxHandler := connect.NewUnaryHandler(
		OpsServiceReplayOutboxProcedure,
		svc.ReplayOutbox,
		connect.WithSchema(opsServiceMethods.ByName("ReplayOutbox")),
		connect.WithHandlerOptions(opts...),
	)
	opsServicePurgeQueueHandler := connect.NewUnaryHandler(
		OpsServicePurgeQueueProcedure,
		svc.PurgeQueue,
		connect.WithSchema(opsServiceMethods.ByName("PurgeQueue")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceRedriveDlqHandler := connect.NewUnaryHandler(
		OpsServiceRedriveDlqProcedure,
		svc.RedriveDlq,
		connect.WithSchema(opsServiceMethods.ByName("RedriveDlq")),
		connect.WithHandlerOptions(opts...),
	)
	opsServicePutDdbAttrHandler := connect.NewUnaryHandler(
		OpsServicePutDdbAttrProcedure,
		svc.PutDdbAttr,
		connect.WithSchema(opsServiceMethods.ByName("PutDdbAttr")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceDeleteDdbRowHandler := connect.NewUnaryHandler(
		OpsServiceDeleteDdbRowProcedure,
		svc.DeleteDdbRow,
		connect.WithSchema(opsServiceMethods.ByName("DeleteDdbRow")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceDeleteS3ObjectHandler := connect.NewUnaryHandler(
		OpsServiceDeleteS3ObjectProcedure,
		svc.DeleteS3Object,
		connect.WithSchema(opsServiceMethods.ByName("DeleteS3Object")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceListGenerationModelsHandler := connect.NewUnaryHandler(
		OpsServiceListGenerationModelsProcedure,
		svc.ListGenerationModels,
		connect.WithSchema(opsServiceMethods.ByName("ListGenerationModels")),
		connect.WithHandlerOptions(opts...),
	)
	opsServiceGetLocalIdentityHandler := connect.NewUnaryHandler(
		OpsServiceGetLocalIdentityProcedure,
		svc.GetLocalIdentity,
		connect.WithSchema(opsServiceMethods.ByName("GetLocalIdentity")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mediaservice.ops.v1.OpsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OpsServiceListJobsProcedure:
			opsServiceListJobsHandler.ServeHTTP(w, r)
		case OpsServiceGetJobProcedure:
			opsServiceGetJobHandler.ServeHTTP(w, r)
		case OpsServiceListMediaProcedure:
			opsServiceListMediaHandler.ServeHTTP(w, r)
		case OpsServiceGetMediaProcedure:
			opsServiceGetMediaHandler.ServeHTTP(w, r)
		case OpsServiceScanDdbProcedure:
			opsServiceScanDdbHandler.ServeHTTP(w, r)
		case OpsServiceGetDdbRowProcedure:
			opsServiceGetDdbRowHandler.ServeHTTP(w, r)
		case OpsServiceQueueDepthsProcedure:
			opsServiceQueueDepthsHandler.ServeHTTP(w, r)
		case OpsServiceGetTenantUsageProcedure:
			opsServiceGetTenantUsageHandler.ServeHTTP(w, r)
		case OpsServiceListS3Procedure:
			opsServiceListS3Handler.ServeHTTP(w, r)
		case OpsServicePresignDownloadProcedure:
			opsServicePresignDownloadHandler.ServeHTTP(w, r)
		case OpsServiceStreamLogsProcedure:
			opsServiceStreamLogsHandler.ServeHTTP(w, r)
		case OpsServiceCancelJobProcedure:
			opsServiceCancelJobHandler.ServeHTTP(w, r)
		case OpsServiceRetryJobProcedure:
			opsServiceRetryJobHandler.ServeHTTP(w, r)
		case OpsServiceForceFailJobProcedure:
			opsServiceForceFailJobHandler.ServeHTTP(w, r)
		case OpsServiceReplayOutboxProcedure:
			opsServiceReplayOutboxHandler.ServeHTTP(w, r)
		case OpsServicePurgeQueueProcedure:
			opsServicePurgeQueueHandler.ServeHTTP(w, r)
		case OpsServiceRedriveDlqProcedure:
			opsServiceRedriveDlqHandler.ServeHTTP(w, r)
		case OpsServicePutDdbAttrProcedure:
			opsServicePutDdbAttrHandler.ServeHTTP(w, r)
		case OpsServiceDeleteDdbRowProcedure:
			opsServiceDeleteDdbRowHandler.ServeHTTP(w, r)
		case OpsServiceDeleteS3ObjectProcedure:
			opsServiceDeleteS3ObjectHandler.ServeHTTP(w, r)
		case OpsServiceListGenerationModelsProcedure:
			opsServiceListGenerationModelsHandler.ServeHTTP(w, r)
		case OpsServiceGetLocalIdentityProcedure:
			opsServiceGetLocalIdentityHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOpsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOpsServiceHandler struct{}

func (UnimplementedOpsServiceHandler) ListJobs(context.Context, *connect.Request[v1.ListJobsRequest]) (*connect.Response[v1.ListJobsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ListJobs is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetJob(context.Context, *connect.Request[v1.GetJobRequest]) (*connect.Response[v1.GetJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.GetJob is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListMedia(context.Context, *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ListMedia is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetMedia(context.Context, *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.GetMedia is not implemented"))
}

func (UnimplementedOpsServiceHandler) ScanDdb(context.Context, *connect.Request[v1.ScanDdbRequest]) (*connect.Response[v1.ScanDdbResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ScanDdb is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetDdbRow(context.Context, *connect.Request[v1.GetDdbRowRequest]) (*connect.Response[v1.GetDdbRowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.GetDdbRow is not implemented"))
}

func (UnimplementedOpsServiceHandler) QueueDepths(context.Context, *connect.Request[v1.QueueDepthsRequest]) (*connect.Response[v1.QueueDepthsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.QueueDepths is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetTenantUsage(context.Context, *connect.Request[v1.GetTenantUsageRequest]) (*connect.Response[v1.GetTenantUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.GetTenantUsage is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListS3(context.Context, *connect.Request[v1.ListS3Request]) (*connect.Response[v1.ListS3Response], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ListS3 is not implemented"))
}

func (UnimplementedOpsServiceHandler) PresignDownload(context.Context, *connect.Request[v1.PresignDownloadRequest]) (*connect.Response[v1.PresignDownloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.PresignDownload is not implemented"))
}

func (UnimplementedOpsServiceHandler) StreamLogs(context.Context, *connect.Request[v1.StreamLogsRequest], *connect.ServerStream[v1.StreamLogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.StreamLogs is not implemented"))
}

func (UnimplementedOpsServiceHandler) CancelJob(context.Context, *connect.Request[v1.CancelJobRequest]) (*connect.Response[v1.CancelJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.CancelJob is not implemented"))
}

func (UnimplementedOpsServiceHandler) RetryJob(context.Context, *connect.Request[v1.RetryJobRequest]) (*connect.Response[v1.RetryJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.RetryJob is not implemented"))
}

func (UnimplementedOpsServiceHandler) ForceFailJob(context.Context, *connect.Request[v1.ForceFailJobRequest]) (*connect.Response[v1.ForceFailJobResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ForceFailJob is not implemented"))
}

func (UnimplementedOpsServiceHandler) ReplayOutbox(context.Context, *connect.Request[v1.ReplayOutboxRequest]) (*connect.Response[v1.ReplayOutboxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ReplayOutbox is not implemented"))
}

func (UnimplementedOpsServiceHandler) PurgeQueue(context.Context, *connect.Request[v1.PurgeQueueRequest]) (*connect.Response[v1.PurgeQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.PurgeQueue is not implemented"))
}

func (UnimplementedOpsServiceHandler) RedriveDlq(context.Context, *connect.Request[v1.RedriveDlqRequest]) (*connect.Response[v1.RedriveDlqResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.RedriveDlq is not implemented"))
}

func (UnimplementedOpsServiceHandler) PutDdbAttr(context.Context, *connect.Request[v1.PutDdbAttrRequest]) (*connect.Response[v1.PutDdbAttrResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.PutDdbAttr is not implemented"))
}

func (UnimplementedOpsServiceHandler) DeleteDdbRow(context.Context, *connect.Request[v1.DeleteDdbRowRequest]) (*connect.Response[v1.DeleteDdbRowResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.DeleteDdbRow is not implemented"))
}

func (UnimplementedOpsServiceHandler) DeleteS3Object(context.Context, *connect.Request[v1.DeleteS3ObjectRequest]) (*connect.Response[v1.DeleteS3ObjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.DeleteS3Object is not implemented"))
}

func (UnimplementedOpsServiceHandler) ListGenerationModels(context.Context, *connect.Request[v1.ListGenerationModelsRequest]) (*connect.Response[v1.ListGenerationModelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.ListGenerationModels is not implemented"))
}

func (UnimplementedOpsServiceHandler) GetLocalIdentity(context.Context, *connect.Request[v1.GetLocalIdentityRequest]) (*connect.Response[v1.GetLocalIdentityResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.ops.v1.OpsService.GetLocalIdentity is not implemented"))
}
