// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mediaservice/shorturl/v1/shorturl.proto

package shorturlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Optional fields use proto3 `optional` so protojson omits them when zero.
type ShortURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ShortUrl      *string                `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3,oneof" json:"short_url,omitempty"`
	MediaId       string                 `protobuf:"bytes,3,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	IsPublic      *bool                  `protobuf:"varint,5,opt,name=is_public,json=isPublic,proto3,oneof" json:"is_public,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"`
	CreatedBy     *string                `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3,oneof" json:"created_by,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=revoked_at,json=revokedAt,proto3,oneof" json:"revoked_at,omitempty"`
	Label         *string                `protobuf:"bytes,10,opt,name=label,proto3,oneof" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortURL) Reset() {
	*x = ShortURL{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortURL) ProtoMessage() {}

func (x *ShortURL) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortURL.ProtoReflect.Descriptor instead.
func (*ShortURL) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *ShortURL) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ShortURL) GetShortUrl() string {
	if x != nil && x.ShortUrl != nil {
		return *x.ShortUrl
	}
	return ""
}

func (x *ShortURL) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ShortURL) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *ShortURL) GetIsPublic() bool {
	if x != nil && x.IsPublic != nil {
		return *x.IsPublic
	}
	return false
}

func (x *ShortURL) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShortURL) GetCreatedBy() string {
	if x != nil && x.CreatedBy != nil {
		return *x.CreatedBy
	}
	return ""
}

func (x *ShortURL) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *ShortURL) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

func (x *ShortURL) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Alias         *string                `protobuf:"bytes,3,opt,name=alias,proto3,oneof" json:"alias,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	Label         *string                `protobuf:"bytes,5,opt,name=label,proto3,oneof" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *CreateRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *CreateRequest) GetAlias() string {
	if x != nil && x.Alias != nil {
		return *x.Alias
	}
	return ""
}

func (x *CreateRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateRequest) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *ShortURL              `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetUrl() *ShortURL {
	if x != nil {
		return x.Url
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*ShortURL            `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetUrls() []*ShortURL {
	if x != nil {
		return x.Urls
	}
	return nil
}

type RevokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{6}
}

var File_mediaservice_shorturl_v1_shorturl_proto protoreflect.FileDescriptor

const file_mediaservice_shorturl_v1_shorturl_proto_rawDesc = "" +
	"\n" +
	"'mediaservice/shorturl/v1/shorturl.proto\x12\x18mediaservice.shorturl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x03\n" +
	"\bShortURL\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12 \n" +
	"\tshort_url\x18\x02 \x01(\tH\x00R\bshortUrl\x88\x01\x01\x12\x19\n" +
	"\bmedia_id\x18\x03 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x04 \x01(\tR\aassetId\x12 \n" +
	"\tis_public\x18\x05 \x01(\bH\x01R\bisPublic\x88\x01\x01\x12>\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tcreatedAt\x88\x01\x01\x12\"\n" +
	"\n" +
	"created_by\x18\a \x01(\tH\x03R\tcreatedBy\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x04R\texpiresAt\x88\x01\x01\x12>\n" +
	"\n" +
	"revoked_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x05R\trevokedAt\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\n" +
	" \x01(\tH\x06R\x05label\x88\x01\x01B\f\n" +
	"\n" +
	"_short_urlB\f\n" +
	"\n" +
	"_is_publicB\r\n" +
	"\v_created_atB\r\n" +
	"\v_created_byB\r\n" +
	"\v_expires_atB\r\n" +
	"\v_revoked_atB\b\n" +
	"\x06_label\"\xde\x01\n" +
	"\rCreateRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x19\n" +
	"\x05alias\x18\x03 \x01(\tH\x00R\x05alias\x88\x01\x01\x12>\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\texpiresAt\x88\x01\x01\x12\x19\n" +
	"\x05label\x18\x05 \x01(\tH\x02R\x05label\x88\x01\x01B\b\n" +
	"\x06_aliasB\r\n" +
	"\v_expires_atB\b\n" +
	"\x06_label\"F\n" +
	"\x0eCreateResponse\x124\n" +
	"\x03url\x18\x01 \x01(\v2\".mediaservice.shorturl.v1.ShortURLR\x03url\">\n" +
	"\vListRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"F\n" +
	"\fListResponse\x126\n" +
	"\x04urls\x18\x01 \x03(\v2\".mediaservice.shorturl.v1.ShortURLR\x04urls\"#\n" +
	"\rRevokeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\x10\n" +
	"\x0eRevokeResponse2\xa2\x02\n" +
	"\x0fShortURLService\x12[\n" +
	"\x06Create\x12'.mediaservice.shorturl.v1.CreateRequest\x1a(.mediaservice.shorturl.v1.CreateResponse\x12U\n" +
	"\x04List\x12%.mediaservice.shorturl.v1.ListRequest\x1a&.mediaservice.shorturl.v1.ListResponse\x12[\n" +
	"\x06Revoke\x12'.mediaservice.shorturl.v1.RevokeRequest\x1a(.mediaservice.shorturl.v1.RevokeResponseB\x96\x02\n" +
	"\x1ccom.mediaservice.shorturl.v1B\rShorturlProtoP\x01Zegithub.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/shorturl/v1;shorturlv1\xa2\x02\x03MSX\xaa\x02\x18Mediaservice.Shorturl.V1\xca\x02\x18Mediaservice\\Shorturl\\V1\xe2\x02$Mediaservice\\Shorturl\\V1\\GPBMetadata\xea\x02\x1aMediaservice::Shorturl::V1b\x06proto3"

var (
	file_mediaservice_shorturl_v1_shorturl_proto_rawDescOnce sync.Once
	file_mediaservice_shorturl_v1_shorturl_proto_rawDescData []byte
)

func file_mediaservice_shorturl_v1_shorturl_proto_rawDescGZIP() []byte {
	file_mediaservice_shorturl_v1_shorturl_proto_rawDescOnce.Do(func() {
		file_mediaservice_shorturl_v1_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mediaservice_shorturl_v1_shorturl_proto_rawDesc), len(file_mediaservice_shorturl_v1_shorturl_proto_rawDesc)))
	})
	return file_mediaservice_shorturl_v1_shorturl_proto_rawDescData
}

var file_mediaservice_shorturl_v1_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_mediaservice_shorturl_v1_shorturl_proto_goTypes = []any{
	(*ShortURL)(nil),              // 0: mediaservice.shorturl.v1.ShortURL
	(*CreateRequest)(nil),         // 1: mediaservice.shorturl.v1.CreateRequest
	(*CreateResponse)(nil),        // 2: mediaservice.shorturl.v1.CreateResponse
	(*ListRequest)(nil),           // 3: mediaservice.shorturl.v1.ListRequest
	(*ListResponse)(nil),          // 4: mediaservice.shorturl.v1.ListResponse
	(*RevokeRequest)(nil),         // 5: mediaservice.shorturl.v1.RevokeRequest
	(*RevokeResponse)(nil),        // 6: mediaservice.shorturl.v1.RevokeResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_mediaservice_shorturl_v1_shorturl_proto_depIdxs = []int32{
	7, // 0: mediaservice.shorturl.v1.ShortURL.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: mediaservice.shorturl.v1.ShortURL.expires_at:type_name -> google.protobuf.Timestamp
	7, // 2: mediaservice.shorturl.v1.ShortURL.revoked_at:type_name -> google.protobuf.Timestamp
	7, // 3: mediaservice.shorturl.v1.CreateRequest.expires_at:type_name -> google.protobuf.Timestamp
	0, // 4: mediaservice.shorturl.v1.CreateResponse.url:type_name -> mediaservice.shorturl.v1.ShortURL
	0, // 5: mediaservice.shorturl.v1.ListResponse.urls:type_name -> mediaservice.shorturl.v1.ShortURL
	1, // 6: mediaservice.shorturl.v1.ShortURLService.Create:input_type -> mediaservice.shorturl.v1.CreateRequest
	3, // 7: mediaservice.shorturl.v1.ShortURLService.List:input_type -> mediaservice.shorturl.v1.ListRequest
	5, // 8: mediaservice.shorturl.v1.ShortURLService.Revoke:input_type -> mediaservice.shorturl.v1.RevokeRequest
	2, // 9: mediaservice.shorturl.v1.ShortURLService.Create:output_type -> mediaservice.shorturl.v1.CreateResponse
	4, // 10: mediaservice.shorturl.v1.ShortURLService.List:output_type -> mediaservice.shorturl.v1.ListResponse
	6, // 11: mediaservice.shorturl.v1.ShortURLService.Revoke:output_type -> mediaservice.shorturl.v1.RevokeResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_mediaservice_shorturl_v1_shorturl_proto_init() }
func file_mediaservice_shorturl_v1_shorturl_proto_init() {
	if File_mediaservice_shorturl_v1_shorturl_proto != nil {
		return
	}
	file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[0].OneofWrappers = []any{}
	file_mediaservice_shorturl_v1_shorturl_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mediaservice_shorturl_v1_shorturl_proto_rawDesc), len(file_mediaservice_shorturl_v1_shorturl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaservice_shorturl_v1_shorturl_proto_goTypes,
		DependencyIndexes: file_mediaservice_shorturl_v1_shorturl_proto_depIdxs,
		MessageInfos:      file_mediaservice_shorturl_v1_shorturl_proto_msgTypes,
	}.Build()
	File_mediaservice_shorturl_v1_shorturl_proto = out.File
	file_mediaservice_shorturl_v1_shorturl_proto_goTypes = nil
	file_mediaservice_shorturl_v1_shorturl_proto_depIdxs = nil
}
