// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mediaservice/auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "mediaservice.auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/mediaservice.auth.v1.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/mediaservice.auth.v1.AuthService/Login"
	// AuthServiceRefreshProcedure is the fully-qualified name of the AuthService's Refresh RPC.
	AuthServiceRefreshProcedure = "/mediaservice.auth.v1.AuthService/Refresh"
	// AuthServiceGetMeProcedure is the fully-qualified name of the AuthService's GetMe RPC.
	AuthServiceGetMeProcedure = "/mediaservice.auth.v1.AuthService/GetMe"
	// AuthServiceCreateAPIKeyProcedure is the fully-qualified name of the AuthService's CreateAPIKey
	// RPC.
	AuthServiceCreateAPIKeyProcedure = "/mediaservice.auth.v1.AuthService/CreateAPIKey"
	// AuthServiceListAPIKeysProcedure is the fully-qualified name of the AuthService's ListAPIKeys RPC.
	AuthServiceListAPIKeysProcedure = "/mediaservice.auth.v1.AuthService/ListAPIKeys"
	// AuthServiceDeleteAPIKeyProcedure is the fully-qualified name of the AuthService's DeleteAPIKey
	// RPC.
	AuthServiceDeleteAPIKeyProcedure = "/mediaservice.auth.v1.AuthService/DeleteAPIKey"
)

// AuthServiceClient is a client for the mediaservice.auth.v1.AuthService service.
type AuthServiceClient interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error)
	ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error)
	DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error)
}

// NewAuthServiceClient constructs a client for the mediaservice.auth.v1.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_mediaservice_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		refresh: connect.NewClient[v1.RefreshRequest, v1.RefreshResponse](
			httpClient,
			baseURL+AuthServiceRefreshProcedure,
			connect.WithSchema(authServiceMethods.ByName("Refresh")),
			connect.WithClientOptions(opts...),
		),
		getMe: connect.NewClient[v1.GetMeRequest, v1.GetMeResponse](
			httpClient,
			baseURL+AuthServiceGetMeProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetMe")),
			connect.WithClientOptions(opts...),
		),
		createAPIKey: connect.NewClient[v1.CreateAPIKeyRequest, v1.CreateAPIKeyResponse](
			httpClient,
			baseURL+AuthServiceCreateAPIKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateAPIKey")),
			connect.WithClientOptions(opts...),
		),
		listAPIKeys: connect.NewClient[v1.ListAPIKeysRequest, v1.ListAPIKeysResponse](
			httpClient,
			baseURL+AuthServiceListAPIKeysProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListAPIKeys")),
			connect.WithClientOptions(opts...),
		),
		deleteAPIKey: connect.NewClient[v1.DeleteAPIKeyRequest, v1.DeleteAPIKeyResponse](
			httpClient,
			baseURL+AuthServiceDeleteAPIKeyProcedure,
			connect.WithSchema(authServiceMethods.ByName("DeleteAPIKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register     *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	login        *connect.Client[v1.LoginRequest, v1.LoginResponse]
	refresh      *connect.Client[v1.RefreshRequest, v1.RefreshResponse]
	getMe        *connect.Client[v1.GetMeRequest, v1.GetMeResponse]
	createAPIKey *connect.Client[v1.CreateAPIKeyRequest, v1.CreateAPIKeyResponse]
	listAPIKeys  *connect.Client[v1.ListAPIKeysRequest, v1.ListAPIKeysResponse]
	deleteAPIKey *connect.Client[v1.DeleteAPIKeyRequest, v1.DeleteAPIKeyResponse]
}

// Register calls mediaservice.auth.v1.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls mediaservice.auth.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// Refresh calls mediaservice.auth.v1.AuthService.Refresh.
func (c *authServiceClient) Refresh(ctx context.Context, req *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error) {
	return c.refresh.CallUnary(ctx, req)
}

// GetMe calls mediaservice.auth.v1.AuthService.GetMe.
func (c *authServiceClient) GetMe(ctx context.Context, req *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return c.getMe.CallUnary(ctx, req)
}

// CreateAPIKey calls mediaservice.auth.v1.AuthService.CreateAPIKey.
func (c *authServiceClient) CreateAPIKey(ctx context.Context, req *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error) {
	return c.createAPIKey.CallUnary(ctx, req)
}

// ListAPIKeys calls mediaservice.auth.v1.AuthService.ListAPIKeys.
func (c *authServiceClient) ListAPIKeys(ctx context.Context, req *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error) {
	return c.listAPIKeys.CallUnary(ctx, req)
}

// DeleteAPIKey calls mediaservice.auth.v1.AuthService.DeleteAPIKey.
func (c *authServiceClient) DeleteAPIKey(ctx context.Context, req *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error) {
	return c.deleteAPIKey.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the mediaservice.auth.v1.AuthService service.
type AuthServiceHandler interface {
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error)
	GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error)
	CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error)
	ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error)
	DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_mediaservice_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRefreshHandler := connect.NewUnaryHandler(
		AuthServiceRefreshProcedure,
		svc.Refresh,
		connect.WithSchema(authServiceMethods.ByName("Refresh")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetMeHandler := connect.NewUnaryHandler(
		AuthServiceGetMeProcedure,
		svc.GetMe,
		connect.WithSchema(authServiceMethods.ByName("GetMe")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCreateAPIKeyHandler := connect.NewUnaryHandler(
		AuthServiceCreateAPIKeyProcedure,
		svc.CreateAPIKey,
		connect.WithSchema(authServiceMethods.ByName("CreateAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListAPIKeysHandler := connect.NewUnaryHandler(
		AuthServiceListAPIKeysProcedure,
		svc.ListAPIKeys,
		connect.WithSchema(authServiceMethods.ByName("ListAPIKeys")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceDeleteAPIKeyHandler := connect.NewUnaryHandler(
		AuthServiceDeleteAPIKeyProcedure,
		svc.DeleteAPIKey,
		connect.WithSchema(authServiceMethods.ByName("DeleteAPIKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mediaservice.auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceRefreshProcedure:
			authServiceRefreshHandler.ServeHTTP(w, r)
		case AuthServiceGetMeProcedure:
			authServiceGetMeHandler.ServeHTTP(w, r)
		case AuthServiceCreateAPIKeyProcedure:
			authServiceCreateAPIKeyHandler.ServeHTTP(w, r)
		case AuthServiceListAPIKeysProcedure:
			authServiceListAPIKeysHandler.ServeHTTP(w, r)
		case AuthServiceDeleteAPIKeyProcedure:
			authServiceDeleteAPIKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) Refresh(context.Context, *connect.Request[v1.RefreshRequest]) (*connect.Response[v1.RefreshResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.Refresh is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetMe(context.Context, *connect.Request[v1.GetMeRequest]) (*connect.Response[v1.GetMeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.GetMe is not implemented"))
}

func (UnimplementedAuthServiceHandler) CreateAPIKey(context.Context, *connect.Request[v1.CreateAPIKeyRequest]) (*connect.Response[v1.CreateAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.CreateAPIKey is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListAPIKeys(context.Context, *connect.Request[v1.ListAPIKeysRequest]) (*connect.Response[v1.ListAPIKeysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.ListAPIKeys is not implemented"))
}

func (UnimplementedAuthServiceHandler) DeleteAPIKey(context.Context, *connect.Request[v1.DeleteAPIKeyRequest]) (*connect.Response[v1.DeleteAPIKeyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.auth.v1.AuthService.DeleteAPIKey is not implemented"))
}
