{
 "title": "Media Service",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Media Service RESTFul API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count{job=\"media-service-api\"}[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "description": "Media Service REST API traces.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "filters": [
      {
       "id": "4d8ded8e",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "media-service-api" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Media Upload Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "media_upload_success_total{job=\"media-service-api\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Media Upload Failure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "media_upload_failure_total{job=\"media-service-api\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max by(le) (rate(http_server_request_duration_seconds_bucket{job=\"media-service-api\"}[$__rate_interval]))) * 1000",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le) (rate(http_server_request_duration_seconds_bucket{job=\"media-service-api\"}[$__rate_interval]))) * 1000",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.75, max by(le) (rate(http_server_request_duration_seconds_bucket{job=\"media-service-api\"}[$__rate_interval]))) * 1000",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.5, max by(le) (rate(http_server_request_duration_seconds_bucket{job=\"media-service-api\"}[$__rate_interval]))) * 1000",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "RESTFul API Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"media-service-api\"} |= ``"
    }
   ]
  },
  {
   "title": "Media Service Asynchronous Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Successful Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "round(increase(lambda_process_media_success_total{job=\"media-service-lambda\"}[$__rate_interval]))",
     "legendFormat": "Process Media"
    },
    {
     "expr": "round(increase(lambda_resize_media_success_total{job=\"media-service-lambda\"}[$__rate_interval]))",
     "legendFormat": "Resize Media"
    },
    {
     "expr": "round(increase(lambda_delete_media_success_total{job=\"media-service-lambda\"}[$__rate_interval]))",
     "legendFormat": "Delete Media"
    }
   ]
  },
  {
   "title": "Failed Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "round(increase(lambda_process_media_failure_total{job=\"media-service-lambda\"}[$__rate_interval]))",
     "legendFormat": "Process Media"
    },
    {
     "expr": "round(increase(lambda_resize_media_failure_total{job=\"media-service-lambda\"}[$__rate_interval]))",
     "legendFormat": "Resize Media"
    },
    {
     "expr": "round(increase(lambda_delete_media_failure_total{job=\"media-service-lambda\"}[$__rate_interval]))",
     "legendFormat": "Delete Media"
    }
   ]
  },
  {
   "title": "Manage Media Lambda Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "filters": [
      {
       "id": "4d8ded8e",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "media-service-lambda" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Manage Media Lambda Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"media-service-lambda\"} |= ``"
    }
   ]
  }
 ]
}