// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mediaservice/media/v1/media.proto

package mediav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/media/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MediaServiceName is the fully-qualified name of the MediaService service.
	MediaServiceName = "mediaservice.media.v1.MediaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MediaServiceListMediaProcedure is the fully-qualified name of the MediaService's ListMedia RPC.
	MediaServiceListMediaProcedure = "/mediaservice.media.v1.MediaService/ListMedia"
	// MediaServiceGetMediaProcedure is the fully-qualified name of the MediaService's GetMedia RPC.
	MediaServiceGetMediaProcedure = "/mediaservice.media.v1.MediaService/GetMedia"
	// MediaServiceDeleteMediaProcedure is the fully-qualified name of the MediaService's DeleteMedia
	// RPC.
	MediaServiceDeleteMediaProcedure = "/mediaservice.media.v1.MediaService/DeleteMedia"
	// MediaServiceListAssetsProcedure is the fully-qualified name of the MediaService's ListAssets RPC.
	MediaServiceListAssetsProcedure = "/mediaservice.media.v1.MediaService/ListAssets"
	// MediaServiceGetAssetProcedure is the fully-qualified name of the MediaService's GetAsset RPC.
	MediaServiceGetAssetProcedure = "/mediaservice.media.v1.MediaService/GetAsset"
	// MediaServiceCreateAssetsProcedure is the fully-qualified name of the MediaService's CreateAssets
	// RPC.
	MediaServiceCreateAssetsProcedure = "/mediaservice.media.v1.MediaService/CreateAssets"
	// MediaServiceRetryAssetProcedure is the fully-qualified name of the MediaService's RetryAsset RPC.
	MediaServiceRetryAssetProcedure = "/mediaservice.media.v1.MediaService/RetryAsset"
	// MediaServiceInitPresignedUploadProcedure is the fully-qualified name of the MediaService's
	// InitPresignedUpload RPC.
	MediaServiceInitPresignedUploadProcedure = "/mediaservice.media.v1.MediaService/InitPresignedUpload"
	// MediaServiceRefreshPresignedUploadProcedure is the fully-qualified name of the MediaService's
	// RefreshPresignedUpload RPC.
	MediaServiceRefreshPresignedUploadProcedure = "/mediaservice.media.v1.MediaService/RefreshPresignedUpload"
	// MediaServiceCompletePresignedUploadProcedure is the fully-qualified name of the MediaService's
	// CompletePresignedUpload RPC.
	MediaServiceCompletePresignedUploadProcedure = "/mediaservice.media.v1.MediaService/CompletePresignedUpload"
	// MediaServicePresignAssetDownloadProcedure is the fully-qualified name of the MediaService's
	// PresignAssetDownload RPC.
	MediaServicePresignAssetDownloadProcedure = "/mediaservice.media.v1.MediaService/PresignAssetDownload"
	// MediaServiceGetMediaRoleURLProcedure is the fully-qualified name of the MediaService's
	// GetMediaRoleURL RPC.
	MediaServiceGetMediaRoleURLProcedure = "/mediaservice.media.v1.MediaService/GetMediaRoleURL"
)

// MediaServiceClient is a client for the mediaservice.media.v1.MediaService service.
type MediaServiceClient interface {
	ListMedia(context.Context, *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error)
	GetMedia(context.Context, *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error)
	DeleteMedia(context.Context, *connect.Request[v1.DeleteMediaRequest]) (*connect.Response[v1.DeleteMediaResponse], error)
	ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error)
	GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error)
	CreateAssets(context.Context, *connect.Request[v1.CreateAssetsRequest]) (*connect.Response[v1.CreateAssetsResponse], error)
	RetryAsset(context.Context, *connect.Request[v1.RetryAssetRequest]) (*connect.Response[v1.RetryAssetResponse], error)
	InitPresignedUpload(context.Context, *connect.Request[v1.InitPresignedUploadRequest]) (*connect.Response[v1.InitPresignedUploadResponse], error)
	RefreshPresignedUpload(context.Context, *connect.Request[v1.RefreshPresignedUploadRequest]) (*connect.Response[v1.RefreshPresignedUploadResponse], error)
	CompletePresignedUpload(context.Context, *connect.Request[v1.CompletePresignedUploadRequest]) (*connect.Response[v1.CompletePresignedUploadResponse], error)
	PresignAssetDownload(context.Context, *connect.Request[v1.PresignAssetDownloadRequest]) (*connect.Response[v1.PresignAssetDownloadResponse], error)
	GetMediaRoleURL(context.Context, *connect.Request[v1.GetMediaRoleURLRequest]) (*connect.Response[v1.GetMediaRoleURLResponse], error)
}

// NewMediaServiceClient constructs a client for the mediaservice.media.v1.MediaService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMediaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MediaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	mediaServiceMethods := v1.File_mediaservice_media_v1_media_proto.Services().ByName("MediaService").Methods()
	return &mediaServiceClient{
		listMedia: connect.NewClient[v1.ListMediaRequest, v1.ListMediaResponse](
			httpClient,
			baseURL+MediaServiceListMediaProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("ListMedia")),
			connect.WithClientOptions(opts...),
		),
		getMedia: connect.NewClient[v1.GetMediaRequest, v1.GetMediaResponse](
			httpClient,
			baseURL+MediaServiceGetMediaProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("GetMedia")),
			connect.WithClientOptions(opts...),
		),
		deleteMedia: connect.NewClient[v1.DeleteMediaRequest, v1.DeleteMediaResponse](
			httpClient,
			baseURL+MediaServiceDeleteMediaProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("DeleteMedia")),
			connect.WithClientOptions(opts...),
		),
		listAssets: connect.NewClient[v1.ListAssetsRequest, v1.ListAssetsResponse](
			httpClient,
			baseURL+MediaServiceListAssetsProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("ListAssets")),
			connect.WithClientOptions(opts...),
		),
		getAsset: connect.NewClient[v1.GetAssetRequest, v1.GetAssetResponse](
			httpClient,
			baseURL+MediaServiceGetAssetProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("GetAsset")),
			connect.WithClientOptions(opts...),
		),
		createAssets: connect.NewClient[v1.CreateAssetsRequest, v1.CreateAssetsResponse](
			httpClient,
			baseURL+MediaServiceCreateAssetsProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("CreateAssets")),
			connect.WithClientOptions(opts...),
		),
		retryAsset: connect.NewClient[v1.RetryAssetRequest, v1.RetryAssetResponse](
			httpClient,
			baseURL+MediaServiceRetryAssetProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("RetryAsset")),
			connect.WithClientOptions(opts...),
		),
		initPresignedUpload: connect.NewClient[v1.InitPresignedUploadRequest, v1.InitPresignedUploadResponse](
			httpClient,
			baseURL+MediaServiceInitPresignedUploadProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("InitPresignedUpload")),
			connect.WithClientOptions(opts...),
		),
		refreshPresignedUpload: connect.NewClient[v1.RefreshPresignedUploadRequest, v1.RefreshPresignedUploadResponse](
			httpClient,
			baseURL+MediaServiceRefreshPresignedUploadProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("RefreshPresignedUpload")),
			connect.WithClientOptions(opts...),
		),
		completePresignedUpload: connect.NewClient[v1.CompletePresignedUploadRequest, v1.CompletePresignedUploadResponse](
			httpClient,
			baseURL+MediaServiceCompletePresignedUploadProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("CompletePresignedUpload")),
			connect.WithClientOptions(opts...),
		),
		presignAssetDownload: connect.NewClient[v1.PresignAssetDownloadRequest, v1.PresignAssetDownloadResponse](
			httpClient,
			baseURL+MediaServicePresignAssetDownloadProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("PresignAssetDownload")),
			connect.WithClientOptions(opts...),
		),
		getMediaRoleURL: connect.NewClient[v1.GetMediaRoleURLRequest, v1.GetMediaRoleURLResponse](
			httpClient,
			baseURL+MediaServiceGetMediaRoleURLProcedure,
			connect.WithSchema(mediaServiceMethods.ByName("GetMediaRoleURL")),
			connect.WithClientOptions(opts...),
		),
	}
}

// mediaServiceClient implements MediaServiceClient.
type mediaServiceClient struct {
	listMedia               *connect.Client[v1.ListMediaRequest, v1.ListMediaResponse]
	getMedia                *connect.Client[v1.GetMediaRequest, v1.GetMediaResponse]
	deleteMedia             *connect.Client[v1.DeleteMediaRequest, v1.DeleteMediaResponse]
	listAssets              *connect.Client[v1.ListAssetsRequest, v1.ListAssetsResponse]
	getAsset                *connect.Client[v1.GetAssetRequest, v1.GetAssetResponse]
	createAssets            *connect.Client[v1.CreateAssetsRequest, v1.CreateAssetsResponse]
	retryAsset              *connect.Client[v1.RetryAssetRequest, v1.RetryAssetResponse]
	initPresignedUpload     *connect.Client[v1.InitPresignedUploadRequest, v1.InitPresignedUploadResponse]
	refreshPresignedUpload  *connect.Client[v1.RefreshPresignedUploadRequest, v1.RefreshPresignedUploadResponse]
	completePresignedUpload *connect.Client[v1.CompletePresignedUploadRequest, v1.CompletePresignedUploadResponse]
	presignAssetDownload    *connect.Client[v1.PresignAssetDownloadRequest, v1.PresignAssetDownloadResponse]
	getMediaRoleURL         *connect.Client[v1.GetMediaRoleURLRequest, v1.GetMediaRoleURLResponse]
}

// ListMedia calls mediaservice.media.v1.MediaService.ListMedia.
func (c *mediaServiceClient) ListMedia(ctx context.Context, req *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error) {
	return c.listMedia.CallUnary(ctx, req)
}

// GetMedia calls mediaservice.media.v1.MediaService.GetMedia.
func (c *mediaServiceClient) GetMedia(ctx context.Context, req *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error) {
	return c.getMedia.CallUnary(ctx, req)
}

// DeleteMedia calls mediaservice.media.v1.MediaService.DeleteMedia.
func (c *mediaServiceClient) DeleteMedia(ctx context.Context, req *connect.Request[v1.DeleteMediaRequest]) (*connect.Response[v1.DeleteMediaResponse], error) {
	return c.deleteMedia.CallUnary(ctx, req)
}

// ListAssets calls mediaservice.media.v1.MediaService.ListAssets.
func (c *mediaServiceClient) ListAssets(ctx context.Context, req *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error) {
	return c.listAssets.CallUnary(ctx, req)
}

// GetAsset calls mediaservice.media.v1.MediaService.GetAsset.
func (c *mediaServiceClient) GetAsset(ctx context.Context, req *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error) {
	return c.getAsset.CallUnary(ctx, req)
}

// CreateAssets calls mediaservice.media.v1.MediaService.CreateAssets.
func (c *mediaServiceClient) CreateAssets(ctx context.Context, req *connect.Request[v1.CreateAssetsRequest]) (*connect.Response[v1.CreateAssetsResponse], error) {
	return c.createAssets.CallUnary(ctx, req)
}

// RetryAsset calls mediaservice.media.v1.MediaService.RetryAsset.
func (c *mediaServiceClient) RetryAsset(ctx context.Context, req *connect.Request[v1.RetryAssetRequest]) (*connect.Response[v1.RetryAssetResponse], error) {
	return c.retryAsset.CallUnary(ctx, req)
}

// InitPresignedUpload calls mediaservice.media.v1.MediaService.InitPresignedUpload.
func (c *mediaServiceClient) InitPresignedUpload(ctx context.Context, req *connect.Request[v1.InitPresignedUploadRequest]) (*connect.Response[v1.InitPresignedUploadResponse], error) {
	return c.initPresignedUpload.CallUnary(ctx, req)
}

// RefreshPresignedUpload calls mediaservice.media.v1.MediaService.RefreshPresignedUpload.
func (c *mediaServiceClient) RefreshPresignedUpload(ctx context.Context, req *connect.Request[v1.RefreshPresignedUploadRequest]) (*connect.Response[v1.RefreshPresignedUploadResponse], error) {
	return c.refreshPresignedUpload.CallUnary(ctx, req)
}

// CompletePresignedUpload calls mediaservice.media.v1.MediaService.CompletePresignedUpload.
func (c *mediaServiceClient) CompletePresignedUpload(ctx context.Context, req *connect.Request[v1.CompletePresignedUploadRequest]) (*connect.Response[v1.CompletePresignedUploadResponse], error) {
	return c.completePresignedUpload.CallUnary(ctx, req)
}

// PresignAssetDownload calls mediaservice.media.v1.MediaService.PresignAssetDownload.
func (c *mediaServiceClient) PresignAssetDownload(ctx context.Context, req *connect.Request[v1.PresignAssetDownloadRequest]) (*connect.Response[v1.PresignAssetDownloadResponse], error) {
	return c.presignAssetDownload.CallUnary(ctx, req)
}

// GetMediaRoleURL calls mediaservice.media.v1.MediaService.GetMediaRoleURL.
func (c *mediaServiceClient) GetMediaRoleURL(ctx context.Context, req *connect.Request[v1.GetMediaRoleURLRequest]) (*connect.Response[v1.GetMediaRoleURLResponse], error) {
	return c.getMediaRoleURL.CallUnary(ctx, req)
}

// MediaServiceHandler is an implementation of the mediaservice.media.v1.MediaService service.
type MediaServiceHandler interface {
	ListMedia(context.Context, *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error)
	GetMedia(context.Context, *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error)
	DeleteMedia(context.Context, *connect.Request[v1.DeleteMediaRequest]) (*connect.Response[v1.DeleteMediaResponse], error)
	ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error)
	GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error)
	CreateAssets(context.Context, *connect.Request[v1.CreateAssetsRequest]) (*connect.Response[v1.CreateAssetsResponse], error)
	RetryAsset(context.Context, *connect.Request[v1.RetryAssetRequest]) (*connect.Response[v1.RetryAssetResponse], error)
	InitPresignedUpload(context.Context, *connect.Request[v1.InitPresignedUploadRequest]) (*connect.Response[v1.InitPresignedUploadResponse], error)
	RefreshPresignedUpload(context.Context, *connect.Request[v1.RefreshPresignedUploadRequest]) (*connect.Response[v1.RefreshPresignedUploadResponse], error)
	CompletePresignedUpload(context.Context, *connect.Request[v1.CompletePresignedUploadRequest]) (*connect.Response[v1.CompletePresignedUploadResponse], error)
	PresignAssetDownload(context.Context, *connect.Request[v1.PresignAssetDownloadRequest]) (*connect.Response[v1.PresignAssetDownloadResponse], error)
	GetMediaRoleURL(context.Context, *connect.Request[v1.GetMediaRoleURLRequest]) (*connect.Response[v1.GetMediaRoleURLResponse], error)
}

// NewMediaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMediaServiceHandler(svc MediaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	mediaServiceMethods := v1.File_mediaservice_media_v1_media_proto.Services().ByName("MediaService").Methods()
	mediaServiceListMediaHandler := connect.NewUnaryHandler(
		MediaServiceListMediaProcedure,
		svc.ListMedia,
		connect.WithSchema(mediaServiceMethods.ByName("ListMedia")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceGetMediaHandler := connect.NewUnaryHandler(
		MediaServiceGetMediaProcedure,
		svc.GetMedia,
		connect.WithSchema(mediaServiceMethods.ByName("GetMedia")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceDeleteMediaHandler := connect.NewUnaryHandler(
		MediaServiceDeleteMediaProcedure,
		svc.DeleteMedia,
		connect.WithSchema(mediaServiceMethods.ByName("DeleteMedia")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceListAssetsHandler := connect.NewUnaryHandler(
		MediaServiceListAssetsProcedure,
		svc.ListAssets,
		connect.WithSchema(mediaServiceMethods.ByName("ListAssets")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceGetAssetHandler := connect.NewUnaryHandler(
		MediaServiceGetAssetProcedure,
		svc.GetAsset,
		connect.WithSchema(mediaServiceMethods.ByName("GetAsset")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceCreateAssetsHandler := connect.NewUnaryHandler(
		MediaServiceCreateAssetsProcedure,
		svc.CreateAssets,
		connect.WithSchema(mediaServiceMethods.ByName("CreateAssets")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceRetryAssetHandler := connect.NewUnaryHandler(
		MediaServiceRetryAssetProcedure,
		svc.RetryAsset,
		connect.WithSchema(mediaServiceMethods.ByName("RetryAsset")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceInitPresignedUploadHandler := connect.NewUnaryHandler(
		MediaServiceInitPresignedUploadProcedure,
		svc.InitPresignedUpload,
		connect.WithSchema(mediaServiceMethods.ByName("InitPresignedUpload")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceRefreshPresignedUploadHandler := connect.NewUnaryHandler(
		MediaServiceRefreshPresignedUploadProcedure,
		svc.RefreshPresignedUpload,
		connect.WithSchema(mediaServiceMethods.ByName("RefreshPresignedUpload")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceCompletePresignedUploadHandler := connect.NewUnaryHandler(
		MediaServiceCompletePresignedUploadProcedure,
		svc.CompletePresignedUpload,
		connect.WithSchema(mediaServiceMethods.ByName("CompletePresignedUpload")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServicePresignAssetDownloadHandler := connect.NewUnaryHandler(
		MediaServicePresignAssetDownloadProcedure,
		svc.PresignAssetDownload,
		connect.WithSchema(mediaServiceMethods.ByName("PresignAssetDownload")),
		connect.WithHandlerOptions(opts...),
	)
	mediaServiceGetMediaRoleURLHandler := connect.NewUnaryHandler(
		MediaServiceGetMediaRoleURLProcedure,
		svc.GetMediaRoleURL,
		connect.WithSchema(mediaServiceMethods.ByName("GetMediaRoleURL")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mediaservice.media.v1.MediaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MediaServiceListMediaProcedure:
			mediaServiceListMediaHandler.ServeHTTP(w, r)
		case MediaServiceGetMediaProcedure:
			mediaServiceGetMediaHandler.ServeHTTP(w, r)
		case MediaServiceDeleteMediaProcedure:
			mediaServiceDeleteMediaHandler.ServeHTTP(w, r)
		case MediaServiceListAssetsProcedure:
			mediaServiceListAssetsHandler.ServeHTTP(w, r)
		case MediaServiceGetAssetProcedure:
			mediaServiceGetAssetHandler.ServeHTTP(w, r)
		case MediaServiceCreateAssetsProcedure:
			mediaServiceCreateAssetsHandler.ServeHTTP(w, r)
		case MediaServiceRetryAssetProcedure:
			mediaServiceRetryAssetHandler.ServeHTTP(w, r)
		case MediaServiceInitPresignedUploadProcedure:
			mediaServiceInitPresignedUploadHandler.ServeHTTP(w, r)
		case MediaServiceRefreshPresignedUploadProcedure:
			mediaServiceRefreshPresignedUploadHandler.ServeHTTP(w, r)
		case MediaServiceCompletePresignedUploadProcedure:
			mediaServiceCompletePresignedUploadHandler.ServeHTTP(w, r)
		case MediaServicePresignAssetDownloadProcedure:
			mediaServicePresignAssetDownloadHandler.ServeHTTP(w, r)
		case MediaServiceGetMediaRoleURLProcedure:
			mediaServiceGetMediaRoleURLHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMediaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMediaServiceHandler struct{}

func (UnimplementedMediaServiceHandler) ListMedia(context.Context, *connect.Request[v1.ListMediaRequest]) (*connect.Response[v1.ListMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.ListMedia is not implemented"))
}

func (UnimplementedMediaServiceHandler) GetMedia(context.Context, *connect.Request[v1.GetMediaRequest]) (*connect.Response[v1.GetMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.GetMedia is not implemented"))
}

func (UnimplementedMediaServiceHandler) DeleteMedia(context.Context, *connect.Request[v1.DeleteMediaRequest]) (*connect.Response[v1.DeleteMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.DeleteMedia is not implemented"))
}

func (UnimplementedMediaServiceHandler) ListAssets(context.Context, *connect.Request[v1.ListAssetsRequest]) (*connect.Response[v1.ListAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.ListAssets is not implemented"))
}

func (UnimplementedMediaServiceHandler) GetAsset(context.Context, *connect.Request[v1.GetAssetRequest]) (*connect.Response[v1.GetAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.GetAsset is not implemented"))
}

func (UnimplementedMediaServiceHandler) CreateAssets(context.Context, *connect.Request[v1.CreateAssetsRequest]) (*connect.Response[v1.CreateAssetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.CreateAssets is not implemented"))
}

func (UnimplementedMediaServiceHandler) RetryAsset(context.Context, *connect.Request[v1.RetryAssetRequest]) (*connect.Response[v1.RetryAssetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.RetryAsset is not implemented"))
}

func (UnimplementedMediaServiceHandler) InitPresignedUpload(context.Context, *connect.Request[v1.InitPresignedUploadRequest]) (*connect.Response[v1.InitPresignedUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.InitPresignedUpload is not implemented"))
}

func (UnimplementedMediaServiceHandler) RefreshPresignedUpload(context.Context, *connect.Request[v1.RefreshPresignedUploadRequest]) (*connect.Response[v1.RefreshPresignedUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.RefreshPresignedUpload is not implemented"))
}

func (UnimplementedMediaServiceHandler) CompletePresignedUpload(context.Context, *connect.Request[v1.CompletePresignedUploadRequest]) (*connect.Response[v1.CompletePresignedUploadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.CompletePresignedUpload is not implemented"))
}

func (UnimplementedMediaServiceHandler) PresignAssetDownload(context.Context, *connect.Request[v1.PresignAssetDownloadRequest]) (*connect.Response[v1.PresignAssetDownloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.PresignAssetDownload is not implemented"))
}

func (UnimplementedMediaServiceHandler) GetMediaRoleURL(context.Context, *connect.Request[v1.GetMediaRoleURLRequest]) (*connect.Response[v1.GetMediaRoleURLResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.media.v1.MediaService.GetMediaRoleURL is not implemented"))
}
