// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mediaservice/admin/v1/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DLQQueue struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Name                    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	QueueUrl                string                 `protobuf:"bytes,2,opt,name=queue_url,json=queueUrl,proto3" json:"queue_url,omitempty"`
	SourceQueueUrl          string                 `protobuf:"bytes,3,opt,name=source_queue_url,json=sourceQueueUrl,proto3" json:"source_queue_url,omitempty"`
	ApproximateMessageCount int32                  `protobuf:"varint,4,opt,name=approximate_message_count,json=approximateMessageCount,proto3" json:"approximate_message_count,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DLQQueue) Reset() {
	*x = DLQQueue{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQQueue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQQueue) ProtoMessage() {}

func (x *DLQQueue) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQQueue.ProtoReflect.Descriptor instead.
func (*DLQQueue) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{0}
}

func (x *DLQQueue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DLQQueue) GetQueueUrl() string {
	if x != nil {
		return x.QueueUrl
	}
	return ""
}

func (x *DLQQueue) GetSourceQueueUrl() string {
	if x != nil {
		return x.SourceQueueUrl
	}
	return ""
}

func (x *DLQQueue) GetApproximateMessageCount() int32 {
	if x != nil {
		return x.ApproximateMessageCount
	}
	return 0
}

type GetDLQStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDLQStatusRequest) Reset() {
	*x = GetDLQStatusRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDLQStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDLQStatusRequest) ProtoMessage() {}

func (x *GetDLQStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDLQStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDLQStatusRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{1}
}

type GetDLQStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*DLQQueue            `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDLQStatusResponse) Reset() {
	*x = GetDLQStatusResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDLQStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDLQStatusResponse) ProtoMessage() {}

func (x *GetDLQStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDLQStatusResponse.ProtoReflect.Descriptor instead.
func (*GetDLQStatusResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *GetDLQStatusResponse) GetQueues() []*DLQQueue {
	if x != nil {
		return x.Queues
	}
	return nil
}

type ListDLQMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DlqName       string                 `protobuf:"bytes,1,opt,name=dlq_name,json=dlqName,proto3" json:"dlq_name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQMessagesRequest) Reset() {
	*x = ListDLQMessagesRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQMessagesRequest) ProtoMessage() {}

func (x *ListDLQMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListDLQMessagesRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ListDLQMessagesRequest) GetDlqName() string {
	if x != nil {
		return x.DlqName
	}
	return ""
}

func (x *ListDLQMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DLQMessage struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MessageId               string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceiptHandle           string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	Body                    string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	MessageAttributes       map[string]string      `protobuf:"bytes,4,rep,name=message_attributes,json=messageAttributes,proto3" json:"message_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SentTimestamp           *string                `protobuf:"bytes,5,opt,name=sent_timestamp,json=sentTimestamp,proto3,oneof" json:"sent_timestamp,omitempty"`
	ApproximateReceiveCount *int32                 `protobuf:"varint,6,opt,name=approximate_receive_count,json=approximateReceiveCount,proto3,oneof" json:"approximate_receive_count,omitempty"`
	// body_signature is an HMAC over (dlq_name|message_id|body|canonical-attrs)
	// returned by Peek; Replay echoes it back and the server verifies before
	// re-sending so the body cannot be tampered with between Peek and Replay.
	BodySignature string `protobuf:"bytes,7,opt,name=body_signature,json=bodySignature,proto3" json:"body_signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLQMessage) Reset() {
	*x = DLQMessage{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQMessage) ProtoMessage() {}

func (x *DLQMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQMessage.ProtoReflect.Descriptor instead.
func (*DLQMessage) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DLQMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DLQMessage) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

func (x *DLQMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DLQMessage) GetMessageAttributes() map[string]string {
	if x != nil {
		return x.MessageAttributes
	}
	return nil
}

func (x *DLQMessage) GetSentTimestamp() string {
	if x != nil && x.SentTimestamp != nil {
		return *x.SentTimestamp
	}
	return ""
}

func (x *DLQMessage) GetApproximateReceiveCount() int32 {
	if x != nil && x.ApproximateReceiveCount != nil {
		return *x.ApproximateReceiveCount
	}
	return 0
}

func (x *DLQMessage) GetBodySignature() string {
	if x != nil {
		return x.BodySignature
	}
	return ""
}

type ListDLQMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*DLQMessage          `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQMessagesResponse) Reset() {
	*x = ListDLQMessagesResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQMessagesResponse) ProtoMessage() {}

func (x *ListDLQMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListDLQMessagesResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListDLQMessagesResponse) GetMessages() []*DLQMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DLQMessageInput struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MessageId         string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ReceiptHandle     string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	Body              string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	MessageAttributes map[string]string      `protobuf:"bytes,4,rep,name=message_attributes,json=messageAttributes,proto3" json:"message_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BodySignature     string                 `protobuf:"bytes,5,opt,name=body_signature,json=bodySignature,proto3" json:"body_signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DLQMessageInput) Reset() {
	*x = DLQMessageInput{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQMessageInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQMessageInput) ProtoMessage() {}

func (x *DLQMessageInput) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQMessageInput.ProtoReflect.Descriptor instead.
func (*DLQMessageInput) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DLQMessageInput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DLQMessageInput) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

func (x *DLQMessageInput) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DLQMessageInput) GetMessageAttributes() map[string]string {
	if x != nil {
		return x.MessageAttributes
	}
	return nil
}

func (x *DLQMessageInput) GetBodySignature() string {
	if x != nil {
		return x.BodySignature
	}
	return ""
}

type ReplayDLQMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DlqName       string                 `protobuf:"bytes,1,opt,name=dlq_name,json=dlqName,proto3" json:"dlq_name,omitempty"`
	Messages      []*DLQMessageInput     `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDLQMessagesRequest) Reset() {
	*x = ReplayDLQMessagesRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDLQMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDLQMessagesRequest) ProtoMessage() {}

func (x *ReplayDLQMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDLQMessagesRequest.ProtoReflect.Descriptor instead.
func (*ReplayDLQMessagesRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ReplayDLQMessagesRequest) GetDlqName() string {
	if x != nil {
		return x.DlqName
	}
	return ""
}

func (x *ReplayDLQMessagesRequest) GetMessages() []*DLQMessageInput {
	if x != nil {
		return x.Messages
	}
	return nil
}

type DLQReplayFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLQReplayFailure) Reset() {
	*x = DLQReplayFailure{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQReplayFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQReplayFailure) ProtoMessage() {}

func (x *DLQReplayFailure) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQReplayFailure.ProtoReflect.Descriptor instead.
func (*DLQReplayFailure) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DLQReplayFailure) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DLQReplayFailure) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DLQReplayFailure) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

type DLQReplayResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OriginalMessageId string                 `protobuf:"bytes,1,opt,name=original_message_id,json=originalMessageId,proto3" json:"original_message_id,omitempty"`
	NewMessageId      *string                `protobuf:"bytes,2,opt,name=new_message_id,json=newMessageId,proto3,oneof" json:"new_message_id,omitempty"`
	Failure           *DLQReplayFailure      `protobuf:"bytes,3,opt,name=failure,proto3,oneof" json:"failure,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DLQReplayResult) Reset() {
	*x = DLQReplayResult{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQReplayResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQReplayResult) ProtoMessage() {}

func (x *DLQReplayResult) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQReplayResult.ProtoReflect.Descriptor instead.
func (*DLQReplayResult) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DLQReplayResult) GetOriginalMessageId() string {
	if x != nil {
		return x.OriginalMessageId
	}
	return ""
}

func (x *DLQReplayResult) GetNewMessageId() string {
	if x != nil && x.NewMessageId != nil {
		return *x.NewMessageId
	}
	return ""
}

func (x *DLQReplayResult) GetFailure() *DLQReplayFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type ReplayDLQMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DLQReplayResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDLQMessagesResponse) Reset() {
	*x = ReplayDLQMessagesResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDLQMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDLQMessagesResponse) ProtoMessage() {}

func (x *ReplayDLQMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDLQMessagesResponse.ProtoReflect.Descriptor instead.
func (*ReplayDLQMessagesResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ReplayDLQMessagesResponse) GetResults() []*DLQReplayResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type DeleteDLQMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DlqName       string                 `protobuf:"bytes,1,opt,name=dlq_name,json=dlqName,proto3" json:"dlq_name,omitempty"`
	ReceiptHandle string                 `protobuf:"bytes,2,opt,name=receipt_handle,json=receiptHandle,proto3" json:"receipt_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDLQMessageRequest) Reset() {
	*x = DeleteDLQMessageRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDLQMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDLQMessageRequest) ProtoMessage() {}

func (x *DeleteDLQMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDLQMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteDLQMessageRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDLQMessageRequest) GetDlqName() string {
	if x != nil {
		return x.DlqName
	}
	return ""
}

func (x *DeleteDLQMessageRequest) GetReceiptHandle() string {
	if x != nil {
		return x.ReceiptHandle
	}
	return ""
}

type DeleteDLQMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDLQMessageResponse) Reset() {
	*x = DeleteDLQMessageResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDLQMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDLQMessageResponse) ProtoMessage() {}

func (x *DeleteDLQMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDLQMessageResponse.ProtoReflect.Descriptor instead.
func (*DeleteDLQMessageResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{12}
}

type PurgeDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DlqName       string                 `protobuf:"bytes,1,opt,name=dlq_name,json=dlqName,proto3" json:"dlq_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeDLQRequest) Reset() {
	*x = PurgeDLQRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeDLQRequest) ProtoMessage() {}

func (x *PurgeDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeDLQRequest.ProtoReflect.Descriptor instead.
func (*PurgeDLQRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *PurgeDLQRequest) GetDlqName() string {
	if x != nil {
		return x.DlqName
	}
	return ""
}

type PurgeDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeDLQResponse) Reset() {
	*x = PurgeDLQResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeDLQResponse) ProtoMessage() {}

func (x *PurgeDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeDLQResponse.ProtoReflect.Descriptor instead.
func (*PurgeDLQResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{14}
}

// OutboxDLQRow is a poisoned transactional-outbox row that the relay couldn't
// publish after exhausting retries. Operators can replay (write a fresh
// outbox event with `replayed_from_event_id`) or abandon (mark the row
// terminally failed so dashboards stop alarming).
type OutboxDLQRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Shard         string                 `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	LastError     *string                `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	Attempts      int32                  `protobuf:"varint,8,opt,name=attempts,proto3" json:"attempts,omitempty"`
	PartitionTs   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=partition_ts,json=partitionTs,proto3" json:"partition_ts,omitempty"`
	FirstFailedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=first_failed_at,json=firstFailedAt,proto3" json:"first_failed_at,omitempty"`
	LastFailedAt  *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_failed_at,json=lastFailedAt,proto3" json:"last_failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxDLQRow) Reset() {
	*x = OutboxDLQRow{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxDLQRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxDLQRow) ProtoMessage() {}

func (x *OutboxDLQRow) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxDLQRow.ProtoReflect.Descriptor instead.
func (*OutboxDLQRow) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *OutboxDLQRow) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *OutboxDLQRow) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *OutboxDLQRow) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *OutboxDLQRow) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OutboxDLQRow) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OutboxDLQRow) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *OutboxDLQRow) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

func (x *OutboxDLQRow) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *OutboxDLQRow) GetPartitionTs() *timestamppb.Timestamp {
	if x != nil {
		return x.PartitionTs
	}
	return nil
}

func (x *OutboxDLQRow) GetFirstFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstFailedAt
	}
	return nil
}

func (x *OutboxDLQRow) GetLastFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastFailedAt
	}
	return nil
}

type ListOutboxDlqRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        *string                `protobuf:"bytes,3,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutboxDlqRowsRequest) Reset() {
	*x = ListOutboxDlqRowsRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutboxDlqRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboxDlqRowsRequest) ProtoMessage() {}

func (x *ListOutboxDlqRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboxDlqRowsRequest.ProtoReflect.Descriptor instead.
func (*ListOutboxDlqRowsRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ListOutboxDlqRowsRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ListOutboxDlqRowsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListOutboxDlqRowsRequest) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

type ListOutboxDlqRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*OutboxDLQRow        `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	NextCursor    *string                `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutboxDlqRowsResponse) Reset() {
	*x = ListOutboxDlqRowsResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutboxDlqRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboxDlqRowsResponse) ProtoMessage() {}

func (x *ListOutboxDlqRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboxDlqRowsResponse.ProtoReflect.Descriptor instead.
func (*ListOutboxDlqRowsResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ListOutboxDlqRowsResponse) GetRows() []*OutboxDLQRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ListOutboxDlqRowsResponse) GetNextCursor() string {
	if x != nil && x.NextCursor != nil {
		return *x.NextCursor
	}
	return ""
}

type ReplayOutboxDlqRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayOutboxDlqRowRequest) Reset() {
	*x = ReplayOutboxDlqRowRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayOutboxDlqRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayOutboxDlqRowRequest) ProtoMessage() {}

func (x *ReplayOutboxDlqRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayOutboxDlqRowRequest.ProtoReflect.Descriptor instead.
func (*ReplayOutboxDlqRowRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ReplayOutboxDlqRowRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *ReplayOutboxDlqRowRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ReplayOutboxDlqRowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReplayOutboxDlqRowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// replayed_from_event_id is the original DLQ row's event id; new_event_id
	// is the freshly-allocated replay row. Operators correlate audit + metrics
	// through replayed_from_event_id.
	ReplayedFromEventId string `protobuf:"bytes,1,opt,name=replayed_from_event_id,json=replayedFromEventId,proto3" json:"replayed_from_event_id,omitempty"`
	NewEventId          string `protobuf:"bytes,2,opt,name=new_event_id,json=newEventId,proto3" json:"new_event_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ReplayOutboxDlqRowResponse) Reset() {
	*x = ReplayOutboxDlqRowResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayOutboxDlqRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayOutboxDlqRowResponse) ProtoMessage() {}

func (x *ReplayOutboxDlqRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayOutboxDlqRowResponse.ProtoReflect.Descriptor instead.
func (*ReplayOutboxDlqRowResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ReplayOutboxDlqRowResponse) GetReplayedFromEventId() string {
	if x != nil {
		return x.ReplayedFromEventId
	}
	return ""
}

func (x *ReplayOutboxDlqRowResponse) GetNewEventId() string {
	if x != nil {
		return x.NewEventId
	}
	return ""
}

type AbandonOutboxDlqRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonOutboxDlqRowRequest) Reset() {
	*x = AbandonOutboxDlqRowRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonOutboxDlqRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonOutboxDlqRowRequest) ProtoMessage() {}

func (x *AbandonOutboxDlqRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonOutboxDlqRowRequest.ProtoReflect.Descriptor instead.
func (*AbandonOutboxDlqRowRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *AbandonOutboxDlqRowRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AbandonOutboxDlqRowRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AbandonOutboxDlqRowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AbandonOutboxDlqRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonOutboxDlqRowResponse) Reset() {
	*x = AbandonOutboxDlqRowResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonOutboxDlqRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonOutboxDlqRowResponse) ProtoMessage() {}

func (x *AbandonOutboxDlqRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonOutboxDlqRowResponse.ProtoReflect.Descriptor instead.
func (*AbandonOutboxDlqRowResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{21}
}

type DeleteOutboxDlqRowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOutboxDlqRowRequest) Reset() {
	*x = DeleteOutboxDlqRowRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOutboxDlqRowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOutboxDlqRowRequest) ProtoMessage() {}

func (x *DeleteOutboxDlqRowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOutboxDlqRowRequest.ProtoReflect.Descriptor instead.
func (*DeleteOutboxDlqRowRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteOutboxDlqRowRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *DeleteOutboxDlqRowRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *DeleteOutboxDlqRowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteOutboxDlqRowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOutboxDlqRowResponse) Reset() {
	*x = DeleteOutboxDlqRowResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOutboxDlqRowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOutboxDlqRowResponse) ProtoMessage() {}

func (x *DeleteOutboxDlqRowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOutboxDlqRowResponse.ProtoReflect.Descriptor instead.
func (*DeleteOutboxDlqRowResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{23}
}

type PurgeOutboxDlqRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        string                 `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeOutboxDlqRowsRequest) Reset() {
	*x = PurgeOutboxDlqRowsRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeOutboxDlqRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeOutboxDlqRowsRequest) ProtoMessage() {}

func (x *PurgeOutboxDlqRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeOutboxDlqRowsRequest.ProtoReflect.Descriptor instead.
func (*PurgeOutboxDlqRowsRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *PurgeOutboxDlqRowsRequest) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *PurgeOutboxDlqRowsRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PurgeOutboxDlqRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeOutboxDlqRowsResponse) Reset() {
	*x = PurgeOutboxDlqRowsResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeOutboxDlqRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeOutboxDlqRowsResponse) ProtoMessage() {}

func (x *PurgeOutboxDlqRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeOutboxDlqRowsResponse.ProtoReflect.Descriptor instead.
func (*PurgeOutboxDlqRowsResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *PurgeOutboxDlqRowsResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

// InspectIdempotencyClaimRequest reads a claim row without mutation. The
// scope is the full IDEMPOTENCY#... primary key as written by the
// idempotency package — operators copy it from logs or audit rows.
type InspectIdempotencyClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectIdempotencyClaimRequest) Reset() {
	*x = InspectIdempotencyClaimRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIdempotencyClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIdempotencyClaimRequest) ProtoMessage() {}

func (x *InspectIdempotencyClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIdempotencyClaimRequest.ProtoReflect.Descriptor instead.
func (*InspectIdempotencyClaimRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *InspectIdempotencyClaimRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type IdempotencyClaim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	InputHash     string                 `protobuf:"bytes,3,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	ResultRef     string                 `protobuf:"bytes,4,opt,name=result_ref,json=resultRef,proto3" json:"result_ref,omitempty"`
	ClaimedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=claimed_at,json=claimedAt,proto3,oneof" json:"claimed_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	TtlAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=ttl_at,json=ttlAt,proto3,oneof" json:"ttl_at,omitempty"`
	Attempts      *int32                 `protobuf:"varint,8,opt,name=attempts,proto3,oneof" json:"attempts,omitempty"`
	LastError     *string                `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3,oneof" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdempotencyClaim) Reset() {
	*x = IdempotencyClaim{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotencyClaim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotencyClaim) ProtoMessage() {}

func (x *IdempotencyClaim) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotencyClaim.ProtoReflect.Descriptor instead.
func (*IdempotencyClaim) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *IdempotencyClaim) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IdempotencyClaim) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *IdempotencyClaim) GetInputHash() string {
	if x != nil {
		return x.InputHash
	}
	return ""
}

func (x *IdempotencyClaim) GetResultRef() string {
	if x != nil {
		return x.ResultRef
	}
	return ""
}

func (x *IdempotencyClaim) GetClaimedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClaimedAt
	}
	return nil
}

func (x *IdempotencyClaim) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *IdempotencyClaim) GetTtlAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TtlAt
	}
	return nil
}

func (x *IdempotencyClaim) GetAttempts() int32 {
	if x != nil && x.Attempts != nil {
		return *x.Attempts
	}
	return 0
}

func (x *IdempotencyClaim) GetLastError() string {
	if x != nil && x.LastError != nil {
		return *x.LastError
	}
	return ""
}

type InspectIdempotencyClaimResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claim         *IdempotencyClaim      `protobuf:"bytes,1,opt,name=claim,proto3" json:"claim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectIdempotencyClaimResponse) Reset() {
	*x = InspectIdempotencyClaimResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectIdempotencyClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectIdempotencyClaimResponse) ProtoMessage() {}

func (x *InspectIdempotencyClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectIdempotencyClaimResponse.ProtoReflect.Descriptor instead.
func (*InspectIdempotencyClaimResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *InspectIdempotencyClaimResponse) GetClaim() *IdempotencyClaim {
	if x != nil {
		return x.Claim
	}
	return nil
}

// ResetIdempotencyClaim invalidates an existing claim so the next request
// proceeds as NEW. Used as the operator escape hatch when a claim row gets
// wedged in CLAIMED past its TTL. Reset is audited and returns the next
// `reset_generation` value derived from the invalidated row.
type ResetIdempotencyClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetIdempotencyClaimRequest) Reset() {
	*x = ResetIdempotencyClaimRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetIdempotencyClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetIdempotencyClaimRequest) ProtoMessage() {}

func (x *ResetIdempotencyClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetIdempotencyClaimRequest.ProtoReflect.Descriptor instead.
func (*ResetIdempotencyClaimRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *ResetIdempotencyClaimRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ResetIdempotencyClaimRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ResetIdempotencyClaimResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Scope           string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	ResetGeneration int32                  `protobuf:"varint,2,opt,name=reset_generation,json=resetGeneration,proto3" json:"reset_generation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetIdempotencyClaimResponse) Reset() {
	*x = ResetIdempotencyClaimResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetIdempotencyClaimResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetIdempotencyClaimResponse) ProtoMessage() {}

func (x *ResetIdempotencyClaimResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetIdempotencyClaimResponse.ProtoReflect.Descriptor instead.
func (*ResetIdempotencyClaimResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *ResetIdempotencyClaimResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ResetIdempotencyClaimResponse) GetResetGeneration() int32 {
	if x != nil {
		return x.ResetGeneration
	}
	return 0
}

// OverrideQuotaCap raises (or lowers) the daily quota reservoir for a tenant
// + metric combination. Conditional update on the reservoir version prevents
// lost updates from concurrent overrides.
type OverrideQuotaCapRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TenantId string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Metric   string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	// period is the YYYYMMDD bucket for daily quotas. Weekly/monthly buckets
	// use the same string format prefixed with the period kind (e.g.
	// "W#202620" for ISO week 20 of 2026).
	Period        string `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	NewCap        int64  `protobuf:"varint,4,opt,name=new_cap,json=newCap,proto3" json:"new_cap,omitempty"`
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideQuotaCapRequest) Reset() {
	*x = OverrideQuotaCapRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideQuotaCapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideQuotaCapRequest) ProtoMessage() {}

func (x *OverrideQuotaCapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideQuotaCapRequest.ProtoReflect.Descriptor instead.
func (*OverrideQuotaCapRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *OverrideQuotaCapRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OverrideQuotaCapRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *OverrideQuotaCapRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *OverrideQuotaCapRequest) GetNewCap() int64 {
	if x != nil {
		return x.NewCap
	}
	return 0
}

func (x *OverrideQuotaCapRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OverrideQuotaCapResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Metric           string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Period           string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	PreviousCap      int64                  `protobuf:"varint,4,opt,name=previous_cap,json=previousCap,proto3" json:"previous_cap,omitempty"`
	NewCap           int64                  `protobuf:"varint,5,opt,name=new_cap,json=newCap,proto3" json:"new_cap,omitempty"`
	ReservoirVersion int64                  `protobuf:"varint,6,opt,name=reservoir_version,json=reservoirVersion,proto3" json:"reservoir_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OverrideQuotaCapResponse) Reset() {
	*x = OverrideQuotaCapResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideQuotaCapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideQuotaCapResponse) ProtoMessage() {}

func (x *OverrideQuotaCapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideQuotaCapResponse.ProtoReflect.Descriptor instead.
func (*OverrideQuotaCapResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *OverrideQuotaCapResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *OverrideQuotaCapResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *OverrideQuotaCapResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *OverrideQuotaCapResponse) GetPreviousCap() int64 {
	if x != nil {
		return x.PreviousCap
	}
	return 0
}

func (x *OverrideQuotaCapResponse) GetNewCap() int64 {
	if x != nil {
		return x.NewCap
	}
	return 0
}

func (x *OverrideQuotaCapResponse) GetReservoirVersion() int64 {
	if x != nil {
		return x.ReservoirVersion
	}
	return 0
}

type RotateWebhookSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EndpointId    string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateWebhookSecretRequest) Reset() {
	*x = RotateWebhookSecretRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateWebhookSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateWebhookSecretRequest) ProtoMessage() {}

func (x *RotateWebhookSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateWebhookSecretRequest.ProtoReflect.Descriptor instead.
func (*RotateWebhookSecretRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *RotateWebhookSecretRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RotateWebhookSecretRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *RotateWebhookSecretRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RotateWebhookSecretResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EndpointId     string                 `protobuf:"bytes,2,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	OldSecretKeyId string                 `protobuf:"bytes,3,opt,name=old_secret_key_id,json=oldSecretKeyId,proto3" json:"old_secret_key_id,omitempty"`
	NewSecretKeyId string                 `protobuf:"bytes,4,opt,name=new_secret_key_id,json=newSecretKeyId,proto3" json:"new_secret_key_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RotateWebhookSecretResponse) Reset() {
	*x = RotateWebhookSecretResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateWebhookSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateWebhookSecretResponse) ProtoMessage() {}

func (x *RotateWebhookSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateWebhookSecretResponse.ProtoReflect.Descriptor instead.
func (*RotateWebhookSecretResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{34}
}

func (x *RotateWebhookSecretResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RotateWebhookSecretResponse) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *RotateWebhookSecretResponse) GetOldSecretKeyId() string {
	if x != nil {
		return x.OldSecretKeyId
	}
	return ""
}

func (x *RotateWebhookSecretResponse) GetNewSecretKeyId() string {
	if x != nil {
		return x.NewSecretKeyId
	}
	return ""
}

type SuspendTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantRequest) Reset() {
	*x = SuspendTenantRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantRequest) ProtoMessage() {}

func (x *SuspendTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantRequest.ProtoReflect.Descriptor instead.
func (*SuspendTenantRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{35}
}

func (x *SuspendTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SuspendTenantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SuspendTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantResponse) Reset() {
	*x = SuspendTenantResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantResponse) ProtoMessage() {}

func (x *SuspendTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantResponse.ProtoReflect.Descriptor instead.
func (*SuspendTenantResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{36}
}

type UnsuspendTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsuspendTenantRequest) Reset() {
	*x = UnsuspendTenantRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsuspendTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsuspendTenantRequest) ProtoMessage() {}

func (x *UnsuspendTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsuspendTenantRequest.ProtoReflect.Descriptor instead.
func (*UnsuspendTenantRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{37}
}

func (x *UnsuspendTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UnsuspendTenantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UnsuspendTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsuspendTenantResponse) Reset() {
	*x = UnsuspendTenantResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsuspendTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsuspendTenantResponse) ProtoMessage() {}

func (x *UnsuspendTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsuspendTenantResponse.ProtoReflect.Descriptor instead.
func (*UnsuspendTenantResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{38}
}

type CancelWorkflowJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowJobRequest) Reset() {
	*x = CancelWorkflowJobRequest{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowJobRequest) ProtoMessage() {}

func (x *CancelWorkflowJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowJobRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowJobRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{39}
}

func (x *CancelWorkflowJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelWorkflowJobRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CancelWorkflowJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowJobResponse) Reset() {
	*x = CancelWorkflowJobResponse{}
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowJobResponse) ProtoMessage() {}

func (x *CancelWorkflowJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_admin_v1_admin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowJobResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowJobResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_admin_v1_admin_proto_rawDescGZIP(), []int{40}
}

var File_mediaservice_admin_v1_admin_proto protoreflect.FileDescriptor

const file_mediaservice_admin_v1_admin_proto_rawDesc = "" +
	"\n" +
	"!mediaservice/admin/v1/admin.proto\x12\x15mediaservice.admin.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x01\n" +
	"\bDLQQueue\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tqueue_url\x18\x02 \x01(\tR\bqueueUrl\x12(\n" +
	"\x10source_queue_url\x18\x03 \x01(\tR\x0esourceQueueUrl\x12:\n" +
	"\x19approximate_message_count\x18\x04 \x01(\x05R\x17approximateMessageCount\"\x15\n" +
	"\x13GetDLQStatusRequest\"O\n" +
	"\x14GetDLQStatusResponse\x127\n" +
	"\x06queues\x18\x01 \x03(\v2\x1f.mediaservice.admin.v1.DLQQueueR\x06queues\"I\n" +
	"\x16ListDLQMessagesRequest\x12\x19\n" +
	"\bdlq_name\x18\x01 \x01(\tR\adlqName\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xda\x03\n" +
	"\n" +
	"DLQMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12g\n" +
	"\x12message_attributes\x18\x04 \x03(\v28.mediaservice.admin.v1.DLQMessage.MessageAttributesEntryR\x11messageAttributes\x12*\n" +
	"\x0esent_timestamp\x18\x05 \x01(\tH\x00R\rsentTimestamp\x88\x01\x01\x12?\n" +
	"\x19approximate_receive_count\x18\x06 \x01(\x05H\x01R\x17approximateReceiveCount\x88\x01\x01\x12%\n" +
	"\x0ebody_signature\x18\a \x01(\tR\rbodySignature\x1aD\n" +
	"\x16MessageAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x11\n" +
	"\x0f_sent_timestampB\x1c\n" +
	"\x1a_approximate_receive_count\"X\n" +
	"\x17ListDLQMessagesResponse\x12=\n" +
	"\bmessages\x18\x01 \x03(\v2!.mediaservice.admin.v1.DLQMessageR\bmessages\"\xc6\x02\n" +
	"\x0fDLQMessageInput\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12l\n" +
	"\x12message_attributes\x18\x04 \x03(\v2=.mediaservice.admin.v1.DLQMessageInput.MessageAttributesEntryR\x11messageAttributes\x12%\n" +
	"\x0ebody_signature\x18\x05 \x01(\tR\rbodySignature\x1aD\n" +
	"\x16MessageAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"y\n" +
	"\x18ReplayDLQMessagesRequest\x12\x19\n" +
	"\bdlq_name\x18\x01 \x01(\tR\adlqName\x12B\n" +
	"\bmessages\x18\x02 \x03(\v2&.mediaservice.admin.v1.DLQMessageInputR\bmessages\"t\n" +
	"\x10DLQReplayFailure\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\"\xd3\x01\n" +
	"\x0fDLQReplayResult\x12.\n" +
	"\x13original_message_id\x18\x01 \x01(\tR\x11originalMessageId\x12)\n" +
	"\x0enew_message_id\x18\x02 \x01(\tH\x00R\fnewMessageId\x88\x01\x01\x12F\n" +
	"\afailure\x18\x03 \x01(\v2'.mediaservice.admin.v1.DLQReplayFailureH\x01R\afailure\x88\x01\x01B\x11\n" +
	"\x0f_new_message_idB\n" +
	"\n" +
	"\b_failure\"]\n" +
	"\x19ReplayDLQMessagesResponse\x12@\n" +
	"\aresults\x18\x01 \x03(\v2&.mediaservice.admin.v1.DLQReplayResultR\aresults\"[\n" +
	"\x17DeleteDLQMessageRequest\x12\x19\n" +
	"\bdlq_name\x18\x01 \x01(\tR\adlqName\x12%\n" +
	"\x0ereceipt_handle\x18\x02 \x01(\tR\rreceiptHandle\"\x1a\n" +
	"\x18DeleteDLQMessageResponse\",\n" +
	"\x0fPurgeDLQRequest\x12\x19\n" +
	"\bdlq_name\x18\x01 \x01(\tR\adlqName\"\x12\n" +
	"\x10PurgeDLQResponse\"\xbb\x03\n" +
	"\fOutboxDLQRow\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\tR\x05shard\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x12\n" +
	"\x04body\x18\x06 \x01(\fR\x04body\x12\"\n" +
	"\n" +
	"last_error\x18\a \x01(\tH\x00R\tlastError\x88\x01\x01\x12\x1a\n" +
	"\battempts\x18\b \x01(\x05R\battempts\x12=\n" +
	"\fpartition_ts\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vpartitionTs\x12B\n" +
	"\x0ffirst_failed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rfirstFailedAt\x12@\n" +
	"\x0elast_failed_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\flastFailedAtB\r\n" +
	"\v_last_error\"p\n" +
	"\x18ListOutboxDlqRowsRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1b\n" +
	"\x06cursor\x18\x03 \x01(\tH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"\x8a\x01\n" +
	"\x19ListOutboxDlqRowsResponse\x127\n" +
	"\x04rows\x18\x01 \x03(\v2#.mediaservice.admin.v1.OutboxDLQRowR\x04rows\x12$\n" +
	"\vnext_cursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\x0e\n" +
	"\f_next_cursor\"f\n" +
	"\x19ReplayOutboxDlqRowRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"s\n" +
	"\x1aReplayOutboxDlqRowResponse\x123\n" +
	"\x16replayed_from_event_id\x18\x01 \x01(\tR\x13replayedFromEventId\x12 \n" +
	"\fnew_event_id\x18\x02 \x01(\tR\n" +
	"newEventId\"g\n" +
	"\x1aAbandonOutboxDlqRowRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x1d\n" +
	"\x1bAbandonOutboxDlqRowResponse\"f\n" +
	"\x19DeleteOutboxDlqRowRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x1c\n" +
	"\x1aDeleteOutboxDlqRowResponse\"K\n" +
	"\x19PurgeOutboxDlqRowsRequest\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"A\n" +
	"\x1aPurgeOutboxDlqRowsResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\"6\n" +
	"\x1eInspectIdempotencyClaimRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\"\xc6\x03\n" +
	"\x10IdempotencyClaim\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"input_hash\x18\x03 \x01(\tR\tinputHash\x12\x1d\n" +
	"\n" +
	"result_ref\x18\x04 \x01(\tR\tresultRef\x12>\n" +
	"\n" +
	"claimed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tclaimedAt\x88\x01\x01\x12B\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\vcompletedAt\x88\x01\x01\x126\n" +
	"\x06ttl_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x05ttlAt\x88\x01\x01\x12\x1f\n" +
	"\battempts\x18\b \x01(\x05H\x03R\battempts\x88\x01\x01\x12\"\n" +
	"\n" +
	"last_error\x18\t \x01(\tH\x04R\tlastError\x88\x01\x01B\r\n" +
	"\v_claimed_atB\x0f\n" +
	"\r_completed_atB\t\n" +
	"\a_ttl_atB\v\n" +
	"\t_attemptsB\r\n" +
	"\v_last_error\"`\n" +
	"\x1fInspectIdempotencyClaimResponse\x12=\n" +
	"\x05claim\x18\x01 \x01(\v2'.mediaservice.admin.v1.IdempotencyClaimR\x05claim\"L\n" +
	"\x1cResetIdempotencyClaimRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"`\n" +
	"\x1dResetIdempotencyClaimResponse\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12)\n" +
	"\x10reset_generation\x18\x02 \x01(\x05R\x0fresetGeneration\"\x97\x01\n" +
	"\x17OverrideQuotaCapRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12\x17\n" +
	"\anew_cap\x18\x04 \x01(\x03R\x06newCap\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xd0\x01\n" +
	"\x18OverrideQuotaCapResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12!\n" +
	"\fprevious_cap\x18\x04 \x01(\x03R\vpreviousCap\x12\x17\n" +
	"\anew_cap\x18\x05 \x01(\x03R\x06newCap\x12+\n" +
	"\x11reservoir_version\x18\x06 \x01(\x03R\x10reservoirVersion\"r\n" +
	"\x1aRotateWebhookSecretRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xb1\x01\n" +
	"\x1bRotateWebhookSecretResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vendpoint_id\x18\x02 \x01(\tR\n" +
	"endpointId\x12)\n" +
	"\x11old_secret_key_id\x18\x03 \x01(\tR\x0eoldSecretKeyId\x12)\n" +
	"\x11new_secret_key_id\x18\x04 \x01(\tR\x0enewSecretKeyId\"K\n" +
	"\x14SuspendTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x17\n" +
	"\x15SuspendTenantResponse\"M\n" +
	"\x16UnsuspendTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x19\n" +
	"\x17UnsuspendTenantResponse\"I\n" +
	"\x18CancelWorkflowJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1b\n" +
	"\x19CancelWorkflowJobResponse2\xb6\x04\n" +
	"\x0fDLQAdminService\x12g\n" +
	"\fGetDLQStatus\x12*.mediaservice.admin.v1.GetDLQStatusRequest\x1a+.mediaservice.admin.v1.GetDLQStatusResponse\x12p\n" +
	"\x0fListDLQMessages\x12-.mediaservice.admin.v1.ListDLQMessagesRequest\x1a..mediaservice.admin.v1.ListDLQMessagesResponse\x12v\n" +
	"\x11ReplayDLQMessages\x12/.mediaservice.admin.v1.ReplayDLQMessagesRequest\x1a0.mediaservice.admin.v1.ReplayDLQMessagesResponse\x12s\n" +
	"\x10DeleteDLQMessage\x12..mediaservice.admin.v1.DeleteDLQMessageRequest\x1a/.mediaservice.admin.v1.DeleteDLQMessageResponse\x12[\n" +
	"\bPurgeDLQ\x12&.mediaservice.admin.v1.PurgeDLQRequest\x1a'.mediaservice.admin.v1.PurgeDLQResponse2\xfe\x04\n" +
	"\x15OutboxDLQAdminService\x12v\n" +
	"\x11ListOutboxDlqRows\x12/.mediaservice.admin.v1.ListOutboxDlqRowsRequest\x1a0.mediaservice.admin.v1.ListOutboxDlqRowsResponse\x12y\n" +
	"\x12ReplayOutboxDlqRow\x120.mediaservice.admin.v1.ReplayOutboxDlqRowRequest\x1a1.mediaservice.admin.v1.ReplayOutboxDlqRowResponse\x12|\n" +
	"\x13AbandonOutboxDlqRow\x121.mediaservice.admin.v1.AbandonOutboxDlqRowRequest\x1a2.mediaservice.admin.v1.AbandonOutboxDlqRowResponse\x12y\n" +
	"\x12DeleteOutboxDlqRow\x120.mediaservice.admin.v1.DeleteOutboxDlqRowRequest\x1a1.mediaservice.admin.v1.DeleteOutboxDlqRowResponse\x12y\n" +
	"\x12PurgeOutboxDlqRows\x120.mediaservice.admin.v1.PurgeOutboxDlqRowsRequest\x1a1.mediaservice.admin.v1.PurgeOutboxDlqRowsResponse2\xa9\x02\n" +
	"\x17IdempotencyAdminService\x12\x88\x01\n" +
	"\x17InspectIdempotencyClaim\x125.mediaservice.admin.v1.InspectIdempotencyClaimRequest\x1a6.mediaservice.admin.v1.InspectIdempotencyClaimResponse\x12\x82\x01\n" +
	"\x15ResetIdempotencyClaim\x123.mediaservice.admin.v1.ResetIdempotencyClaimRequest\x1a4.mediaservice.admin.v1.ResetIdempotencyClaimResponse2\x88\x01\n" +
	"\x11QuotaAdminService\x12s\n" +
	"\x10OverrideQuotaCap\x12..mediaservice.admin.v1.OverrideQuotaCapRequest\x1a/.mediaservice.admin.v1.OverrideQuotaCapResponse2\x93\x01\n" +
	"\x13WebhookAdminService\x12|\n" +
	"\x13RotateWebhookSecret\x121.mediaservice.admin.v1.RotateWebhookSecretRequest\x1a2.mediaservice.admin.v1.RotateWebhookSecretResponse2\xf2\x01\n" +
	"\x12TenantAdminService\x12j\n" +
	"\rSuspendTenant\x12+.mediaservice.admin.v1.SuspendTenantRequest\x1a,.mediaservice.admin.v1.SuspendTenantResponse\x12p\n" +
	"\x0fUnsuspendTenant\x12-.mediaservice.admin.v1.UnsuspendTenantRequest\x1a..mediaservice.admin.v1.UnsuspendTenantResponse2\x8e\x01\n" +
	"\x14WorkflowAdminService\x12v\n" +
	"\x11CancelWorkflowJob\x12/.mediaservice.admin.v1.CancelWorkflowJobRequest\x1a0.mediaservice.admin.v1.CancelWorkflowJobResponseB\xfe\x01\n" +
	"\x19com.mediaservice.admin.v1B\n" +
	"AdminProtoP\x01Z_github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/admin/v1;adminv1\xa2\x02\x03MAX\xaa\x02\x15Mediaservice.Admin.V1\xca\x02\x15Mediaservice\\Admin\\V1\xe2\x02!Mediaservice\\Admin\\V1\\GPBMetadata\xea\x02\x17Mediaservice::Admin::V1b\x06proto3"

var (
	file_mediaservice_admin_v1_admin_proto_rawDescOnce sync.Once
	file_mediaservice_admin_v1_admin_proto_rawDescData []byte
)

func file_mediaservice_admin_v1_admin_proto_rawDescGZIP() []byte {
	file_mediaservice_admin_v1_admin_proto_rawDescOnce.Do(func() {
		file_mediaservice_admin_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mediaservice_admin_v1_admin_proto_rawDesc), len(file_mediaservice_admin_v1_admin_proto_rawDesc)))
	})
	return file_mediaservice_admin_v1_admin_proto_rawDescData
}

var file_mediaservice_admin_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_mediaservice_admin_v1_admin_proto_goTypes = []any{
	(*DLQQueue)(nil),                        // 0: mediaservice.admin.v1.DLQQueue
	(*GetDLQStatusRequest)(nil),             // 1: mediaservice.admin.v1.GetDLQStatusRequest
	(*GetDLQStatusResponse)(nil),            // 2: mediaservice.admin.v1.GetDLQStatusResponse
	(*ListDLQMessagesRequest)(nil),          // 3: mediaservice.admin.v1.ListDLQMessagesRequest
	(*DLQMessage)(nil),                      // 4: mediaservice.admin.v1.DLQMessage
	(*ListDLQMessagesResponse)(nil),         // 5: mediaservice.admin.v1.ListDLQMessagesResponse
	(*DLQMessageInput)(nil),                 // 6: mediaservice.admin.v1.DLQMessageInput
	(*ReplayDLQMessagesRequest)(nil),        // 7: mediaservice.admin.v1.ReplayDLQMessagesRequest
	(*DLQReplayFailure)(nil),                // 8: mediaservice.admin.v1.DLQReplayFailure
	(*DLQReplayResult)(nil),                 // 9: mediaservice.admin.v1.DLQReplayResult
	(*ReplayDLQMessagesResponse)(nil),       // 10: mediaservice.admin.v1.ReplayDLQMessagesResponse
	(*DeleteDLQMessageRequest)(nil),         // 11: mediaservice.admin.v1.DeleteDLQMessageRequest
	(*DeleteDLQMessageResponse)(nil),        // 12: mediaservice.admin.v1.DeleteDLQMessageResponse
	(*PurgeDLQRequest)(nil),                 // 13: mediaservice.admin.v1.PurgeDLQRequest
	(*PurgeDLQResponse)(nil),                // 14: mediaservice.admin.v1.PurgeDLQResponse
	(*OutboxDLQRow)(nil),                    // 15: mediaservice.admin.v1.OutboxDLQRow
	(*ListOutboxDlqRowsRequest)(nil),        // 16: mediaservice.admin.v1.ListOutboxDlqRowsRequest
	(*ListOutboxDlqRowsResponse)(nil),       // 17: mediaservice.admin.v1.ListOutboxDlqRowsResponse
	(*ReplayOutboxDlqRowRequest)(nil),       // 18: mediaservice.admin.v1.ReplayOutboxDlqRowRequest
	(*ReplayOutboxDlqRowResponse)(nil),      // 19: mediaservice.admin.v1.ReplayOutboxDlqRowResponse
	(*AbandonOutboxDlqRowRequest)(nil),      // 20: mediaservice.admin.v1.AbandonOutboxDlqRowRequest
	(*AbandonOutboxDlqRowResponse)(nil),     // 21: mediaservice.admin.v1.AbandonOutboxDlqRowResponse
	(*DeleteOutboxDlqRowRequest)(nil),       // 22: mediaservice.admin.v1.DeleteOutboxDlqRowRequest
	(*DeleteOutboxDlqRowResponse)(nil),      // 23: mediaservice.admin.v1.DeleteOutboxDlqRowResponse
	(*PurgeOutboxDlqRowsRequest)(nil),       // 24: mediaservice.admin.v1.PurgeOutboxDlqRowsRequest
	(*PurgeOutboxDlqRowsResponse)(nil),      // 25: mediaservice.admin.v1.PurgeOutboxDlqRowsResponse
	(*InspectIdempotencyClaimRequest)(nil),  // 26: mediaservice.admin.v1.InspectIdempotencyClaimRequest
	(*IdempotencyClaim)(nil),                // 27: mediaservice.admin.v1.IdempotencyClaim
	(*InspectIdempotencyClaimResponse)(nil), // 28: mediaservice.admin.v1.InspectIdempotencyClaimResponse
	(*ResetIdempotencyClaimRequest)(nil),    // 29: mediaservice.admin.v1.ResetIdempotencyClaimRequest
	(*ResetIdempotencyClaimResponse)(nil),   // 30: mediaservice.admin.v1.ResetIdempotencyClaimResponse
	(*OverrideQuotaCapRequest)(nil),         // 31: mediaservice.admin.v1.OverrideQuotaCapRequest
	(*OverrideQuotaCapResponse)(nil),        // 32: mediaservice.admin.v1.OverrideQuotaCapResponse
	(*RotateWebhookSecretRequest)(nil),      // 33: mediaservice.admin.v1.RotateWebhookSecretRequest
	(*RotateWebhookSecretResponse)(nil),     // 34: mediaservice.admin.v1.RotateWebhookSecretResponse
	(*SuspendTenantRequest)(nil),            // 35: mediaservice.admin.v1.SuspendTenantRequest
	(*SuspendTenantResponse)(nil),           // 36: mediaservice.admin.v1.SuspendTenantResponse
	(*UnsuspendTenantRequest)(nil),          // 37: mediaservice.admin.v1.UnsuspendTenantRequest
	(*UnsuspendTenantResponse)(nil),         // 38: mediaservice.admin.v1.UnsuspendTenantResponse
	(*CancelWorkflowJobRequest)(nil),        // 39: mediaservice.admin.v1.CancelWorkflowJobRequest
	(*CancelWorkflowJobResponse)(nil),       // 40: mediaservice.admin.v1.CancelWorkflowJobResponse
	nil,                                     // 41: mediaservice.admin.v1.DLQMessage.MessageAttributesEntry
	nil,                                     // 42: mediaservice.admin.v1.DLQMessageInput.MessageAttributesEntry
	(*timestamppb.Timestamp)(nil),           // 43: google.protobuf.Timestamp
}
var file_mediaservice_admin_v1_admin_proto_depIdxs = []int32{
	0,  // 0: mediaservice.admin.v1.GetDLQStatusResponse.queues:type_name -> mediaservice.admin.v1.DLQQueue
	41, // 1: mediaservice.admin.v1.DLQMessage.message_attributes:type_name -> mediaservice.admin.v1.DLQMessage.MessageAttributesEntry
	4,  // 2: mediaservice.admin.v1.ListDLQMessagesResponse.messages:type_name -> mediaservice.admin.v1.DLQMessage
	42, // 3: mediaservice.admin.v1.DLQMessageInput.message_attributes:type_name -> mediaservice.admin.v1.DLQMessageInput.MessageAttributesEntry
	6,  // 4: mediaservice.admin.v1.ReplayDLQMessagesRequest.messages:type_name -> mediaservice.admin.v1.DLQMessageInput
	8,  // 5: mediaservice.admin.v1.DLQReplayResult.failure:type_name -> mediaservice.admin.v1.DLQReplayFailure
	9,  // 6: mediaservice.admin.v1.ReplayDLQMessagesResponse.results:type_name -> mediaservice.admin.v1.DLQReplayResult
	43, // 7: mediaservice.admin.v1.OutboxDLQRow.partition_ts:type_name -> google.protobuf.Timestamp
	43, // 8: mediaservice.admin.v1.OutboxDLQRow.first_failed_at:type_name -> google.protobuf.Timestamp
	43, // 9: mediaservice.admin.v1.OutboxDLQRow.last_failed_at:type_name -> google.protobuf.Timestamp
	15, // 10: mediaservice.admin.v1.ListOutboxDlqRowsResponse.rows:type_name -> mediaservice.admin.v1.OutboxDLQRow
	43, // 11: mediaservice.admin.v1.IdempotencyClaim.claimed_at:type_name -> google.protobuf.Timestamp
	43, // 12: mediaservice.admin.v1.IdempotencyClaim.completed_at:type_name -> google.protobuf.Timestamp
	43, // 13: mediaservice.admin.v1.IdempotencyClaim.ttl_at:type_name -> google.protobuf.Timestamp
	27, // 14: mediaservice.admin.v1.InspectIdempotencyClaimResponse.claim:type_name -> mediaservice.admin.v1.IdempotencyClaim
	1,  // 15: mediaservice.admin.v1.DLQAdminService.GetDLQStatus:input_type -> mediaservice.admin.v1.GetDLQStatusRequest
	3,  // 16: mediaservice.admin.v1.DLQAdminService.ListDLQMessages:input_type -> mediaservice.admin.v1.ListDLQMessagesRequest
	7,  // 17: mediaservice.admin.v1.DLQAdminService.ReplayDLQMessages:input_type -> mediaservice.admin.v1.ReplayDLQMessagesRequest
	11, // 18: mediaservice.admin.v1.DLQAdminService.DeleteDLQMessage:input_type -> mediaservice.admin.v1.DeleteDLQMessageRequest
	13, // 19: mediaservice.admin.v1.DLQAdminService.PurgeDLQ:input_type -> mediaservice.admin.v1.PurgeDLQRequest
	16, // 20: mediaservice.admin.v1.OutboxDLQAdminService.ListOutboxDlqRows:input_type -> mediaservice.admin.v1.ListOutboxDlqRowsRequest
	18, // 21: mediaservice.admin.v1.OutboxDLQAdminService.ReplayOutboxDlqRow:input_type -> mediaservice.admin.v1.ReplayOutboxDlqRowRequest
	20, // 22: mediaservice.admin.v1.OutboxDLQAdminService.AbandonOutboxDlqRow:input_type -> mediaservice.admin.v1.AbandonOutboxDlqRowRequest
	22, // 23: mediaservice.admin.v1.OutboxDLQAdminService.DeleteOutboxDlqRow:input_type -> mediaservice.admin.v1.DeleteOutboxDlqRowRequest
	24, // 24: mediaservice.admin.v1.OutboxDLQAdminService.PurgeOutboxDlqRows:input_type -> mediaservice.admin.v1.PurgeOutboxDlqRowsRequest
	26, // 25: mediaservice.admin.v1.IdempotencyAdminService.InspectIdempotencyClaim:input_type -> mediaservice.admin.v1.InspectIdempotencyClaimRequest
	29, // 26: mediaservice.admin.v1.IdempotencyAdminService.ResetIdempotencyClaim:input_type -> mediaservice.admin.v1.ResetIdempotencyClaimRequest
	31, // 27: mediaservice.admin.v1.QuotaAdminService.OverrideQuotaCap:input_type -> mediaservice.admin.v1.OverrideQuotaCapRequest
	33, // 28: mediaservice.admin.v1.WebhookAdminService.RotateWebhookSecret:input_type -> mediaservice.admin.v1.RotateWebhookSecretRequest
	35, // 29: mediaservice.admin.v1.TenantAdminService.SuspendTenant:input_type -> mediaservice.admin.v1.SuspendTenantRequest
	37, // 30: mediaservice.admin.v1.TenantAdminService.UnsuspendTenant:input_type -> mediaservice.admin.v1.UnsuspendTenantRequest
	39, // 31: mediaservice.admin.v1.WorkflowAdminService.CancelWorkflowJob:input_type -> mediaservice.admin.v1.CancelWorkflowJobRequest
	2,  // 32: mediaservice.admin.v1.DLQAdminService.GetDLQStatus:output_type -> mediaservice.admin.v1.GetDLQStatusResponse
	5,  // 33: mediaservice.admin.v1.DLQAdminService.ListDLQMessages:output_type -> mediaservice.admin.v1.ListDLQMessagesResponse
	10, // 34: mediaservice.admin.v1.DLQAdminService.ReplayDLQMessages:output_type -> mediaservice.admin.v1.ReplayDLQMessagesResponse
	12, // 35: mediaservice.admin.v1.DLQAdminService.DeleteDLQMessage:output_type -> mediaservice.admin.v1.DeleteDLQMessageResponse
	14, // 36: mediaservice.admin.v1.DLQAdminService.PurgeDLQ:output_type -> mediaservice.admin.v1.PurgeDLQResponse
	17, // 37: mediaservice.admin.v1.OutboxDLQAdminService.ListOutboxDlqRows:output_type -> mediaservice.admin.v1.ListOutboxDlqRowsResponse
	19, // 38: mediaservice.admin.v1.OutboxDLQAdminService.ReplayOutboxDlqRow:output_type -> mediaservice.admin.v1.ReplayOutboxDlqRowResponse
	21, // 39: mediaservice.admin.v1.OutboxDLQAdminService.AbandonOutboxDlqRow:output_type -> mediaservice.admin.v1.AbandonOutboxDlqRowResponse
	23, // 40: mediaservice.admin.v1.OutboxDLQAdminService.DeleteOutboxDlqRow:output_type -> mediaservice.admin.v1.DeleteOutboxDlqRowResponse
	25, // 41: mediaservice.admin.v1.OutboxDLQAdminService.PurgeOutboxDlqRows:output_type -> mediaservice.admin.v1.PurgeOutboxDlqRowsResponse
	28, // 42: mediaservice.admin.v1.IdempotencyAdminService.InspectIdempotencyClaim:output_type -> mediaservice.admin.v1.InspectIdempotencyClaimResponse
	30, // 43: mediaservice.admin.v1.IdempotencyAdminService.ResetIdempotencyClaim:output_type -> mediaservice.admin.v1.ResetIdempotencyClaimResponse
	32, // 44: mediaservice.admin.v1.QuotaAdminService.OverrideQuotaCap:output_type -> mediaservice.admin.v1.OverrideQuotaCapResponse
	34, // 45: mediaservice.admin.v1.WebhookAdminService.RotateWebhookSecret:output_type -> mediaservice.admin.v1.RotateWebhookSecretResponse
	36, // 46: mediaservice.admin.v1.TenantAdminService.SuspendTenant:output_type -> mediaservice.admin.v1.SuspendTenantResponse
	38, // 47: mediaservice.admin.v1.TenantAdminService.UnsuspendTenant:output_type -> mediaservice.admin.v1.UnsuspendTenantResponse
	40, // 48: mediaservice.admin.v1.WorkflowAdminService.CancelWorkflowJob:output_type -> mediaservice.admin.v1.CancelWorkflowJobResponse
	32, // [32:49] is the sub-list for method output_type
	15, // [15:32] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_mediaservice_admin_v1_admin_proto_init() }
func file_mediaservice_admin_v1_admin_proto_init() {
	if File_mediaservice_admin_v1_admin_proto != nil {
		return
	}
	file_mediaservice_admin_v1_admin_proto_msgTypes[4].OneofWrappers = []any{}
	file_mediaservice_admin_v1_admin_proto_msgTypes[9].OneofWrappers = []any{}
	file_mediaservice_admin_v1_admin_proto_msgTypes[15].OneofWrappers = []any{}
	file_mediaservice_admin_v1_admin_proto_msgTypes[16].OneofWrappers = []any{}
	file_mediaservice_admin_v1_admin_proto_msgTypes[17].OneofWrappers = []any{}
	file_mediaservice_admin_v1_admin_proto_msgTypes[27].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mediaservice_admin_v1_admin_proto_rawDesc), len(file_mediaservice_admin_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_mediaservice_admin_v1_admin_proto_goTypes,
		DependencyIndexes: file_mediaservice_admin_v1_admin_proto_depIdxs,
		MessageInfos:      file_mediaservice_admin_v1_admin_proto_msgTypes,
	}.Build()
	File_mediaservice_admin_v1_admin_proto = out.File
	file_mediaservice_admin_v1_admin_proto_goTypes = nil
	file_mediaservice_admin_v1_admin_proto_depIdxs = nil
}
