// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mediaservice/shorturl/v1/shorturl.proto

package shorturlv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/shorturl/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ShortURLServiceName is the fully-qualified name of the ShortURLService service.
	ShortURLServiceName = "mediaservice.shorturl.v1.ShortURLService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ShortURLServiceCreateProcedure is the fully-qualified name of the ShortURLService's Create RPC.
	ShortURLServiceCreateProcedure = "/mediaservice.shorturl.v1.ShortURLService/Create"
	// ShortURLServiceListProcedure is the fully-qualified name of the ShortURLService's List RPC.
	ShortURLServiceListProcedure = "/mediaservice.shorturl.v1.ShortURLService/List"
	// ShortURLServiceRevokeProcedure is the fully-qualified name of the ShortURLService's Revoke RPC.
	ShortURLServiceRevokeProcedure = "/mediaservice.shorturl.v1.ShortURLService/Revoke"
)

// ShortURLServiceClient is a client for the mediaservice.shorturl.v1.ShortURLService service.
type ShortURLServiceClient interface {
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	Revoke(context.Context, *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error)
}

// NewShortURLServiceClient constructs a client for the mediaservice.shorturl.v1.ShortURLService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewShortURLServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ShortURLServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	shortURLServiceMethods := v1.File_mediaservice_shorturl_v1_shorturl_proto.Services().ByName("ShortURLService").Methods()
	return &shortURLServiceClient{
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+ShortURLServiceCreateProcedure,
			connect.WithSchema(shortURLServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+ShortURLServiceListProcedure,
			connect.WithSchema(shortURLServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		revoke: connect.NewClient[v1.RevokeRequest, v1.RevokeResponse](
			httpClient,
			baseURL+ShortURLServiceRevokeProcedure,
			connect.WithSchema(shortURLServiceMethods.ByName("Revoke")),
			connect.WithClientOptions(opts...),
		),
	}
}

// shortURLServiceClient implements ShortURLServiceClient.
type shortURLServiceClient struct {
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
	list   *connect.Client[v1.ListRequest, v1.ListResponse]
	revoke *connect.Client[v1.RevokeRequest, v1.RevokeResponse]
}

// Create calls mediaservice.shorturl.v1.ShortURLService.Create.
func (c *shortURLServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// List calls mediaservice.shorturl.v1.ShortURLService.List.
func (c *shortURLServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Revoke calls mediaservice.shorturl.v1.ShortURLService.Revoke.
func (c *shortURLServiceClient) Revoke(ctx context.Context, req *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error) {
	return c.revoke.CallUnary(ctx, req)
}

// ShortURLServiceHandler is an implementation of the mediaservice.shorturl.v1.ShortURLService
// service.
type ShortURLServiceHandler interface {
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	Revoke(context.Context, *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error)
}

// NewShortURLServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewShortURLServiceHandler(svc ShortURLServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	shortURLServiceMethods := v1.File_mediaservice_shorturl_v1_shorturl_proto.Services().ByName("ShortURLService").Methods()
	shortURLServiceCreateHandler := connect.NewUnaryHandler(
		ShortURLServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(shortURLServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	shortURLServiceListHandler := connect.NewUnaryHandler(
		ShortURLServiceListProcedure,
		svc.List,
		connect.WithSchema(shortURLServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	shortURLServiceRevokeHandler := connect.NewUnaryHandler(
		ShortURLServiceRevokeProcedure,
		svc.Revoke,
		connect.WithSchema(shortURLServiceMethods.ByName("Revoke")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mediaservice.shorturl.v1.ShortURLService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ShortURLServiceCreateProcedure:
			shortURLServiceCreateHandler.ServeHTTP(w, r)
		case ShortURLServiceListProcedure:
			shortURLServiceListHandler.ServeHTTP(w, r)
		case ShortURLServiceRevokeProcedure:
			shortURLServiceRevokeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedShortURLServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedShortURLServiceHandler struct{}

func (UnimplementedShortURLServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.shorturl.v1.ShortURLService.Create is not implemented"))
}

func (UnimplementedShortURLServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.shorturl.v1.ShortURLService.List is not implemented"))
}

func (UnimplementedShortURLServiceHandler) Revoke(context.Context, *connect.Request[v1.RevokeRequest]) (*connect.Response[v1.RevokeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.shorturl.v1.ShortURLService.Revoke is not implemented"))
}
