// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: mediaservice/analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityViewCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ViewCount     int32                  `protobuf:"varint,4,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	Rank          int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	Deleted       *bool                  `protobuf:"varint,6,opt,name=deleted,proto3,oneof" json:"deleted,omitempty"`
	DeletedAt     *string                `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityViewCount) Reset() {
	*x = EntityViewCount{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityViewCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityViewCount) ProtoMessage() {}

func (x *EntityViewCount) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityViewCount.ProtoReflect.Descriptor instead.
func (*EntityViewCount) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *EntityViewCount) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *EntityViewCount) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityViewCount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntityViewCount) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *EntityViewCount) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *EntityViewCount) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *EntityViewCount) GetDeletedAt() string {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return ""
}

type ViewStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Today         int32                  `protobuf:"varint,4,opt,name=today,proto3" json:"today,omitempty"`
	ThisWeek      int32                  `protobuf:"varint,5,opt,name=this_week,json=thisWeek,proto3" json:"this_week,omitempty"`
	ThisMonth     int32                  `protobuf:"varint,6,opt,name=this_month,json=thisMonth,proto3" json:"this_month,omitempty"`
	ThisYear      int32                  `protobuf:"varint,7,opt,name=this_year,json=thisYear,proto3" json:"this_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewStats) Reset() {
	*x = ViewStats{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewStats) ProtoMessage() {}

func (x *ViewStats) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewStats.ProtoReflect.Descriptor instead.
func (*ViewStats) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *ViewStats) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ViewStats) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ViewStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ViewStats) GetToday() int32 {
	if x != nil {
		return x.Today
	}
	return 0
}

func (x *ViewStats) GetThisWeek() int32 {
	if x != nil {
		return x.ThisWeek
	}
	return 0
}

func (x *ViewStats) GetThisMonth() int32 {
	if x != nil {
		return x.ThisMonth
	}
	return 0
}

func (x *ViewStats) GetThisYear() int32 {
	if x != nil {
		return x.ThisYear
	}
	return 0
}

type FormatUsageStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Usage         map[string]int32       `protobuf:"bytes,2,rep,name=usage,proto3" json:"usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatUsageStats) Reset() {
	*x = FormatUsageStats{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatUsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatUsageStats) ProtoMessage() {}

func (x *FormatUsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatUsageStats.ProtoReflect.Descriptor instead.
func (*FormatUsageStats) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *FormatUsageStats) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *FormatUsageStats) GetUsage() map[string]int32 {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *FormatUsageStats) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DownloadStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Period         string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	TotalDownloads int32                  `protobuf:"varint,2,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	ByFormat       map[string]int32       `protobuf:"bytes,3,rep,name=by_format,json=byFormat,proto3" json:"by_format,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByDay          map[string]int32       `protobuf:"bytes,4,rep,name=by_day,json=byDay,proto3" json:"by_day,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DownloadStats) Reset() {
	*x = DownloadStats{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadStats) ProtoMessage() {}

func (x *DownloadStats) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadStats.ProtoReflect.Descriptor instead.
func (*DownloadStats) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadStats) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *DownloadStats) GetTotalDownloads() int32 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *DownloadStats) GetByFormat() map[string]int32 {
	if x != nil {
		return x.ByFormat
	}
	return nil
}

func (x *DownloadStats) GetByDay() map[string]int32 {
	if x != nil {
		return x.ByDay
	}
	return nil
}

type AnalyticsSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalViews     int32                  `protobuf:"varint,1,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalDownloads int32                  `protobuf:"varint,2,opt,name=total_downloads,json=totalDownloads,proto3" json:"total_downloads,omitempty"`
	ViewsToday     int32                  `protobuf:"varint,3,opt,name=views_today,json=viewsToday,proto3" json:"views_today,omitempty"`
	DownloadsToday int32                  `protobuf:"varint,4,opt,name=downloads_today,json=downloadsToday,proto3" json:"downloads_today,omitempty"`
	TopMediaToday  []*EntityViewCount     `protobuf:"bytes,5,rep,name=top_media_today,json=topMediaToday,proto3" json:"top_media_today,omitempty"`
	// Bounded rolling top-media view so DDB scans never touch data older than one year.
	TopMediaRolling_12M []*EntityViewCount `protobuf:"bytes,6,rep,name=top_media_rolling_12m,json=topMediaRolling12m,proto3" json:"top_media_rolling_12m,omitempty"`
	FormatUsage         map[string]int32   `protobuf:"bytes,7,rep,name=format_usage,json=formatUsage,proto3" json:"format_usage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AnalyticsSummary) Reset() {
	*x = AnalyticsSummary{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyticsSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyticsSummary) ProtoMessage() {}

func (x *AnalyticsSummary) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyticsSummary.ProtoReflect.Descriptor instead.
func (*AnalyticsSummary) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyticsSummary) GetTotalViews() int32 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *AnalyticsSummary) GetTotalDownloads() int32 {
	if x != nil {
		return x.TotalDownloads
	}
	return 0
}

func (x *AnalyticsSummary) GetViewsToday() int32 {
	if x != nil {
		return x.ViewsToday
	}
	return 0
}

func (x *AnalyticsSummary) GetDownloadsToday() int32 {
	if x != nil {
		return x.DownloadsToday
	}
	return 0
}

func (x *AnalyticsSummary) GetTopMediaToday() []*EntityViewCount {
	if x != nil {
		return x.TopMediaToday
	}
	return nil
}

func (x *AnalyticsSummary) GetTopMediaRolling_12M() []*EntityViewCount {
	if x != nil {
		return x.TopMediaRolling_12M
	}
	return nil
}

func (x *AnalyticsSummary) GetFormatUsage() map[string]int32 {
	if x != nil {
		return x.FormatUsage
	}
	return nil
}

type GetTopMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopMediaRequest) Reset() {
	*x = GetTopMediaRequest{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopMediaRequest) ProtoMessage() {}

func (x *GetTopMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopMediaRequest.ProtoReflect.Descriptor instead.
func (*GetTopMediaRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopMediaRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetTopMediaRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopMediaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EntityViewCount     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopMediaResponse) Reset() {
	*x = GetTopMediaResponse{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopMediaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopMediaResponse) ProtoMessage() {}

func (x *GetTopMediaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopMediaResponse.ProtoReflect.Descriptor instead.
func (*GetTopMediaResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopMediaResponse) GetItems() []*EntityViewCount {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetMediaViewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       string                 `protobuf:"bytes,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaViewsRequest) Reset() {
	*x = GetMediaViewsRequest{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaViewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaViewsRequest) ProtoMessage() {}

func (x *GetMediaViewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaViewsRequest.ProtoReflect.Descriptor instead.
func (*GetMediaViewsRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetMediaViewsRequest) GetMediaId() string {
	if x != nil {
		return x.MediaId
	}
	return ""
}

type GetMediaViewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *ViewStats             `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaViewsResponse) Reset() {
	*x = GetMediaViewsResponse{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaViewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaViewsResponse) ProtoMessage() {}

func (x *GetMediaViewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaViewsResponse.ProtoReflect.Descriptor instead.
func (*GetMediaViewsResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetMediaViewsResponse) GetStats() *ViewStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetFormatUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormatUsageRequest) Reset() {
	*x = GetFormatUsageRequest{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormatUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormatUsageRequest) ProtoMessage() {}

func (x *GetFormatUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormatUsageRequest.ProtoReflect.Descriptor instead.
func (*GetFormatUsageRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetFormatUsageRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetFormatUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *FormatUsageStats      `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFormatUsageResponse) Reset() {
	*x = GetFormatUsageResponse{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFormatUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFormatUsageResponse) ProtoMessage() {}

func (x *GetFormatUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFormatUsageResponse.ProtoReflect.Descriptor instead.
func (*GetFormatUsageResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *GetFormatUsageResponse) GetStats() *FormatUsageStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetDownloadStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        string                 `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadStatsRequest) Reset() {
	*x = GetDownloadStatsRequest{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadStatsRequest) ProtoMessage() {}

func (x *GetDownloadStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadStatsRequest.ProtoReflect.Descriptor instead.
func (*GetDownloadStatsRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetDownloadStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetDownloadStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *DownloadStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDownloadStatsResponse) Reset() {
	*x = GetDownloadStatsResponse{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDownloadStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDownloadStatsResponse) ProtoMessage() {}

func (x *GetDownloadStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDownloadStatsResponse.ProtoReflect.Descriptor instead.
func (*GetDownloadStatsResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *GetDownloadStatsResponse) GetStats() *DownloadStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetAnalyticsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsSummaryRequest) Reset() {
	*x = GetAnalyticsSummaryRequest{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsSummaryRequest) ProtoMessage() {}

func (x *GetAnalyticsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAnalyticsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{13}
}

type GetAnalyticsSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *AnalyticsSummary      `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalyticsSummaryResponse) Reset() {
	*x = GetAnalyticsSummaryResponse{}
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalyticsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalyticsSummaryResponse) ProtoMessage() {}

func (x *GetAnalyticsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mediaservice_analytics_v1_analytics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalyticsSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAnalyticsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP(), []int{14}
}

func (x *GetAnalyticsSummaryResponse) GetSummary() *AnalyticsSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

var File_mediaservice_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_mediaservice_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	")mediaservice/analytics/v1/analytics.proto\x12\x19mediaservice.analytics.v1\"\xf4\x01\n" +
	"\x0fEntityViewCount\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"view_count\x18\x04 \x01(\x05R\tviewCount\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\x12\x1d\n" +
	"\adeleted\x18\x06 \x01(\bH\x00R\adeleted\x88\x01\x01\x12\"\n" +
	"\n" +
	"deleted_at\x18\a \x01(\tH\x01R\tdeletedAt\x88\x01\x01B\n" +
	"\n" +
	"\b_deletedB\r\n" +
	"\v_deleted_at\"\xce\x01\n" +
	"\tViewStats\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x14\n" +
	"\x05today\x18\x04 \x01(\x05R\x05today\x12\x1b\n" +
	"\tthis_week\x18\x05 \x01(\x05R\bthisWeek\x12\x1d\n" +
	"\n" +
	"this_month\x18\x06 \x01(\x05R\tthisMonth\x12\x1b\n" +
	"\tthis_year\x18\a \x01(\x05R\bthisYear\"\xc8\x01\n" +
	"\x10FormatUsageStats\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12L\n" +
	"\x05usage\x18\x02 \x03(\v26.mediaservice.analytics.v1.FormatUsageStats.UsageEntryR\x05usage\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x1a8\n" +
	"\n" +
	"UsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xe8\x02\n" +
	"\rDownloadStats\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12'\n" +
	"\x0ftotal_downloads\x18\x02 \x01(\x05R\x0etotalDownloads\x12S\n" +
	"\tby_format\x18\x03 \x03(\v26.mediaservice.analytics.v1.DownloadStats.ByFormatEntryR\bbyFormat\x12J\n" +
	"\x06by_day\x18\x04 \x03(\v23.mediaservice.analytics.v1.DownloadStats.ByDayEntryR\x05byDay\x1a;\n" +
	"\rByFormatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"ByDayEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xfa\x03\n" +
	"\x10AnalyticsSummary\x12\x1f\n" +
	"\vtotal_views\x18\x01 \x01(\x05R\n" +
	"totalViews\x12'\n" +
	"\x0ftotal_downloads\x18\x02 \x01(\x05R\x0etotalDownloads\x12\x1f\n" +
	"\vviews_today\x18\x03 \x01(\x05R\n" +
	"viewsToday\x12'\n" +
	"\x0fdownloads_today\x18\x04 \x01(\x05R\x0edownloadsToday\x12R\n" +
	"\x0ftop_media_today\x18\x05 \x03(\v2*.mediaservice.analytics.v1.EntityViewCountR\rtopMediaToday\x12]\n" +
	"\x15top_media_rolling_12m\x18\x06 \x03(\v2*.mediaservice.analytics.v1.EntityViewCountR\x12topMediaRolling12m\x12_\n" +
	"\fformat_usage\x18\a \x03(\v2<.mediaservice.analytics.v1.AnalyticsSummary.FormatUsageEntryR\vformatUsage\x1a>\n" +
	"\x10FormatUsageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"B\n" +
	"\x12GetTopMediaRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"W\n" +
	"\x13GetTopMediaResponse\x12@\n" +
	"\x05items\x18\x01 \x03(\v2*.mediaservice.analytics.v1.EntityViewCountR\x05items\"1\n" +
	"\x14GetMediaViewsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\tR\amediaId\"S\n" +
	"\x15GetMediaViewsResponse\x12:\n" +
	"\x05stats\x18\x01 \x01(\v2$.mediaservice.analytics.v1.ViewStatsR\x05stats\"/\n" +
	"\x15GetFormatUsageRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"[\n" +
	"\x16GetFormatUsageResponse\x12A\n" +
	"\x05stats\x18\x01 \x01(\v2+.mediaservice.analytics.v1.FormatUsageStatsR\x05stats\"1\n" +
	"\x17GetDownloadStatsRequest\x12\x16\n" +
	"\x06period\x18\x01 \x01(\tR\x06period\"Z\n" +
	"\x18GetDownloadStatsResponse\x12>\n" +
	"\x05stats\x18\x01 \x01(\v2(.mediaservice.analytics.v1.DownloadStatsR\x05stats\"\x1c\n" +
	"\x1aGetAnalyticsSummaryRequest\"d\n" +
	"\x1bGetAnalyticsSummaryResponse\x12E\n" +
	"\asummary\x18\x01 \x01(\v2+.mediaservice.analytics.v1.AnalyticsSummaryR\asummary2\xef\x04\n" +
	"\x10AnalyticsService\x12l\n" +
	"\vGetTopMedia\x12-.mediaservice.analytics.v1.GetTopMediaRequest\x1a..mediaservice.analytics.v1.GetTopMediaResponse\x12r\n" +
	"\rGetMediaViews\x12/.mediaservice.analytics.v1.GetMediaViewsRequest\x1a0.mediaservice.analytics.v1.GetMediaViewsResponse\x12u\n" +
	"\x0eGetFormatUsage\x120.mediaservice.analytics.v1.GetFormatUsageRequest\x1a1.mediaservice.analytics.v1.GetFormatUsageResponse\x12{\n" +
	"\x10GetDownloadStats\x122.mediaservice.analytics.v1.GetDownloadStatsRequest\x1a3.mediaservice.analytics.v1.GetDownloadStatsResponse\x12\x84\x01\n" +
	"\x13GetAnalyticsSummary\x125.mediaservice.analytics.v1.GetAnalyticsSummaryRequest\x1a6.mediaservice.analytics.v1.GetAnalyticsSummaryResponseB\x9e\x02\n" +
	"\x1dcom.mediaservice.analytics.v1B\x0eAnalyticsProtoP\x01Zggithub.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/analytics/v1;analyticsv1\xa2\x02\x03MAX\xaa\x02\x19Mediaservice.Analytics.V1\xca\x02\x19Mediaservice\\Analytics\\V1\xe2\x02%Mediaservice\\Analytics\\V1\\GPBMetadata\xea\x02\x1bMediaservice::Analytics::V1b\x06proto3"

var (
	file_mediaservice_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_mediaservice_analytics_v1_analytics_proto_rawDescData []byte
)

func file_mediaservice_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_mediaservice_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_mediaservice_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mediaservice_analytics_v1_analytics_proto_rawDesc), len(file_mediaservice_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_mediaservice_analytics_v1_analytics_proto_rawDescData
}

var file_mediaservice_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_mediaservice_analytics_v1_analytics_proto_goTypes = []any{
	(*EntityViewCount)(nil),             // 0: mediaservice.analytics.v1.EntityViewCount
	(*ViewStats)(nil),                   // 1: mediaservice.analytics.v1.ViewStats
	(*FormatUsageStats)(nil),            // 2: mediaservice.analytics.v1.FormatUsageStats
	(*DownloadStats)(nil),               // 3: mediaservice.analytics.v1.DownloadStats
	(*AnalyticsSummary)(nil),            // 4: mediaservice.analytics.v1.AnalyticsSummary
	(*GetTopMediaRequest)(nil),          // 5: mediaservice.analytics.v1.GetTopMediaRequest
	(*GetTopMediaResponse)(nil),         // 6: mediaservice.analytics.v1.GetTopMediaResponse
	(*GetMediaViewsRequest)(nil),        // 7: mediaservice.analytics.v1.GetMediaViewsRequest
	(*GetMediaViewsResponse)(nil),       // 8: mediaservice.analytics.v1.GetMediaViewsResponse
	(*GetFormatUsageRequest)(nil),       // 9: mediaservice.analytics.v1.GetFormatUsageRequest
	(*GetFormatUsageResponse)(nil),      // 10: mediaservice.analytics.v1.GetFormatUsageResponse
	(*GetDownloadStatsRequest)(nil),     // 11: mediaservice.analytics.v1.GetDownloadStatsRequest
	(*GetDownloadStatsResponse)(nil),    // 12: mediaservice.analytics.v1.GetDownloadStatsResponse
	(*GetAnalyticsSummaryRequest)(nil),  // 13: mediaservice.analytics.v1.GetAnalyticsSummaryRequest
	(*GetAnalyticsSummaryResponse)(nil), // 14: mediaservice.analytics.v1.GetAnalyticsSummaryResponse
	nil,                                 // 15: mediaservice.analytics.v1.FormatUsageStats.UsageEntry
	nil,                                 // 16: mediaservice.analytics.v1.DownloadStats.ByFormatEntry
	nil,                                 // 17: mediaservice.analytics.v1.DownloadStats.ByDayEntry
	nil,                                 // 18: mediaservice.analytics.v1.AnalyticsSummary.FormatUsageEntry
}
var file_mediaservice_analytics_v1_analytics_proto_depIdxs = []int32{
	15, // 0: mediaservice.analytics.v1.FormatUsageStats.usage:type_name -> mediaservice.analytics.v1.FormatUsageStats.UsageEntry
	16, // 1: mediaservice.analytics.v1.DownloadStats.by_format:type_name -> mediaservice.analytics.v1.DownloadStats.ByFormatEntry
	17, // 2: mediaservice.analytics.v1.DownloadStats.by_day:type_name -> mediaservice.analytics.v1.DownloadStats.ByDayEntry
	0,  // 3: mediaservice.analytics.v1.AnalyticsSummary.top_media_today:type_name -> mediaservice.analytics.v1.EntityViewCount
	0,  // 4: mediaservice.analytics.v1.AnalyticsSummary.top_media_rolling_12m:type_name -> mediaservice.analytics.v1.EntityViewCount
	18, // 5: mediaservice.analytics.v1.AnalyticsSummary.format_usage:type_name -> mediaservice.analytics.v1.AnalyticsSummary.FormatUsageEntry
	0,  // 6: mediaservice.analytics.v1.GetTopMediaResponse.items:type_name -> mediaservice.analytics.v1.EntityViewCount
	1,  // 7: mediaservice.analytics.v1.GetMediaViewsResponse.stats:type_name -> mediaservice.analytics.v1.ViewStats
	2,  // 8: mediaservice.analytics.v1.GetFormatUsageResponse.stats:type_name -> mediaservice.analytics.v1.FormatUsageStats
	3,  // 9: mediaservice.analytics.v1.GetDownloadStatsResponse.stats:type_name -> mediaservice.analytics.v1.DownloadStats
	4,  // 10: mediaservice.analytics.v1.GetAnalyticsSummaryResponse.summary:type_name -> mediaservice.analytics.v1.AnalyticsSummary
	5,  // 11: mediaservice.analytics.v1.AnalyticsService.GetTopMedia:input_type -> mediaservice.analytics.v1.GetTopMediaRequest
	7,  // 12: mediaservice.analytics.v1.AnalyticsService.GetMediaViews:input_type -> mediaservice.analytics.v1.GetMediaViewsRequest
	9,  // 13: mediaservice.analytics.v1.AnalyticsService.GetFormatUsage:input_type -> mediaservice.analytics.v1.GetFormatUsageRequest
	11, // 14: mediaservice.analytics.v1.AnalyticsService.GetDownloadStats:input_type -> mediaservice.analytics.v1.GetDownloadStatsRequest
	13, // 15: mediaservice.analytics.v1.AnalyticsService.GetAnalyticsSummary:input_type -> mediaservice.analytics.v1.GetAnalyticsSummaryRequest
	6,  // 16: mediaservice.analytics.v1.AnalyticsService.GetTopMedia:output_type -> mediaservice.analytics.v1.GetTopMediaResponse
	8,  // 17: mediaservice.analytics.v1.AnalyticsService.GetMediaViews:output_type -> mediaservice.analytics.v1.GetMediaViewsResponse
	10, // 18: mediaservice.analytics.v1.AnalyticsService.GetFormatUsage:output_type -> mediaservice.analytics.v1.GetFormatUsageResponse
	12, // 19: mediaservice.analytics.v1.AnalyticsService.GetDownloadStats:output_type -> mediaservice.analytics.v1.GetDownloadStatsResponse
	14, // 20: mediaservice.analytics.v1.AnalyticsService.GetAnalyticsSummary:output_type -> mediaservice.analytics.v1.GetAnalyticsSummaryResponse
	16, // [16:21] is the sub-list for method output_type
	11, // [11:16] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_mediaservice_analytics_v1_analytics_proto_init() }
func file_mediaservice_analytics_v1_analytics_proto_init() {
	if File_mediaservice_analytics_v1_analytics_proto != nil {
		return
	}
	file_mediaservice_analytics_v1_analytics_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mediaservice_analytics_v1_analytics_proto_rawDesc), len(file_mediaservice_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaservice_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_mediaservice_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_mediaservice_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_mediaservice_analytics_v1_analytics_proto = out.File
	file_mediaservice_analytics_v1_analytics_proto_goTypes = nil
	file_mediaservice_analytics_v1_analytics_proto_depIdxs = nil
}
