// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: mediaservice/analytics/v1/analytics.proto

package analyticsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/dtszwai/media-processing-service/backend/pkg/contracts/mediaservice/analytics/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AnalyticsServiceName is the fully-qualified name of the AnalyticsService service.
	AnalyticsServiceName = "mediaservice.analytics.v1.AnalyticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AnalyticsServiceGetTopMediaProcedure is the fully-qualified name of the AnalyticsService's
	// GetTopMedia RPC.
	AnalyticsServiceGetTopMediaProcedure = "/mediaservice.analytics.v1.AnalyticsService/GetTopMedia"
	// AnalyticsServiceGetMediaViewsProcedure is the fully-qualified name of the AnalyticsService's
	// GetMediaViews RPC.
	AnalyticsServiceGetMediaViewsProcedure = "/mediaservice.analytics.v1.AnalyticsService/GetMediaViews"
	// AnalyticsServiceGetFormatUsageProcedure is the fully-qualified name of the AnalyticsService's
	// GetFormatUsage RPC.
	AnalyticsServiceGetFormatUsageProcedure = "/mediaservice.analytics.v1.AnalyticsService/GetFormatUsage"
	// AnalyticsServiceGetDownloadStatsProcedure is the fully-qualified name of the AnalyticsService's
	// GetDownloadStats RPC.
	AnalyticsServiceGetDownloadStatsProcedure = "/mediaservice.analytics.v1.AnalyticsService/GetDownloadStats"
	// AnalyticsServiceGetAnalyticsSummaryProcedure is the fully-qualified name of the
	// AnalyticsService's GetAnalyticsSummary RPC.
	AnalyticsServiceGetAnalyticsSummaryProcedure = "/mediaservice.analytics.v1.AnalyticsService/GetAnalyticsSummary"
)

// AnalyticsServiceClient is a client for the mediaservice.analytics.v1.AnalyticsService service.
type AnalyticsServiceClient interface {
	GetTopMedia(context.Context, *connect.Request[v1.GetTopMediaRequest]) (*connect.Response[v1.GetTopMediaResponse], error)
	GetMediaViews(context.Context, *connect.Request[v1.GetMediaViewsRequest]) (*connect.Response[v1.GetMediaViewsResponse], error)
	GetFormatUsage(context.Context, *connect.Request[v1.GetFormatUsageRequest]) (*connect.Response[v1.GetFormatUsageResponse], error)
	GetDownloadStats(context.Context, *connect.Request[v1.GetDownloadStatsRequest]) (*connect.Response[v1.GetDownloadStatsResponse], error)
	GetAnalyticsSummary(context.Context, *connect.Request[v1.GetAnalyticsSummaryRequest]) (*connect.Response[v1.GetAnalyticsSummaryResponse], error)
}

// NewAnalyticsServiceClient constructs a client for the mediaservice.analytics.v1.AnalyticsService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAnalyticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AnalyticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	analyticsServiceMethods := v1.File_mediaservice_analytics_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	return &analyticsServiceClient{
		getTopMedia: connect.NewClient[v1.GetTopMediaRequest, v1.GetTopMediaResponse](
			httpClient,
			baseURL+AnalyticsServiceGetTopMediaProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetTopMedia")),
			connect.WithClientOptions(opts...),
		),
		getMediaViews: connect.NewClient[v1.GetMediaViewsRequest, v1.GetMediaViewsResponse](
			httpClient,
			baseURL+AnalyticsServiceGetMediaViewsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetMediaViews")),
			connect.WithClientOptions(opts...),
		),
		getFormatUsage: connect.NewClient[v1.GetFormatUsageRequest, v1.GetFormatUsageResponse](
			httpClient,
			baseURL+AnalyticsServiceGetFormatUsageProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetFormatUsage")),
			connect.WithClientOptions(opts...),
		),
		getDownloadStats: connect.NewClient[v1.GetDownloadStatsRequest, v1.GetDownloadStatsResponse](
			httpClient,
			baseURL+AnalyticsServiceGetDownloadStatsProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetDownloadStats")),
			connect.WithClientOptions(opts...),
		),
		getAnalyticsSummary: connect.NewClient[v1.GetAnalyticsSummaryRequest, v1.GetAnalyticsSummaryResponse](
			httpClient,
			baseURL+AnalyticsServiceGetAnalyticsSummaryProcedure,
			connect.WithSchema(analyticsServiceMethods.ByName("GetAnalyticsSummary")),
			connect.WithClientOptions(opts...),
		),
	}
}

// analyticsServiceClient implements AnalyticsServiceClient.
type analyticsServiceClient struct {
	getTopMedia         *connect.Client[v1.GetTopMediaRequest, v1.GetTopMediaResponse]
	getMediaViews       *connect.Client[v1.GetMediaViewsRequest, v1.GetMediaViewsResponse]
	getFormatUsage      *connect.Client[v1.GetFormatUsageRequest, v1.GetFormatUsageResponse]
	getDownloadStats    *connect.Client[v1.GetDownloadStatsRequest, v1.GetDownloadStatsResponse]
	getAnalyticsSummary *connect.Client[v1.GetAnalyticsSummaryRequest, v1.GetAnalyticsSummaryResponse]
}

// GetTopMedia calls mediaservice.analytics.v1.AnalyticsService.GetTopMedia.
func (c *analyticsServiceClient) GetTopMedia(ctx context.Context, req *connect.Request[v1.GetTopMediaRequest]) (*connect.Response[v1.GetTopMediaResponse], error) {
	return c.getTopMedia.CallUnary(ctx, req)
}

// GetMediaViews calls mediaservice.analytics.v1.AnalyticsService.GetMediaViews.
func (c *analyticsServiceClient) GetMediaViews(ctx context.Context, req *connect.Request[v1.GetMediaViewsRequest]) (*connect.Response[v1.GetMediaViewsResponse], error) {
	return c.getMediaViews.CallUnary(ctx, req)
}

// GetFormatUsage calls mediaservice.analytics.v1.AnalyticsService.GetFormatUsage.
func (c *analyticsServiceClient) GetFormatUsage(ctx context.Context, req *connect.Request[v1.GetFormatUsageRequest]) (*connect.Response[v1.GetFormatUsageResponse], error) {
	return c.getFormatUsage.CallUnary(ctx, req)
}

// GetDownloadStats calls mediaservice.analytics.v1.AnalyticsService.GetDownloadStats.
func (c *analyticsServiceClient) GetDownloadStats(ctx context.Context, req *connect.Request[v1.GetDownloadStatsRequest]) (*connect.Response[v1.GetDownloadStatsResponse], error) {
	return c.getDownloadStats.CallUnary(ctx, req)
}

// GetAnalyticsSummary calls mediaservice.analytics.v1.AnalyticsService.GetAnalyticsSummary.
func (c *analyticsServiceClient) GetAnalyticsSummary(ctx context.Context, req *connect.Request[v1.GetAnalyticsSummaryRequest]) (*connect.Response[v1.GetAnalyticsSummaryResponse], error) {
	return c.getAnalyticsSummary.CallUnary(ctx, req)
}

// AnalyticsServiceHandler is an implementation of the mediaservice.analytics.v1.AnalyticsService
// service.
type AnalyticsServiceHandler interface {
	GetTopMedia(context.Context, *connect.Request[v1.GetTopMediaRequest]) (*connect.Response[v1.GetTopMediaResponse], error)
	GetMediaViews(context.Context, *connect.Request[v1.GetMediaViewsRequest]) (*connect.Response[v1.GetMediaViewsResponse], error)
	GetFormatUsage(context.Context, *connect.Request[v1.GetFormatUsageRequest]) (*connect.Response[v1.GetFormatUsageResponse], error)
	GetDownloadStats(context.Context, *connect.Request[v1.GetDownloadStatsRequest]) (*connect.Response[v1.GetDownloadStatsResponse], error)
	GetAnalyticsSummary(context.Context, *connect.Request[v1.GetAnalyticsSummaryRequest]) (*connect.Response[v1.GetAnalyticsSummaryResponse], error)
}

// NewAnalyticsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAnalyticsServiceHandler(svc AnalyticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	analyticsServiceMethods := v1.File_mediaservice_analytics_v1_analytics_proto.Services().ByName("AnalyticsService").Methods()
	analyticsServiceGetTopMediaHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetTopMediaProcedure,
		svc.GetTopMedia,
		connect.WithSchema(analyticsServiceMethods.ByName("GetTopMedia")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetMediaViewsHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetMediaViewsProcedure,
		svc.GetMediaViews,
		connect.WithSchema(analyticsServiceMethods.ByName("GetMediaViews")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetFormatUsageHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetFormatUsageProcedure,
		svc.GetFormatUsage,
		connect.WithSchema(analyticsServiceMethods.ByName("GetFormatUsage")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetDownloadStatsHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetDownloadStatsProcedure,
		svc.GetDownloadStats,
		connect.WithSchema(analyticsServiceMethods.ByName("GetDownloadStats")),
		connect.WithHandlerOptions(opts...),
	)
	analyticsServiceGetAnalyticsSummaryHandler := connect.NewUnaryHandler(
		AnalyticsServiceGetAnalyticsSummaryProcedure,
		svc.GetAnalyticsSummary,
		connect.WithSchema(analyticsServiceMethods.ByName("GetAnalyticsSummary")),
		connect.WithHandlerOptions(opts...),
	)
	return "/mediaservice.analytics.v1.AnalyticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AnalyticsServiceGetTopMediaProcedure:
			analyticsServiceGetTopMediaHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetMediaViewsProcedure:
			analyticsServiceGetMediaViewsHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetFormatUsageProcedure:
			analyticsServiceGetFormatUsageHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetDownloadStatsProcedure:
			analyticsServiceGetDownloadStatsHandler.ServeHTTP(w, r)
		case AnalyticsServiceGetAnalyticsSummaryProcedure:
			analyticsServiceGetAnalyticsSummaryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAnalyticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAnalyticsServiceHandler struct{}

func (UnimplementedAnalyticsServiceHandler) GetTopMedia(context.Context, *connect.Request[v1.GetTopMediaRequest]) (*connect.Response[v1.GetTopMediaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.analytics.v1.AnalyticsService.GetTopMedia is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetMediaViews(context.Context, *connect.Request[v1.GetMediaViewsRequest]) (*connect.Response[v1.GetMediaViewsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.analytics.v1.AnalyticsService.GetMediaViews is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetFormatUsage(context.Context, *connect.Request[v1.GetFormatUsageRequest]) (*connect.Response[v1.GetFormatUsageResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.analytics.v1.AnalyticsService.GetFormatUsage is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetDownloadStats(context.Context, *connect.Request[v1.GetDownloadStatsRequest]) (*connect.Response[v1.GetDownloadStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.analytics.v1.AnalyticsService.GetDownloadStats is not implemented"))
}

func (UnimplementedAnalyticsServiceHandler) GetAnalyticsSummary(context.Context, *connect.Request[v1.GetAnalyticsSummaryRequest]) (*connect.Response[v1.GetAnalyticsSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("mediaservice.analytics.v1.AnalyticsService.GetAnalyticsSummary is not implemented"))
}
